modules/activiti-engine/src/main/java/org/activiti/engine/impl/util/io/StringStreamSource.java
When users attempt to parse a 'UTF-8'-encoded BPMN file (while the locale charset is not set as 'UTF-8') using following codes:
String fileContent = IOUtils.readStringAndClose(new InputStreamReader(new FileInputStream(modelFile), "utf-8"), (int) modelFile.length());
BpmnModel bpmnModel = new BpmnXMLConverter().convertToBpmnModel(new StringStreamSource(fileContent), false, false); 
the result bpmnModel is wrong because properties of all model elements are parsed in locale charset, Chinese 'gb2312' for example.
I think this error is caused by that StringStreamSource.getInputStream() returns a byte array stream using locale charset encoding, and that is why I add a new two-arguments constructor for StringStreamSource class.
Now, codes could be written as below:
BpmnModel bpmnModel = new …
=> enables StringStreamSource.getInputStream() return a byte array in given charset

modules/activiti-spring-boot/pom.xml, modules/activiti-spring-boot/spring-boot-samples/spring-boot-sample-actuator/src/main/java/activiti/Application.java, modules/activiti-spring-boot/spring-boot-samples/spring-boot-sample-basic/src/main/java/activiti/Application.java, modules/activiti-spring-boot/spring-boot-samples/spring-boot-sample-integration/src/main/java/activiti/Application.java, modules/activiti-spring-boot/spring-boot-samples/spring-boot-sample-jpa/src/main/java/activiti/Application.java, modules/activiti-spring-boot/spring-boot-samples/spring-boot-sample-rest-api/src/main/java/activiti/Application.java, modules/activiti-spring-boot/spring-boot-starters/pom.xml, modules/activiti-spring-boot/spring-boot-starters/spring-boot-starter-basic/pom.xml, modules/activiti-spring-boot/spring-boot-starters/spring-boot-starter-basic/src/main/java/org/activiti/spring/boot/RestApiAutoConfiguration.java, pom.xml
This change is backwards compatible for Spring framework revisions. The samples are using features new in Spring Boot 1.2, but they're just samples.
=> Move to Spring Boot 1.2.1 and Spring Framework 4.1

modules/activiti-crystalball/src/main/java/org/activiti/crystalball/simulator/impl/ScriptEventHandler.java, modules/activiti-engine/src/test/java/org/activiti/engine/test/concurrency/CompetingJobAcquisitionTest.java, modules/activiti-engine/src/test/java/org/activiti/engine/test/concurrency/CompetingJoinTest.java
Seeing pull request #540, I wrote a quick script to look for cases for other cases where the getLogger() classname did not match the name of the file.  The script found 3 occurrences.
=> Match getLogger() classname parameter to actual classname

modules/activiti-json-converter/src/main/java/org/activiti/editor/language/json/converter/BaseBpmnJsonConverter.java
According to my issue:
http://jira.codehaus.org/browse/ACT-2220
I have found the way to workaround with it.  Hope it helps.
Generally, Activiti modeler stores enum type form property in JSON as:
"enumValues":[ { "value":"yes", "$$hashKey":"0RN" }, { "value":"no", "$$hashKey":"0RO" }]
However, when deploy a model (i.e. converting a model from JSON to BPMN20.xml), we need to add nodes of value with id and name attributes, otherwise when start the process the combo box will be empty. For example:
\<activiti:formProperty id="approved" name="approved" type="enum"\>
\<activiti:value id="yes" name="yes"\>\</activiti:value\>
\<activiti:value id="no" name="no"\>\</activiti:value\>
\</activiti:formProperty\>
At the moment, in activiti-json-converter module, the call of setter of formValue for id …
=> Fix empty of enum form property of model created by Activiti modeler

userguide/src/en/ch07b-BPMN-Constructs.adoc
Call Activity super process image for credit check example was not displaying correctly, nor was it linking to the correct image.  
Corrected link syntax and found correct image file.
=> UserGuide: Fixed Call Activity super process example image

modules/activiti-engine/src/test/java/org/activiti/engine/test/bpmn/event/end/TerminateEndEventTest.java, modules/activiti-engine/src/test/resources/org/activiti/engine/test/bpmn/event/end/TerminateEndEventTest.testTerminateInSubProcessWithBoundary.bpmn
Additional test for pull #567
Test for terminateEventDefinition in subprocess with a boundary timer event (which leads to another terminateEventDefinition event) attached to it. Tested both terminating the subprocess and terminating the main process.
=> Terminate event in subprocess with Boundary timer test for pull #567

modules/activiti-engine/src/main/java/org/activiti/engine/impl/event/AbstractEventHandler.java
The Nullcheck of flowNode is unneeded as it was previously deferenced in the method call immediately above.
=> Nullcheck of flowNode is unneeded as it was previously deferenced.

modules/activiti-engine/src/main/java/org/activiti/engine/impl/cmd/StartProcessInstanceCmd.java, modules/activiti-engine/src/main/java/org/activiti/engine/impl/cmd/SubmitStartFormCmd.java, modules/activiti-engine/src/main/java/org/activiti/engine/impl/util/ProcessInstanceUtil.java
Our custom extensions (i.e attributes on process variables) require us to perform the following steps:
1) create a process instance
2) set variables 
3) set attributes (Hook needed for custom extensions)
3) start process.
This pull request refactors a few classes to allow us to extend the StartProcessInstanceCmd and still re-use the functionality provided in the ProcessInstanceUtil class. A similar PR was submitted to version 5 but was not brought forward with the Activiti 6 refactoring.
=> Refactor ProcessInstanceUtil & StartProcessInstanceCmd for extensibility

modules/activiti-engine/src/main/java/org/activiti/engine/impl/cmd/AbstractSetProcessDefinitionStateCmd.java, modules/activiti-engine/src/main/java/org/activiti/engine/impl/db/ActivitiVersion.java, modules/activiti-engine/src/main/java/org/activiti/engine/impl/scripting/JuelScriptEngineFactory.java, modules/activiti-engine/src/main/java/org/activiti/engine/impl/test/AbstractActivitiTestCase.java, modules/activiti-engine/src/main/java/org/activiti/engine/impl/test/TestHelper.java, modules/activiti-engine/src/test/java/org/activiti/engine/test/api/task/DelegateTaskTest.java, modules/activiti-engine/src/test/java/org/activiti/engine/test/api/task/TaskQueryTest.java, modules/activiti-engine/src/test/java/org/activiti/engine/test/api/task/TaskServiceTest.java, modules/activiti-engine/src/test/java/org/activiti/engine/test/bpmn/async/AsyncEmailTaskTest.java, modules/activiti-engine/src/test/java/org/activiti/engine/test/bpmn/mail/EmailSendTaskTest.java, modules/activiti-engine/src/test/java/org/activiti/engine/test/bpmn/mail/EmailServiceTaskTest.java, modules/activiti-engine/src/test/java/org/activiti/engine/test/history/HistoricProcessInstanceTest.java, modules/activiti-engine/src/test/java/org/activiti/examples/processdefinitions/ProcessDefinitionsTest.java
This change replaces calls to `Arrays.asList()` with a single argument with `Collections.singletonList()` which saves some memory.
=> use Collections.singletonList() for performance

modules/activiti-engine/src/main/java/org/activiti/engine/impl/IdentityServiceImpl.java
The saveGroup method of the IdentityServiceImpl class executes the SaveGroupCmd command with the GroupEntity implementation. This forces inherit from GroupEntity instead of implement directly from the "Group" interface.
=> Remove dependence of GroupEntity on SaveGroupCmd command

modules/activiti-engine/src/main/java/org/activiti/engine/delegate/event/impl/ActivitiEventDispatcherImpl.java
The cast in ActivitiEventDispatcherImpl.java conflicts with 'instanceOf'
Change the `instanceof` operand.
From:
```java
if (entity instanceof ProcessDefinition) {
result = (ProcessDefinitionEntity) entity;
```
To:
```java
if (entity instanceof ProcessDefinitionEntity) {`
result = (ProcessDefinitionEntity) entity;
```
It is most likely OK the way it is but this is more correct.
=> [FIX] Cast conflicts with 'instanceof'

modules/activiti-cxf/src/main/java/org/activiti/engine/impl/webservice/CxfWSDLImporter.java, modules/activiti-cxf/src/main/java/org/activiti/engine/impl/webservice/CxfWebServiceClient.java
The previous pull request #585 about [ACT-4012](https://activiti.atlassian.net/browse/ACT-4012) must be completed: JaxB custom bindings must be used not only when importing the WSDL, but also when creating web-service clients
=> ACT-4012: IllegalArgumentException when invoking a service task requiring a date

distro/src/readme.html
Now that `codehaus.org` is no more, update the JIRA references from: `http://jira.codehaus.org` to `https://activiti.atlassian.net`.
There is still one `codehous.org` reference as I could not find the location of the Wiki.
=> Update references in readme.html to use new JIRA location.

modules/activiti-engine/src/test/java/org/activiti/examples/bpmn/servicetask/ExpressionServiceTaskTest.java
The skip expression test case was using the wrong variable for the process (using `variable2` instead of `variable3`).
While in the test changed the last test to test case where `_ACTIVITI_SKIP_EXPRESSION_ENABLED` is false.
=> [FIX] skip expression test case

modules/activiti-engine/src/main/java/org/activiti/engine/impl/variable/JPAEntityScanner.java
Fix to address the issue described in ACT-2217:
JPAEntityScanner.getIdMethod() cannot cope with the case where the annotated @Id method overrides a generic method in the superclass.
In this case, Class.getMethods() will return both the declared method with the declared return type and a bridge method with a return type of the upper bounds from the generic class.
The fix involves adding a check on Method.isBridge() to ensure the method is not a bridge method.
=> ACT-2217 - JPAEntityScanner fix - Method.isBridge() check in getIdMethod

modules/activiti-engine/src/main/java/org/activiti/engine/impl/bpmn/deployer/BpmnDeployer.java, modules/activiti-engine/src/main/java/org/activiti/engine/impl/jobexecutor/TimerDeclarationImpl.java, modules/activiti-engine/src/main/java/org/activiti/engine/impl/persistence/entity/ExecutionEntity.java, modules/activiti-engine/src/test/java/org/activiti/engine/test/bpmn/event/timer/BoundaryTimerEventTest.java, modules/activiti-engine/src/test/resources/org/activiti/engine/test/bpmn/event/timer/BoundaryTimerEventTest.testNullExpressionOnTimer.bpmn20.xml
This allows schedule *or not* a BoundaryTimer Job, depending on dueDate execution variable value.
Null value  expression (dueDate or ISO duration) is supported; if NULL - BoundaryTimer ignored.
=> Conditional BoundaryTimer dueDate - based on NULL duration expression support.

modules/activiti-json-converter/src/main/java/org/activiti/editor/language/json/converter/SequenceFlowJsonConverter.java
This fix is for ACT 4025: execution listeners on sequence flows not
being imported into Explorer from a Designer file.
Added a check to SequenceFlowJsonConverter class to add execution
listeners to the properties node on XML —> JSON conversion inside
convertToJson method. Was unable to consistently reproduce the issue in
which execution listeners were not converted to XML on export.
=> ACT 4025 Sequence Flow bug fix

modules/activiti-cdi/src/main/java/org/activiti/cdi/impl/event/CdiExecutionListener.java, modules/activiti-cdi/src/main/java/org/activiti/cdi/impl/event/CdiTaskListener.java
For consistency purposes it might be better to fire the CdiBusinessProcessEvent using the ProcessEngineConfiguration clock's time.
=> Use ProcessEngineConfiguration clock's time.

modules/activiti-engine/src/main/java/org/activiti/engine/impl/persistence/entity/ExecutionEntityManager.java
Seems like VariableInstanceEntity.getByteArrayRef is never null. Not sure what to do here, but I get a SQL exception from oracle, because "deleteByteArrayNoRevisionCheck" tries to delete with 'where ID_ = null'. Maybe this works for other databases, but it sure isn't good?
=> Delete byte array only if there is one

modules/activiti-explorer/src/main/java/org/activiti/explorer/ui/task/TaskEventsPanel.java, modules/activiti-explorer/src/main/java/org/activiti/explorer/ui/task/TaskPage.java
If 
- I create a New Task in the explorer 
- complete it 
- post an event
Then an error message is shown with a stack trace in the log (task with a given id does not exist)
The Post Event should be enabled only when there is an active task.
=> [activiti-webapp-explorer] disable post event when no task is active

modules/activiti-engine/src/main/java/org/activiti/engine/impl/util/tree/ExecutionTreeNode.java
Fix string concatenations used as arguments of StringBuffer.append() calls
=> Fix string concatenation when used as argument of append() call

modules/activiti-camel/src/main/java/org/activiti/camel/CamelBehavior.java
In camel 2.16.0-SNAPSHOT... The use of "Exchange ex = new DefaultExchange(camelContextObj);" seems to generate an NPE, because it doesn't set the necessary properties on the exchange for the event to be notified correctly.
=> Change in Exchange creation

modules/activiti-engine/src/main/java/org/activiti/engine/impl/bpmn/helper/ClassDelegate.java, modules/activiti-engine/src/main/java/org/activiti/engine/impl/bpmn/parser/factory/DefaultActivityBehaviorFactory.java
This is a functional no-op change that allows us to add children of ClassDelegate that override the instantiateDelegate method.
This does change two public method names. I've updated the call sites in Activiti, but it is possible that external users are calling these methods.
=> Activiti6 Modify ClassDelegate to so that the way it instantiates classes can be overridden.

modules/activiti-engine/src/main/java/org/activiti/engine/impl/bpmn/helper/ClassDelegateFactory.java, modules/activiti-engine/src/main/java/org/activiti/engine/impl/bpmn/helper/DefaultClassDelegateFactory.java, modules/activiti-engine/src/main/java/org/activiti/engine/impl/bpmn/parser/factory/DefaultActivityBehaviorFactory.java, modules/activiti-engine/src/main/java/org/activiti/engine/impl/bpmn/parser/factory/DefaultListenerFactory.java
This change adds a ClassDelegateFactory interface along with an implementation that calls new ClassDelegate(...). DefaultActivityBehaviorFactory and TaskListenerFactory are updated to accept a ClassDelegateFactory and use it instead of calling new directly. By default they are constructed with the DefaultClassDelegateFactory so no additional configuration is required.
Also factored out getSkipExpressionFromServiceTask in DefaultActivityBehaviorFactory.
This change should be completely safe. It doesn't change any existing interfaces.
=> Add a ClassDelegateFactory interface.

modules/activiti-engine/src/test/java/org/activiti/engine/test/bpmn/event/timer/StartTimerEventRepeatWithoutN.java, modules/activiti-engine/src/test/resources/org/activiti/engine/test/bpmn/event/timer/StartTimerEventRepeatWithoutN.testStartTimerEventRepeatWithoutN.bpmn20.xml
The issue mentioned in https://activiti.atlassian.net/browse/ACT-4066 is valid for version 5.18.0
It is already resolved in snapshot version of 5.18.1.
Here is a test case to prove the correctness and make sure the problem does not return back.
=> test case for act-4066

modules/activiti-spring-boot/spring-boot-samples/pom.xml, modules/activiti-spring-boot/spring-boot-samples/spring-boot-sample-custom-mybatis-mapper/pom.xml, modules/activiti-spring-boot/spring-boot-samples/spring-boot-sample-custom-mybatis-mapper/src/main/java/activiti/Application.java, modules/activiti-spring-boot/spring-boot-samples/spring-boot-sample-custom-mybatis-mapper/src/main/java/activiti/mappers/CustomMybatisMapper.java, modules/activiti-spring-boot/spring-boot-samples/spring-boot-sample-custom-mybatis-mapper/src/main/resources/config/application.yml, modules/activiti-spring-boot/spring-boot-samples/spring-boot-sample-custom-mybatis-mapper/src/main/resources/mappers/CustomMybatisXmlMapper.xml, modules/activiti-spring-boot/spring-boot-samples/spring-boot-sample-custom-mybatis-mapper/src/main/resources/processes/basic.bpmn20.xml, modules/activiti-spring-boot/spring-boot-samples/spring-boot-sample-custom-mybatis-mapper/src/test/java/org/activiti/test/spring/boot/CustomMybatisMapperConfigurationTest.java, modules/activiti-spring-boot/spring-boot-samples/spring-boot-sample-custom-mybatis-mapper/src/test/resources/config/application.properties, modules/activiti-spring-boot/spring-boot-starters/activiti-spring-boot-starter-basic/src/main/java/org/activiti/spring/boot/AbstractProcessEngineAutoConfiguration.java, modules/activiti-spring-boot/spring-boot-starters/activiti-spring-boot-starter-basic/src/main/java/org/activiti/spring/boot/ActivitiProperties.java
Recently I had a problem with defining custom Mybatis mappers. I like clean solutions so I have added to activiti-spring-boot project possibility to define these mappers in spring boot configuration file. Additionally I have created sample project with two simple test cases.
=> Activiti Spring Boot configuration extended for custom Mybatis mappers 

userguide/src/en/ch07b-BPMN-Constructs.adoc, userguide/src/en/ch14-REST.adoc, userguide/src/en/ch17-Advanced.adoc, userguide/src/en/ch19-tooling.adoc
I was reviewing some of the recent pull requests and noticed some spelling errors.
The majority of the 517 "changes" are just white space.
=> Minor spelling changes to User Guide

modules/activiti-ui/activiti-app-logic/src/main/java/com/activiti/service/runtime/DeploymentServiceImpl.java
Really small change but it did take a while to find out why the formKey wasn't part of the json response from /runtime/tasks and /form/form-data REST calls
=> bug fix for null overwrite of formKey if it exissts

modules/activiti-engine/src/main/java/org/activiti/engine/impl/cfg/ProcessEngineConfigurationImpl.java
An explicitly set (custom) CommandContextFactory should be initialized.
=> Initialize custom CommandContextFactories

modules/activiti-bpmn-converter/src/main/java/org/activiti/bpmn/converter/child/ActivitiFailedjobRetryParser.java
This pull request is focused on resolving occurrences of Sonar rule squid:S2178 - Short-circuit logic should be used in boolean contexts
You can find more information about the issue here: 
https://dev.eclipse.org/sonar/coding_rules#q=squid:S2178
Please let me know if you have any questions.
Kirill Vlasov
=> Short-circuit logic should be used in boolean contexts

modules/activiti-bpmn-model/src/main/java/org/activiti/bpmn/model/ValuedDataObject.java
This pull request is focused on resolving occurrences of Sonar rule squid:S1201 - Methods named "equals" should override Object.equals(Object)
You can find more information about the issue here: 
https://dev.eclipse.org/sonar/coding_rules#q=squid:S1201
Please let me know if you have any questions.
Kirill Vlasov
=> Methods named "equals" should override Object.equals(Object)

modules/activiti-engine/src/main/java/org/activiti/engine/DynamicBpmnConstants.java, modules/activiti-engine/src/main/java/org/activiti/engine/RuntimeService.java, modules/activiti-engine/src/main/java/org/activiti/engine/impl/RuntimeServiceImpl.java, modules/activiti-engine/src/main/java/org/activiti/engine/impl/bpmn/deployer/BpmnDeployer.java, modules/activiti-engine/src/main/java/org/activiti/engine/impl/cmd/GetExecutionVariableInstanceCmd.java, modules/activiti-engine/src/main/java/org/activiti/engine/impl/cmd/GetExecutionVariableInstancesCmd.java, modules/activiti-engine/src/main/java/org/activiti/engine/runtime/VariableInstance.java, modules/activiti-engine/src/test/java/org/activiti/examples/variables/VariablesTest.java, modules/activiti-engine/src/test/resources/org/activiti/examples/variables/VariablesTest.testLocalizeVariables.bpmn20.xml
Summary:
* Add support for localizing variable name and descriptions via the DynamicBpmnService.
* Add support for populating localized values for DataObject names and descriptions into the DynamicBpmnService cache when a process definition is deployed.
* Update RuntimeService interface to support the retrieval of localized values for variables by introducing a new class VariableInstance.
=> Add support for localizing Variable names and descriptions.

modules/activiti-engine/src/main/java/org/activiti/engine/impl/ProcessDefinitionQueryImpl.java, modules/activiti-engine/src/test/java/org/activiti/engine/test/api/repository/ProcessDefinitionQueryByLatestTest.java, modules/activiti-engine/src/test/java/org/activiti/engine/test/api/repository/ProcessDefinitionQueryTest.java, modules/activiti-engine/src/test/resources/org/activiti/engine/test/repository/latest/name_testProcess1_one.bpmn20.xml, modules/activiti-engine/src/test/resources/org/activiti/engine/test/repository/latest/name_testProcess1_two.bpmn20.xml, modules/activiti-engine/src/test/resources/org/activiti/engine/test/repository/latest/name_testProcess2_one.bpmn20.xml, modules/activiti-engine/src/test/resources/org/activiti/engine/test/repository/latest/version_testProcess1_one.bpmn20.xml, modules/activiti-engine/src/test/resources/org/activiti/engine/test/repository/latest/version_testProcess1_two.bpmn20.xml, modules/activiti-engine/src/test/resources/org/activiti/engine/test/repository/latest/version_testProcess2_one.bpmn20.xml
ProcessDefinitionQuery throws ActivitiIllegalArgumentException when I used latestVersion() with name() and nameLike, and so on.
Because I thought all other criteria (name) don't defeats the purpose of the "latest" concept, I removed the restriction and added test cases.
https://github.com/Activiti/Activiti/blob/master/modules/activiti-engine/src/main/java/org/activiti/engine/impl/ProcessDefinitionQueryImpl.java
// latest() makes only sense when used with key() or keyLike()
if (latest && ( (id != null) || (name != null) || (nameLike != null) || (version != null) || (deploymentId != null) ) ){
throw new ActivitiIllegalArgumentException("Calling latest() can only be used in combination with key(String) and keyLike(String)");
}
According to the following exchanges,I thought that …
=> Removal the restriction that latestVersion() can only be used in combination with key() or keyLike()

modules/activiti-engine/src/main/java/org/activiti/engine/impl/bpmn/behavior/UserTaskActivityBehavior.java
Instead of creating and inserting the task entity in one go, this changes creates the task entity with necessary values and then inserts it.
=> Separate out TaskEntity creation and insertion.

modules/activiti-engine/src/main/java/org/activiti/engine/impl/db/DbSqlSession.java, modules/activiti-engine/src/main/java/org/activiti/engine/impl/variable/DeserializedObject.java, modules/activiti-engine/src/main/java/org/activiti/engine/impl/variable/SerializableType.java
Fix for serializable object compare when upgrading JDK version. 
Backport and reorganize of a fix done in activiti 5.16.4 (SHA-1: efcfb9a899127dc1a0132b074f107ae16d6b1aef)
=> MNT-15609 : Fix for serializable object compare when upgrading JDK version

modules/activiti-engine/src/main/java/org/activiti/engine/RepositoryService.java, modules/activiti-engine/src/main/java/org/activiti/engine/repository/ProcessDefinitionQuery.java
Not suspended but activate.
I removed the description of the old specification.
Relation to https://github.com/Activiti/Activiti/pull/788 .
=> Javadoc fix

userguide/src/en/ch19-tooling.adoc
Make the same change as pull request [#834](https://github.com/Activiti/Activiti/pull/834); that is add a missing 'i', so the change is from:
<pre>
docker push activit/activiti-single-image:latest
</pre>
to:
<pre>
docker push activiti/activiti-single-image:latest
</pre>
Also made the rest of the file match the current contents of the Version 5 section.
=> update doc to match V5 version

userguide/src/en/ch19-tooling.adoc
Add a missing 'i', so the change is from:
<pre>
docker push activit/activiti-single-image:latest
</pre>
to:
<pre>
docker push activiti/activiti-single-image:latest
</pre>
=> user guide typo in docker spec

modules/activiti-engine/src/main/java/org/activiti/engine/impl/context/Context.java
Make ResourceBundleControl class public so that the fallback logic can be reused in by our custom extension elements.
=> Make ResourceBundleControl class public.

modules/activiti-engine/src/main/java/org/activiti/engine/impl/RuntimeServiceImpl.java
The RuntimeService.getVariablesInstancesLocal(...) methods are returning non-local variables due to a value of 'false' being passed into the GetExecutionVariableInstancesCmd constructor. The value should be true.
=> Fix - getVariableInstancesLocal() returning non-local variables

modules/activiti-bpmn-converter/src/main/java/org/activiti/bpmn/converter/BpmnXMLConverter.java
BpmnXMLConverter has 2 createXML method calls. It looks like the second one has been updated already (since my last attempt at a pull request). It would be helpful to have the second method updated as well so we can generate alternative BPMNDI required for ACT-4116.
=> ACT-4135 increase accessibility of base createXML method

modules/activiti-engine/src/main/java/org/activiti/engine/history/HistoricProcessInstance.java, modules/activiti-engine/src/main/java/org/activiti/engine/history/HistoricProcessInstanceQuery.java, modules/activiti-engine/src/main/java/org/activiti/engine/impl/ExecutionQueryImpl.java, modules/activiti-engine/src/main/java/org/activiti/engine/impl/HistoricProcessInstanceQueryImpl.java, modules/activiti-engine/src/main/java/org/activiti/engine/impl/HistoricProcessInstanceQueryProperty.java, modules/activiti-engine/src/main/java/org/activiti/engine/impl/ProcessInstanceQueryImpl.java, modules/activiti-engine/src/main/java/org/activiti/engine/impl/persistence/entity/HistoricProcessInstanceEntity.java, modules/activiti-engine/src/main/java/org/activiti/engine/impl/persistence/entity/HistoricScopeInstanceEntity.java, modules/activiti-engine/src/main/java/org/activiti/engine/runtime/ExecutionQuery.java, modules/activiti-engine/src/main/java/org/activiti/engine/runtime/ProcessInstanceQuery.java, modules/activiti-engine/src/main/resources/org/activiti/db/mapping/entity/Execution.xml, modules/activiti-engine/src/main/resources/org/activiti/db/mapping/entity/HistoricProcessInstance.xml, modules/activiti-engine/src/test/java/org/activiti/engine/test/api/history/HistoricProcessInstanceAndVariablesQueryTest.java, modules/activiti-engine/src/test/java/org/activiti/engine/test/api/history/HistoricProcessInstanceQueryVersionTest.java, modules/activiti-engine/src/test/java/org/activiti/engine/test/api/history/HistoryServiceTest.java, modules/activiti-engine/src/test/java/org/activiti/engine/test/api/history/NonCascadeDeleteTest.java, modules/activiti-engine/src/test/java/org/activiti/engine/test/api/runtime/ExecutionAndProcessInstanceQueryVersionTest.java, modules/activiti-engine/src/test/java/org/activiti/engine/test/api/runtime/ExecutionQueryTest.java, modules/activiti-engine/src/test/java/org/activiti/engine/test/api/runtime/ProcessInstanceQueryTest.java, modules/activiti-engine/src/test/resources/org/activiti/engine/test/api/oneTaskProcess.bpmn20.xml, modules/activiti-engine/src/test/resources/org/activiti/engine/test/api/runtime/concurrentExecution.bpmn20.xml, modules/activiti-engine/src/test/resources/org/activiti/engine/test/api/runtime/oneTaskProcess.bpmn20.xml, modules/activiti-engine/src/test/resources/org/activiti/engine/test/api/runtime/oneTaskProcess2.bpmn20.xml
We added the search criteria related to process definition.
We added the following search criteria.
ExecutionQuery#processDefinitionCategory(String processDefinitionCategory)
ExecutionQuery#processDefinitionVersion(Integer processDefinitionVersion)
We added the following search criteria.
ProcessInstanceQuery#processDefinitionCategory(String processDefinitionCategory)
ProcessInstanceQuery#processDefinitionVersion(Integer processDefinitionVersion)
1. In the same way as ProcessInstanceQuery, we became able to get processDefinitionName/ProcessDefinitionKey/processDefinitionVersion/deploymentId by using HistoricProcessInstanceQuery.
In each case, we joined table ACT_RE_PROCDEF like ProcessInstanceQuery.
In consideration of RepositoryService.deleteDeployment(String deploymentId, false), we …
=> Add the process definition search criteria.

modules/activiti-engine/pom.xml
We excluded testcase from history level none mode.
Because testcases that we added in this following pull request don't work in history level none mode, we excluded them.
https://github.com/Activiti/Activiti/pull/833
https://github.com/Activiti/Activiti/pull/807
=> exclude testcase from history level none mode

modules/activiti-engine/src/main/java/org/activiti/engine/impl/ProcessInstanceHistoryLogQueryImpl.java, modules/activiti-engine/src/test/java/org/activiti/standalone/jpa/HistoricJPAVariableTest.java, modules/activiti-engine/src/test/resources/org/activiti/standalone/jpa/HistoricJPAVariableTest.testGetJPAEntityAsHistoricLog.bpmn20.xml, modules/activiti-engine/src/test/resources/org/activiti/standalone/jpa/HistoricJPAVariableTest.testGetJPAEntityAsHistoricVariable.bpmn20.xml
I solved the fix leaks of https://github.com/Activiti/Activiti/pull/755 .
NPE on referring Historic Variable(JPAEntityVariableType):
((HistoricVariableInstance) historicData).getValue();
java.lang.NullPointerException
at org.activiti.engine.impl.variable.JPAEntityMappings.findEntity(JPAEntityMappings.java:127)
at org.activiti.engine.impl.variable.JPAEntityMappings.getJPAEntity(JPAEntityMappings.java:121)
at org.activiti.engine.impl.variable.JPAEntityVariableType.getValue(JPAEntityVariableType.java:79)
at org.activiti.engine.impl.persistence.entity.HistoricVariableInstanceEntity.getValue(HistoricVariableInstanceEntity.java:129)
We are experiencing a NPE on referring HistoricVariableInstance(JPAEntityVariableType).
We are not experiencing a NPE on referring HistoricVariableInstance(String …
=> Fix NPE occured on referring Historic Variable(JPAEntityVariableType)

modules/activiti-engine/src/main/resources/org/activiti/db/create/activiti.mysql.create.engine.sql
Fix - modified columns timestamp default to null for ACT_RU_TASK and ACT_RE_DEPLOYMENT for mysql dialect, since Amazon RDS 5.6 is not using anymore defaults for timestamp. Same fix as in https://github.com/Activiti/Activiti/pull/720/
=> Amazon RDS 5.6 is not using anymore the defaults for timestamp

modules/activiti-engine/src/main/java/org/activiti/engine/impl/cfg/ProcessEngineConfigurationImpl.java
Activiti did not work when db2 was running on a linux ppc64 little endian. This patch simply add that to the lookup table used to identify the database type.
=> Add support for DB2/LINUXPPC64LE

modules/activiti-engine/src/main/java/org/activiti/engine/impl/context/Context.java, pom.xml
Hi Tijs,
Here is a pull request to update the Java version used by Activiti to 1.7 as we discussed via email along with a change to the localization fallback support to make use of the Local.forLanguageTag(..) method introduced in 1.7.
thanks,
Rob
=> Upgrade to Java 1.7 and use Locale.forLanguageTag() for localization

modules/activiti-engine/src/main/java/org/activiti/engine/impl/persistence/entity/ExecutionEntityManagerImpl.java
We need to know the process instance ID before inserting child executions. This is a simple re-ordering of when the parent attributes are set.
=> Set parent attributes of child execution before insertion.

modules/activiti-engine/src/main/java/org/activiti/engine/impl/ProcessInstanceQueryImpl.java, modules/activiti-engine/src/test/java/org/activiti/engine/test/api/runtime/ProcessInstanceAndVariablesQueryTest.java
Fixed a bug that arises when querying process instances with process variables like 'ignore case' conditions in an 'or' clause.
Fixes #856.
=> Fixed problem with process instances query

modules/activiti-engine/src/main/java/org/activiti/engine/impl/cfg/ProcessEngineConfigurationImpl.java, modules/activiti-engine/src/main/java/org/activiti/engine/impl/cmd/StartProcessInstanceByMessageCmd.java, modules/activiti-engine/src/main/java/org/activiti/engine/impl/cmd/StartProcessInstanceCmd.java, modules/activiti-engine/src/main/java/org/activiti/engine/impl/cmd/SubmitStartFormCmd.java, modules/activiti-engine/src/main/java/org/activiti/engine/impl/event/SignalEventHandler.java, modules/activiti-engine/src/main/java/org/activiti/engine/impl/util/ProcessInstanceHelper.java
Refactor ProcessInstanceUtils to be a helper class that can be configured in the ProcessEngineConfiguration to allow a subclass to override the behavior.  We require this change in order to override the processDataObjects method without copying the StartProcessInstanceCmd and the ProcessInstanceUtils classes into our codebase.
=> Refactor ProcessInstanceUtils

modules/activiti-engine/src/test/java/org/activiti/examples/bpmn/scripttask/ScriptTaskTest.java
Changed the script test so it works across JDK7 and JDK8 on OSX, Windows, and Linux.  This small change is "copied" from the method used in the previous test method (testAutoStoreVariables) at line 79.  This change "standardizes" the result so the assertEquals() is successful.
=> Refactor test to run under JDK7 and JDK8

modules/activiti-engine/src/main/java/org/activiti/engine/delegate/event/impl/ActivitiEventSupport.java
Use CopyOnWriteArrayList instead of ArrayList to prevent ConcurrentModificationException when a listener removes itself when iterating over the list in dispatchEvent(...)
=> Fix for #886

modules/activiti-explorer/src/main/java/org/activiti/explorer/ui/login/ExplorerLoginForm.java
.getURL() returns "http" scheme when SSL is provided by e.g. load-balancer.
Browser warning:
"Mixed Content: The page at 'https://domain/activiti-explorer/ui/APP/2/login' was loaded over a secure connection, but contains a form which targets an insecure endpoint 'http://domain/activiti-explorer/ui/1/loginHandler'. This endpoint should be made available over a secure connection."
If you hit "login", request is blocked by browser:
"Mixed Content: The page at 'https://domain/activiti-explorer/ui/APP/2/login' was loaded over HTTPS, but requested an insecure form action 'http://domain/activiti-explorer/ui/1/loginHandler'. This request has been blocked; the content must be served over HTTPS."
Solution is omitting the protocol (scheme) in order to preserve the one of the current page: …
=> omitting the protocol (scheme) / behind SSL proxy

modules/activiti-engine/src/main/java/org/activiti/engine/RuntimeService.java, modules/activiti-engine/src/main/java/org/activiti/engine/TaskService.java, modules/activiti-engine/src/main/java/org/activiti/engine/history/HistoricVariableInstanceQuery.java, modules/activiti-engine/src/main/java/org/activiti/engine/impl/HistoricVariableInstanceQueryImpl.java, modules/activiti-engine/src/main/java/org/activiti/engine/impl/RuntimeServiceImpl.java, modules/activiti-engine/src/main/java/org/activiti/engine/impl/TaskServiceImpl.java, modules/activiti-engine/src/main/java/org/activiti/engine/impl/cmd/GetExecutionsVariablesCmd.java, modules/activiti-engine/src/main/java/org/activiti/engine/impl/cmd/GetTasksLocalVariablesCmd.java, modules/activiti-engine/src/main/java/org/activiti/engine/impl/persistence/entity/VariableInstanceEntityManager.java, modules/activiti-engine/src/main/resources/org/activiti/db/mapping/entity/HistoricVariableInstance.xml, modules/activiti-engine/src/main/resources/org/activiti/db/mapping/entity/VariableInstance.xml, modules/activiti-engine/src/test/java/org/activiti/engine/test/api/runtime/RuntimeVariablesTest.java, modules/activiti-engine/src/test/java/org/activiti/engine/test/api/task/TaskVariablesTest.java, modules/activiti-engine/src/test/java/org/activiti/engine/test/history/HistoricVariableInstanceTest.java, modules/activiti-engine/src/test/resources/org/activiti/engine/test/api/runtime/RuntimeVariablesTest.testGetVariablesByExecutionIds.bpmn20.xml, modules/activiti-engine/src/test/resources/org/activiti/engine/test/api/runtime/variableScope.bpmn20.xml, modules/activiti-engine/src/test/resources/org/activiti/engine/test/api/task/TaskVariablesTest.testGetVariablesLocalByTaskIds.bpmn20.xml
We added the alternative query method to includeProcessVariables criteria.
We intend to resolve includeProcessVariables problem by this fix.
If we use includeProcessVariables, we cannot use LIMIT/OFFSET sql pagination and cannot get records after 20,000.
https://github.com/Activiti/Activiti/commit/093aed84401c7f7b33f1bdb3adaea5959b406bbd
https://forums.activiti.org/content/using-includeprocessvariables-historyservicecreatehistoricprocessinstancequery
https://forums.activiti.org/content/limitation-query-tasks-variables
https://forums.activiti.org/content/static-records-limit-taskentitymanager
We can resolve includeProcessVariables problem by dividing the query.
1. First query
We get only tasks/processInstances by setting includeProcessVariables flag false.
2. Second query
We get only …
=> Add the alternative query method to includeProcessVariables criteria.

modules/activiti-engine/src/main/java/org/activiti/engine/impl/bpmn/behavior/UserTaskActivityBehavior.java, modules/activiti-engine/src/test/java/org/activiti/engine/test/api/event/TaskEventsTest.java, modules/activiti-engine/src/test/java/org/activiti/engine/test/api/event/TestActivitiEntityEventTaskListener.java, modules/activiti-engine/src/test/resources/org/activiti/engine/test/api/event/TaskEventsTest.testEventFiring.bpmn20.xml
I have changed around the event firing for UserTaskActivityBehavior.  See ACT-2146.  This should make the event firing consistent.
I don't know all the implications of doing this but I have added a test which checks the new ordering.  The test is a little more complicated than anticipated because the in-memory Task object was getting updated after the event fired.  An external event listener would not have known about the changes.
I hope it meets your standards!
=> ACT-2146: Switch around event firing for Task creation

modules/activiti-bpmn-converter/src/main/java/org/activiti/bpmn/converter/SubprocessXMLConverter.java, modules/activiti-bpmn-converter/src/test/java/org/activiti/editor/language/xml/SubProcessConverterNoDITest.java, modules/activiti-bpmn-converter/src/test/java/org/activiti/editor/language/xml/SubProcessMultiDiagramConverterNoDITest.java, modules/activiti-bpmn-converter/src/test/java/org/activiti/editor/language/xml/SubProcessMultiDiagramConverterTest.java, modules/activiti-bpmn-converter/src/test/resources/subprocessmodel-noDI.bpmn, modules/activiti-bpmn-converter/src/test/resources/subprocessmultidiagrammodel-noDI.bpmn, modules/activiti-bpmn-converter/src/test/resources/subprocessmultidiagrammodel.bpmn
Note that this is dependent upon ACT-4135 as I separated out the base BpmnXMLConverter update top avoid future merge conflicts.
I tried to get it working with the existing Designer code, but got to where the next id was determined for each BPMN element within the UI and it was looping through and finding the next one. Wouldn't it be better to use a UUID or keep a key list somewhere with the next key value? Don't you use ids or sids for the web-based design tool already?
=> ACT-4116 Custom subprocess parser

modules/activiti-engine/src/main/java/org/activiti/engine/impl/TaskQueryImpl.java
This appears to fix the issue described in ACT-2081.  The code was retrieving the groups for the user only if candidateUser was set, but in the case of taskCandidateOrAssigned candidateUser is not set, instead userIdForCandidateAndAssignee is.  So added code to use that user if candidateUser is not set but userIdForCandidateAndAssignee is.
It would be great if this can be part of 5.20 or 5.19.0.3 if there is one.
=> Fix for ACT-2081, use userIdForCandidateAndAssignee for retrieving groups if set

modules/activiti-spring-boot/spring-boot-samples/spring-boot-sample-rest-api/src/test/java/org/activiti/test/spring/boot/RestApiAutoConfigurationTest.java, modules/activiti-spring-boot/spring-boot-starters/activiti-spring-boot-starter-basic/src/main/java/org/activiti/spring/boot/RestApiAutoConfiguration.java, modules/activiti-spring-boot/spring-boot-starters/activiti-spring-boot-starter-basic/src/main/java/org/activiti/spring/boot/SecurityAutoConfiguration.java
As described in #683/[ACT-4074](https://activiti.atlassian.net/browse/ACT-4074), customizing security configuration is difficult because one cannot exclude ```SecurityConfiguration``` without excluding entire ```RestApiAutoConfiguration```. This in turn requires the user to rewrite non security related parts of ```RestApiAutoConfiguration```.
This PR makes it easier for users to provide their own security confiugration.
=> Move security-related parts of RestApiAutoConfiguration to SecurityAutoConfiguration

modules/activiti-explorer/src/main/java/org/activiti/explorer/ui/management/deployment/DeploymentUploadReceiver.java
We improved that exceptions by deployment can be propagated to the call hierarchy.
https://forums.activiti.org/content/where-can-i-find-diagnostics-when-activiti-explorer-reports-deployment-failed
org.activiti.explorer.ui.management.deployment.DeploymentUploadReceiver.class#deployUploadedFile() does not propagate to the call hierarchy.
We changed to propagate exceptions to the call hierarchy.
Because the fix place is ui logic, we have no test case.
Because essential exception is hidden, non-essential exception occurs and is outputed as log.
```java
} catch (ActivitiException e) {
String errorMsg = e.getMessage().replace(System.getProperty("line.separator"), "<br/>");
notificationManager.showErrorNotification(Messages.DEPLOYMENT_UPLOAD_FAILED, errorMsg);
}
```
```java …
```
=> 【Activiti Explorer】Improvement of exception propagation

modules/activiti-bpmn-model/src/main/java/org/activiti/bpmn/model/Process.java
Two small changes to Process.java
(1) Remove redundant "association.getTargetRef() != null" check
(2) Remove "element != null" check as it appears that the previous line of code already assumes a non-null value
=> Small changes to Process.java

modules/activiti-image-generator/src/main/java/org/activiti/image/impl/DefaultProcessDiagramGenerator.java
Now  DefaultProcessDiagramGenerator has a bug:
It only draw the first process in bpmn model, if there are more than one processes in the model.
Example:
model in the eclipse desinger:
image generated by DefaultProcessDiagramGenerator:
This patch fixes it.
Image generated by the patched code:
=> fix: only draw the first process in bpmn model

modules/activiti-bpmn-converter/src/main/java/org/activiti/bpmn/converter/SubprocessXMLConverter.java
If no sequence flows are defined, the BPMNDI export step is skipped.
This is only an issue with partial (draft) diagrams that are saved prior
to completion using the our workflow definition editor. It is unlikely
that a valid diagram will have no sequence flows.
=> ACT-4191 BPMNDI data not generated without sequence flows

modules/activiti-engine/src/main/resources/org/activiti/db/create/activiti.db2.create.engine.sql
These two indexes are created on lines 291 and 292 and again on lines 382 and 283.
This request removes the second set.
```sql
create index ACT_IDX_JOB_PROCESS_INSTANCE_ID on ACT_RU_JOB(PROCESS_INSTANCE_ID_);
create index ACT_IDX_JOB_PROC_DEF_ID on ACT_RU_JOB(PROC_DEF_ID_);
```
=> Remove duplicate creation of indexes for DB2 engine table.

modules/activiti-engine/src/main/java/org/activiti/engine/impl/bpmn/behavior/BpmnActivityBehavior.java
As part of the [19fad05](https://github.com/Activiti/Activiti/commit/19fad051eb349eee9abd570bd44c86c8473c4983#diff-7f31b80a406e836752411a3dcdfa6766) commit on 8/27/2015, when ActivityExecution was removed it appears that a change to the method parameters was made but there are some subsequent changes to the code that are applicable:
(1) fix the javadoc
(2) remove the ExecutionEntity casts as the parameter is already an ExecutionEintity
(3) remove the instanceOf test for the same reason; I replaced it with a null check just to be safe
=> further changes after the removal of ActivityExecution

modules/activiti-ui/activiti-app/src/main/webapp/editor/styles/style-editor.css, modules/activiti-ui/activiti-app/src/main/webapp/editor/views/form-builder.html
there were issues with dragging palette items onto the form builder canvas.
especially adding them from the bottom of the canvas.
these are fixed.
in additional I've added some more spacing between the elements (and added a dotted border)
=> fixes issues with formbuilder item placement

modules/activiti-engine/src/main/resources/org/activiti/db/create/activiti.db2.create.engine.sql, modules/activiti-engine/src/main/resources/org/activiti/db/upgrade/activiti.db2.upgradestep.6001.to.6002.engine.sql
In create and update scripts for  the table ACT_RU_EXECUTION, the column  IS_COUNT_ENABLED_  specified the incorrect check() constraint variable.  Very simple change.
=> Error in DB2 create and update scripts

modules/activiti-bpmn-model/src/main/java/org/activiti/bpmn/model/ValuedDataObject.java, modules/activiti-engine/src/main/java/org/activiti/engine/impl/DataObjectImpl.java, modules/activiti-engine/src/main/java/org/activiti/engine/impl/cmd/GetDataObjectCmd.java, modules/activiti-engine/src/main/java/org/activiti/engine/impl/cmd/GetDataObjectsCmd.java, modules/activiti-engine/src/main/java/org/activiti/engine/impl/cmd/GetTaskDataObjectCmd.java, modules/activiti-engine/src/main/java/org/activiti/engine/impl/cmd/GetTaskDataObjectsCmd.java, modules/activiti-engine/src/test/java/org/activiti/examples/variables/VariablesTest.java
The initial DataObject support did not include a value for the type field. This pull request updates the various GetDataObject* commands to populate this field with the value as defined in the BPMN Model.  Exposing the value allows an API built on top of Activiti to prevent the type of DataObject object from changing when a client attempts to set a value.
=> Include type information from BPMN model in DataObject

modules/activiti5-test/src/test/java/org/activiti5/engine/test/db/DatabaseTablePrefixTest.java
Fix DatabaseTablePrefixTest in v5 compatibility tests by setting `setValidateExecutionRelationshipCountConfigOnBoot(false);` as is done in the v6 test version.
=> DatabaseTablePrefixTest in v5 compatibility

modules/activiti-engine/src/main/java/org/activiti/engine/impl/persistence/entity/ExecutionEntity.java, modules/activiti-engine/src/test/java/org/activiti/engine/test/bpmn/callactivity/CallActivityAdvancedTest.java, modules/activiti-engine/src/test/resources/org/activiti/engine/test/bpmn/callactivity/DataObject.fatherProcess.bpmn20.xml, modules/activiti-engine/src/test/resources/org/activiti/engine/test/bpmn/callactivity/DataObject.subProcess.bpmn20.xml
If defined a DataObject in a process, then invoked it with callActivity, DataObject will not enabled.
Please reference this following testcase, commenting `subProcessInstance.setVariables(dataObjectVars)` could re-produce this problem.
Please review the codes. Thanks.
=> DataObject will not enabled when invoked by callActivity

modules/activiti-bpmn-converter/src/main/java/org/activiti/bpmn/constants/BpmnXMLConstants.java, modules/activiti-bpmn-converter/src/main/java/org/activiti/bpmn/converter/CallActivityXMLConverter.java, modules/activiti-bpmn-model/src/main/java/org/activiti/bpmn/model/CallActivity.java, modules/activiti-engine/src/main/java/org/activiti/engine/impl/bpmn/behavior/CallActivityBehavior.java, modules/activiti-engine/src/main/java/org/activiti/engine/impl/bpmn/parser/factory/DefaultActivityBehaviorFactory.java, modules/activiti-engine/src/test/java/org/activiti/engine/test/bpmn/subprocess/CallActivityTest.java, modules/activiti-engine/src/test/resources/org/activiti/engine/test/bpmn/subprocess/SubProcessTest.testInheritVariablesCallActivity_childProcess.bpmn20.xml, modules/activiti-engine/src/test/resources/org/activiti/engine/test/bpmn/subprocess/SubProcessTest.testInheritVariablesCallActivity_mainProcess.bpmn20.xml, modules/activiti-engine/src/test/resources/org/activiti/engine/test/bpmn/subprocess/SubProcessTest.testNotInheritVariablesCallActivity_mainProcess.bpmn20.xml
We add the inheritVariables option to callActivityBehavior task.
If this option is true, sub process inherit all variables from parent process.
=> Add the inheritVariables option to callActivityBehavior task.

modules/activiti-cxf/src/main/java/org/activiti/engine/impl/webservice/CxfWebServiceClient.java, modules/activiti-cxf/src/test/java/org/activiti/engine/impl/webservice/WebServiceTaskTest.java, modules/activiti-cxf/src/test/resources/org/activiti/engine/impl/webservice/WebServiceTaskTest.testWebServiceInvocationWithEndpointAddressConfigured.bpmn20.xml, modules/activiti-cxf/src/test/resources/org/activiti/engine/impl/webservice/webservicemock.wsdl, modules/activiti-engine/src/main/java/org/activiti/engine/ProcessEngineConfiguration.java, modules/activiti-engine/src/main/java/org/activiti/engine/impl/bpmn/behavior/WebServiceActivityBehavior.java, modules/activiti-engine/src/main/java/org/activiti/engine/impl/bpmn/webservice/Operation.java, modules/activiti-engine/src/main/java/org/activiti/engine/impl/bpmn/webservice/OperationImplementation.java, modules/activiti-engine/src/main/java/org/activiti/engine/impl/webservice/SyncWebServiceClient.java, modules/activiti-engine/src/main/java/org/activiti/engine/impl/webservice/WSOperation.java
See [ACT-4206](https://activiti.atlassian.net/browse/ACT-4206):
> When using a service task implemented by a web-service, the endpoint address of the web-service is extracted from the WSDL imported into the process definition.
> Once you have deployed your process definition, it is possible to move the web-service, and its endpoint address changes. And now all new process instances will fail.
> To avoid this problem, we should be able to override the endpoint addresses at Activiti engine level, in its configuration for example.
Endpoint addresses are configured through a map where the key is the endpoint qualified name available in the WSDL, and the value its location
=> ACT-4206: Webservice endpoint address should be customizable

modules/activiti-engine/src/main/java/org/activiti/engine/delegate/event/ActivitiEventType.java, modules/activiti-engine/src/main/java/org/activiti/engine/impl/asyncexecutor/DefaultJobManager.java, modules/activiti-engine/src/test/java/org/activiti/engine/test/api/event/JobEventsTest.java
Neither the ACTIVITY_STARTED OR ENTITY_CREATED/ENTITY_INITIALIZED events can be used as an event type for a callback hook in a listener to know when a timer is started. ACTIVITY_STARTED does not work since a timer is not an 'activity'. The ENTITY_CREATED/ENTITY_INITIALIZED event types do not help since they are sent multiple times (i.e when the process has reached the timer element and when the timer is fired). This pulls request adds a new event (TIMER_STARTED) that is sent after a timer is scheduled which a listener can use.
=> Add support for TIMER_SCHEDULED event.

modules/activiti-bpmn-converter/src/main/java/org/activiti/bpmn/converter/BpmnXMLConverter.java, modules/activiti-bpmn-model/src/main/java/org/activiti/bpmn/model/FlowElement.java, modules/activiti-dmn-api/src/main/java/org/activiti/dmn/api/DecisionExecutionAuditContainer.java, modules/activiti-engine/src/main/java/org/activiti/engine/impl/bpmn/behavior/BoundaryCompensateEventActivityBehavior.java, modules/activiti-engine/src/main/java/org/activiti/engine/impl/bpmn/behavior/IntermediateCatchEventActivityBehavior.java, modules/activiti-engine/src/main/java/org/activiti/engine/impl/bpmn/behavior/TerminateEndEventActivityBehavior.java, modules/activiti-engine/src/main/java/org/activiti/engine/impl/bpmn/listener/ListenerNotificationHelper.java, modules/activiti-engine/src/main/java/org/activiti/engine/impl/bpmn/parser/BpmnParse.java, modules/activiti-engine/src/main/java/org/activiti/engine/impl/el/JsonNodeELResolver.java, modules/activiti-engine/src/main/java/org/activiti/engine/impl/event/AbstractEventHandler.java, modules/activiti-engine/src/main/java/org/activiti/engine/impl/event/SignalEventHandler.java, modules/activiti-engine/src/main/java/org/activiti/engine/impl/util/ExecutionGraphUtil.java, modules/activiti-engine/src/main/java/org/activiti/engine/impl/util/FormHandlerUtil.java, modules/activiti-engine/src/main/java/org/activiti/engine/impl/util/TimerUtil.java
Since the instanceof operator always returns false for null, there is no need to have an additional null check.
Here is an example of a violation:
if (x != null && x instanceof String) { ... }
The change to the code is:
if (x instanceof String) { ... }
=> Unnecessary 'null' check before 'instanceof' expression

modules/activiti-engine/src/main/java/org/activiti/engine/impl/bpmn/behavior/ShellActivityBehavior.java
Unnecessary 'null' which are followed by an 'equals()' call with a constant argument can be simplified.
For example:
if (s != null && s.equals("literal")) {}
The fix is to replace that with:
if ("literal".equals(s)) {}
=> Unnecessary 'null' check before 'equals()' call

userguide/src/en/ch14-REST.adoc
The REST api doc incorrectly had the a property, "dataUrl" coming
back from calls to GET repository/deployments/{deploymentId}/resources
The actual property is "contentUrl".
=> fix incorrect "dataUrl" response property in REST api doc

modules/activiti-cxf/src/test/java/org/activiti/engine/impl/webservice/AbstractWebServiceTaskTest.java, modules/activiti-cxf/src/test/java/org/activiti/engine/impl/webservice/WebServiceTaskTest.java
Improve unit tests of `WebServiceTask` provided by `activiti-cxf` introducing a constant for the web-service URL. This constant is used to locate the test web-service on the server and client sides.
=> Improve unit tests of activiti-cxf introducing a constant for the webservice URL

userguide/src/en/ch14-REST.adoc
The RestIdentityLink class, which is being used for serialization
in identity link creation and retrieval, has the properties,
"group", and "user".  The doc used "groupId" and "userId" instead.
Creating identity links using the exact doc sample syntax resulted
in the error,
"A group or a user is required to create an identity link."
Note: I left "groupId" and "userId" when it was part of a URL, for example:
"GET identity/users/{userId}"  since this makes more sense.  I could be
wrong in having left these.
=> identitylinks user & group docs did not match implementation

modules/activiti-engine/src/main/java/org/activiti/engine/impl/AbstractVariableQueryImpl.java, modules/activiti-engine/src/main/resources/org/activiti/db/mapping/entity/Execution.xml, modules/activiti-engine/src/main/resources/org/activiti/db/mapping/entity/HistoricTaskInstance.xml, modules/activiti-engine/src/main/resources/org/activiti/db/mapping/entity/Task.xml, modules/activiti-engine/src/test/java/org/activiti/engine/test/api/history/HistoricTaskAndVariablesQueryTest.java, modules/activiti-engine/src/test/java/org/activiti/engine/test/api/runtime/ProcessInstanceAndVariablesQueryTest.java, modules/activiti-engine/src/test/java/org/activiti/engine/test/api/task/TaskAndVariablesQueryTest.java, modules/activiti-engine/src/test/resources/org/activiti/engine/test/api/history/HistoricTaskAndVariablesQueryTest.testOrQueryMultipleVariableValues.bpmn20.xml, modules/activiti-engine/src/test/resources/org/activiti/engine/test/api/task/TaskAndVariablesQueryTest.testOrQuery.bpmn20.xml, modules/activiti-engine/src/test/resources/org/activiti/engine/test/api/task/TaskAndVariablesQueryTest.testOrQueryMultipleVariableValues.bpmn20.xml
I addressed the same problem of #989 for Process Instance, Task and Historic Task queries.
=> Remaining optimizations for 'or queries' with multiple process variable values

modules/activiti-rest/src/main/java/org/activiti/rest/service/api/engine/variable/QueryVariable.java
Otherwise, serializing the QueryRequest object using
JSONNode ends up creating a "variableOperation" property
instead of an "operation" property, causing an error
on the server side.
=> Implement setOperation for serialization purposes

modules/activiti-camel/src/test/java/org/activiti/camel/revisited/AsyncProcessRevisitedTest.java
increased the waiting time increase the waiting time, (just to wait enough also for slow machines)
=> fix for AsyncProcessRevisitedTest

modules/activiti-engine/src/main/java/org/activiti/engine/impl/persistence/entity/VariableScopeImpl.java, modules/activiti-engine/src/test/java/org/activiti/engine/test/api/task/TaskServiceTest.java
ACT-4144 - fixed search variables by activityInstanceID in HistoricDetailQuery. Added unit test.
More details in the comments of the Jira bug:
https://activiti.atlassian.net/browse/ACT-4144
Signed-off-by: Vlad Stan <stan.v.vlad@gmail.com>
=> ACT-4144 - fixed search variables by activityInstanceID in HistoricDetailQuery. Added unit test.

modules/activiti-engine/src/main/java/org/activiti/engine/impl/persistence/entity/ExecutionEntity.java, modules/activiti-engine/src/test/java/org/activiti/engine/test/bpmn/event/compensate/CompensateEventTest.java, modules/activiti-engine/src/test/resources/org/activiti/engine/test/bpmn/event/compensate/CompensateEventTest.testCompensateTwoSubprocesses.bpmn20.xml, modules/activiti-engine/src/test/resources/org/activiti/engine/test/bpmn/event/compensate/SubProcess1.bpmn20.xml, modules/activiti-engine/src/test/resources/org/activiti/engine/test/bpmn/event/compensate/SubProcess2.bpmn20.xml
ACT-4102 For multiple executions paths, only the compensation(s) on the current execution was executed.
Added unit test.
More details in the comments of the Jira bug:
https://activiti.atlassian.net/projects/ACT/issues/ACT-4102
Signed-off-by: Vlad Stan stan.v.vlad@gmail.com
=> act-4102 trigger all compensation event for process

modules/activiti-engine/src/main/java/org/activiti/engine/impl/persistence/entity/AttachmentEntityManager.java, modules/activiti-engine/src/main/java/org/activiti/engine/impl/persistence/entity/HistoricProcessInstanceEntityManager.java, modules/activiti-engine/src/test/java/org/activiti/engine/test/api/event/AttachmentEventsTest.java
We fixed that attachment entity attached to the process instance is deleted when deleting historic process instance.
If we specify null as taskId when using TaskService.createAttachment method, we can attach file to not task but process instance.
https://www.activiti.org/javadocs/org/activiti/engine/TaskService.html#createAttachment-java.lang.String-java.lang.String-java.lang.String-java.lang.String-java.lang.String-java.io.InputStream-
In this case, we cannot delete attachment entity by deleting historic process instance.
We fixed that attachment entity event on historicTaskDelete contains processDefinitionId and processInstanceId and executionId by using history data.
=> Attachment entity attached to the process instance is not deleted when process instance is deleted.

modules/activiti-engine/src/test/java/org/activiti/standalone/escapeclause/HistoricTaskQueryEscapeClauseTest.java
just give enough time to the engine to start the processes in the desired order
=> fixed the tests in HistoricTaskQueryEscapeClauseTest

modules/activiti-engine/src/main/java/org/activiti/engine/impl/HistoricTaskInstanceQueryImpl.java, modules/activiti-engine/src/main/java/org/activiti/engine/impl/TaskQueryImpl.java, modules/activiti-engine/src/main/java/org/activiti/engine/task/TaskInfoQuery.java, modules/activiti-engine/src/main/resources/org/activiti/db/mapping/entity/HistoricTaskInstance.xml, modules/activiti-engine/src/main/resources/org/activiti/db/mapping/entity/Task.xml, modules/activiti-engine/src/test/java/org/activiti/engine/test/api/task/TaskQueryTest.java, modules/activiti5-engine/src/main/java/org/activiti5/engine/impl/HistoricTaskInstanceQueryImpl.java, modules/activiti5-engine/src/main/java/org/activiti5/engine/impl/TaskQueryImpl.java, modules/activiti5-engine/src/main/java/org/activiti5/engine/task/TaskInfoQuery.java, modules/activiti5-engine/src/main/resources/org/activiti5/db/mapping/entity/HistoricTaskInstance.xml, modules/activiti5-engine/src/main/resources/org/activiti5/db/mapping/entity/Task.xml
It takes a list of users as parameter and returns tasks with an assignee in the list. Currently, TaskInfoQuery interface provides methods for querying or filtering tasks assigned to a specific user. If one would like to query for tasks assigned to several users, he has to query for individual users and then merge them to create the complete list. This method solves this problem.
Similar method "taskCandidateGroupIn" for querying tasks of groups is already there in activiti. This will add similar functionality for querying tasks of users as well.
=> Added taskAssigneeIds method

modules/activiti-engine/src/main/java/org/activiti/engine/delegate/event/ActivitiEventType.java, modules/activiti-engine/src/main/java/org/activiti/engine/impl/bpmn/behavior/BoundaryMessageEventActivityBehavior.java, modules/activiti-engine/src/main/java/org/activiti/engine/impl/bpmn/behavior/IntermediateCatchMessageEventActivityBehavior.java, modules/activiti-engine/src/main/java/org/activiti/engine/impl/util/ProcessInstanceHelper.java, modules/activiti-engine/src/test/java/org/activiti/engine/test/api/event/ActivityEventsTest.java
Added message waiting event type for intermediate or boundary or sub-process start message catching event. Whenever any activity creates message event subscription, this event will be dispatched to indicate that activity is waiting for message.
=> Added message waiting event type

pom.xml
AssertJ will replace classic JUnit assertions when writing tests.
It should be added as dependency in each maven module when it is used for the first time.
=> Add dependency to AssertJ

modules/activiti-engine/pom.xml, modules/activiti-engine/src/main/java/org/activiti/engine/impl/bpmn/behavior/SequentialMultiInstanceBehavior.java, modules/activiti-engine/src/main/java/org/activiti/engine/impl/bpmn/helper/ScopeUtil.java, modules/activiti-engine/src/main/java/org/activiti/engine/impl/bpmn/helper/SubProcessVariableSnapshotter.java, modules/activiti-engine/src/test/java/org/activiti/engine/impl/bpmn/helper/SubProcessVariableSnapshotterTest.java, modules/activiti-engine/src/test/java/org/activiti/engine/test/bpmn/multiinstance/MultiInstanceTest.java
- The variables nrOfInstances, nrOfCompletedInstances and nrOfActiveInstances are only created for the outer instance.
They are, however, still available in the context of the inner instances when using the method getVariables instead of getVariablesLocal
- The variable loopCounter is only created for the inner instances
=> Fix multi instance

modules/activiti-bpmn-model/src/main/java/org/activiti/bpmn/model/BaseElement.java, modules/activiti-engine/src/main/java/org/activiti/engine/impl/bpmn/behavior/MultiInstanceActivityBehavior.java, modules/activiti-engine/src/main/java/org/activiti/engine/impl/cmd/ExecuteJobsCmd.java, modules/activiti-engine/src/main/java/org/activiti/engine/impl/juel/ExpressionFactoryImpl.java, modules/activiti-engine/src/main/java/org/activiti/engine/impl/persistence/entity/AttachmentEntityManager.java, modules/activiti-engine/src/main/java/org/activiti/engine/impl/persistence/entity/VariableScopeImpl.java
These items were all flagged by the sonar report as points where a null check was needed. Hopefully it is clear that in each a null check has been added, except for the change to AttachmentEntityManager where the change was to move the for-block inside of an existing null check that preceded it ("if (dispatchEvents && attachments != null && !attachments.isEmpty())").
=> changes recommended by sonar for possible null pointer dereference

modules/activiti-ui/activiti-app/src/main/webapp/idm/views/idm-group-mgmt.html
Hi,
When adding a new group to the identity management,  group list ui getting scroll instead of showing created group below even if it has enough space to show. for the reference i have attached the screenshot and issue highlighted with red mark below . 
Before
After
Which is handled with this fix.
Thanks,
Ravi kumar Tadela
=> Fix for ui issue related to list of groups in idm-group-management page

modules/activiti-engine/src/main/java/org/activiti/engine/impl/el/ExpressionManager.java
Allow the ExpressionManager to create an ELResolver without a variableScope
=> Allow the ExpressionManager to create an ELResolver without a variable scope

modules/activiti-webapp-rest2/src/main/webapp/docs/index.html
Hi,
By default swagger host set to "localhost:8080" in pom.xml. When there is any changes in host of activiti-rest other then "localhost:8080", then swagger docs host doesn't change dynamically. So that rest call can't be called successfully. Which is handled with this fix.
=> Setting dynamic hostname for swagger docs of activiti-rest

activiti-spring-boot/spring-boot-samples/spring-boot-sample-hal-rest-api/README.md, activiti-spring-boot/spring-boot-samples/spring-boot-sample-hal-rest-api/springboot-realm.json
Small addition to keycloak config that provides an admin user for the docker container and update to README to say how to access container's admin console.
=> admin user for keycloak docker container

activiti-bpmn-converter/src/main/java/org/activiti/bpmn/converter/util/BpmnXMLUtil.java, activiti-bpmn-layout/src/main/java/org/activiti/bpmn/BPMNLayout.java, activiti-engine/pom.xml, activiti-image-generator/src/main/java/org/activiti/image/impl/DefaultProcessDiagramCanvas.java, activiti-spring-boot/spring-boot-starters/activiti-spring-boot-starter-basic/src/main/java/org/activiti/spring/boot/EndpointAutoConfiguration.java, activiti-spring-boot/spring-boot-starters/activiti-spring-boot-starter-basic/src/main/java/org/activiti/spring/integration/Activiti.java, activiti-spring/src/main/java/org/activiti/spring/SpringAsyncExecutor.java, activiti-spring/src/main/java/org/activiti/spring/autodeployment/AutoDeploymentStrategy.java, activiti-spring/src/main/java/org/activiti/spring/impl/test/CleanTestExecutionListener.java
The javadoc generation currently fails - and it is requested by the maven-release-plugin.
This merge requests improve things by making it pass.
But I cheated in the `activiti-engine` module, which has more than 100 errors, so I disabled the check...
=> Attempt to fix javadoc errors - except in activiti-engine

modules/activiti-engine/src/main/java/org/activiti/engine/impl/persistence/entity/VariableInstanceEntity.java
null processDefinitionId passed while creating new VARIABLE_DELETE event. processDefinitionId is require to get tenant Id. Without processDefinitionId VARIABLE_DELETE event will not have tenant Id
=> Process Definition Id was null

activiti-services/activiti-services-audit/activiti-services-audit-jpa/src/test/resources/application-producer-test.properties
@erdemedeiros @ryandawsonuk please review and merge. Notice that we will need this flag in tests for the query service and all the other services that doesn't require the registry to be tested.
=> disabling discovery for tests

pom.xml
Specifying the proper version of assertj-core in the Maven generator plugin.
Side effect: fixes the build on Bamboo...
=> BDE-1243 Fix dependency of assertj-core in generator plugin

activiti-services/activiti-services-query/activiti-services-query-rest/src/main/java/org/activiti/services/query/events/AbstractProcessEngineEvent.java, activiti-services/activiti-services-query/activiti-services-query-rest/src/main/java/org/activiti/services/query/events/IgnoredProcessEngineEvent.java
Closes #1428. Add a new type to map all the events to be ignored by the query service.
This avoid exceptions when jackson tries to deserialize events.
=> Ignore unknown events

activiti-services/activiti-services-query/activiti-services-query-graphql/src/test/java/org/activiti/services/query/qraphql/autoconfigure/ActivitiGraphQLSchemaBuildTest.java, activiti-services/activiti-services-query/activiti-services-query-model/src/main/java/org/activiti/services/query/model/ProcessInstance.java, activiti-services/activiti-services-query/activiti-services-query-rest/src/main/java/org/activiti/services/query/events/handlers/ProcessStartedHandler.java, activiti-services/activiti-services-query/activiti-services-query-rest/src/main/java/org/activiti/services/query/events/handlers/TaskCreatedEventHandler.java, activiti-services/activiti-services-query/activiti-services-query-rest/src/main/java/org/activiti/services/query/events/handlers/VariableCreatedEventHandler.java, activiti-services/activiti-services-query/activiti-services-query-rest/src/test/java/org/activiti/services/query/events/handlers/ProcessStartedHandlerTest.java, activiti-services/activiti-services-query/activiti-services-query-rest/src/test/resources/jpa-test.sql
This PR fixes attribute data type inconsistencies in query entities. For example, @Id field processInstanceId in ProcessInstance is declared as Long type, and  as String in Task and Variable entities. It creates inconsistency in GraphQL and Rest API schemas visible to end-user.  
I have also fixed tests to verify correct data type are used in generated Rest and GraphQL schemas
=> Fix Query Model ProcessInstance @Id attribute to use String data type

activiti-engine/src/main/java/org/activiti/engine/impl/cmd/integration/RetrieveIntegrationContextsCmd.java, activiti-engine/src/main/java/org/activiti/engine/impl/persistence/entity/data/integration/IntegrationContextDataManager.java, activiti-engine/src/main/java/org/activiti/engine/impl/persistence/entity/data/integration/MybatisIntegrationContextDataManager.java, activiti-engine/src/main/java/org/activiti/engine/impl/persistence/entity/integration/IntegrationContextManager.java, activiti-engine/src/main/java/org/activiti/engine/impl/persistence/entity/integration/IntegrationContextManagerImpl.java, activiti-engine/src/main/java/org/activiti/engine/integration/IntegrationContextService.java, activiti-engine/src/main/java/org/activiti/engine/integration/IntegrationContextServiceImpl.java, activiti-engine/src/test/java/org/activiti/engine/impl/cmd/integration/RetrieveIntegrationContextCmdTest.java, activiti-engine/src/test/java/org/activiti/engine/impl/persistence/entity/data/MybatisIntegrationContextDataManagerTest.java, activiti-engine/src/test/java/org/activiti/engine/impl/persistence/entity/integration/IntegrationContextManagerImplTest.java, activiti-engine/src/test/java/org/activiti/engine/integration/IntegrationContextServiceImplTest.java
Fix the rare and intermittent org.apache.ibatis.exceptions.TooManyResultsException: Expected one result (or null) to be returned by selectOne(), but found: 2 error
org.activiti.engine.integration.IntegrationContextServiceImpl.findIntegrationContextByExecutionId(IntegrationContextServiceImpl.java:34)
org.activiti.services.connectors.channel.ServiceTaskIntegrationResultEventHandler.receive(ServiceTaskIntegrationResultEventHandler.java:60)
org.activiti.engine.impl.persistence.entity.data.integration.MybatisIntegrationContextDataManager.findIntegrationContextByExecutionId(MybatisIntegrationContextDataManager.java:42)
=> fix intermittent TooManyResultsException

modules/activiti-engine/src/main/java/org/activiti/engine/impl/bpmn/behavior/CallActivityBehavior.java, modules/activiti-engine/src/test/java/org/activiti/engine/test/bpmn/subprocess/CallActivityTest.java
I fixed the bug that the history of businessKey cannot be updated in case of using inheritBusinessKey.
This bug is related to https://github.com/Activiti/Activiti/pull/1567.
=> Update history of inheritBusinessKey

activiti-api/activiti-process-runtime-api-impl/src/main/java/org/activiti/runtime/api/connector/DefaultServiceTaskBehavior.java, activiti-api/activiti-process-runtime-api-impl/src/test/java/org/activiti/runtime/api/connector/DefaultServiceTaskBehaviorTest.java
Fixes #1943
In addition of checking if there is a bean with the given implementation name, check the bean type: it should be a connector
=> Fix cloud connectors

activiti-engine/src/main/java/org/activiti/engine/impl/bpmn/deployer/BpmnDeployer.java, activiti-engine/src/main/java/org/activiti/engine/impl/repository/DeploymentBuilderImpl.java, activiti-engine/src/main/java/org/activiti/engine/repository/DeploymentBuilder.java, activiti-engine/src/test/java/org/activiti/engine/impl/repository/DeploymentBuilderImplTest.java, activiti-spring-boot-starter/src/main/java/org/activiti/spring/boot/AbstractProcessEngineAutoConfiguration.java, activiti-spring-boot-starter/src/main/java/org/activiti/spring/boot/AbstractProcessEngineConfiguration.java, activiti-spring-boot-starter/src/main/java/org/activiti/spring/boot/ActivitiProperties.java, activiti-spring-boot-starter/src/main/java/org/activiti/spring/boot/ProcessDefinitionResourceFinder.java, activiti-spring-boot-starter/src/main/java/org/activiti/spring/boot/ProcessEngineAutoConfiguration.java, activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/ProcessDefinitionResourceFinderIT.java, activiti-spring-boot-starter/src/test/resources/processes-empty/non-process-definition-file.txt, activiti-spring/src/main/java/org/activiti/spring/autodeployment/DefaultAutoDeploymentStrategy.java, activiti-spring/src/main/java/org/activiti/spring/autodeployment/ResourceParentFolderAutoDeploymentStrategy.java, activiti-spring/src/main/java/org/activiti/spring/autodeployment/SingleResourceAutoDeploymentStrategy.java, activiti-spring/src/test/java/org/activiti/spring/test/autodeployment/AbstractAutoDeploymentStrategyTest.java, activiti-spring/src/test/java/org/activiti/spring/test/autodeployment/DefaultAutoDeploymentStrategyTest.java, activiti-spring/src/test/java/org/activiti/spring/test/autodeployment/ResourceParentFolderAutoDeploymentStrategyTest.java, activiti-spring/src/test/java/org/activiti/spring/test/autodeployment/SingleResourceAutoDeploymentStrategyTest.java
Fixes #1965
Instead of failing when the folder does not exist just log an warning
=> Avoid failure when process definitions folder is not found

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.build:activiti-parent` to: `7.0.26`
=> update org.activiti.build:activiti-parent to 7.0.26

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.build:activiti-parent` to: `7.0.27`
=> update org.activiti.build:activiti-parent to 7.0.27

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.build:activiti-parent` to: `7.0.28`
=> update org.activiti.build:activiti-parent to 7.0.28

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.build:activiti-parent` to: `7.0.29`
=> update org.activiti.build:activiti-parent to 7.0.31

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.build:activiti-parent` to: `7.0.39`
=> update org.activiti.build:activiti-parent to 7.0.39

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.build:activiti-parent` to: `7.0.40`
=> update org.activiti.build:activiti-parent to 7.0.40

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.api:activiti-api-dependencies` to: `7.0.47`
=> update org.activiti.api:activiti-api-dependencies to 7.0.47

activiti-spring-boot-starter/pom.xml, activiti-spring-boot-starter/src/main/java/org/activiti/spring/ProcessDeployedEventProducer.java, activiti-spring-boot-starter/src/main/java/org/activiti/spring/boot/ProcessEngineAutoConfiguration.java, activiti-spring-boot-starter/src/test/java/org/activiti/spring/ProcessDeployedEventProducerTest.java, activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/process/DeployedProcessesListener.java, activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/process/ProcessDeployedEventIT.java
The events will be sent when the Spring Boot application is ready (ApplicationReadyEvent). A ProcessDeployedEvent will be triggered for every process deployed every time the application starts. Listeners to these events should be able do deal with duplicates.
Refs https://github.com/Activiti/Activiti/issues/2149
=> Trigger process deployed events

pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.core.common:activiti-core-common-dependencies` to: `7.0.18`
=> update org.activiti.core.common:activiti-core-common-dependencies to 7.0.18

activiti-spring-boot-starter/src/main/java/org/activiti/spring/boot/AbstractProcessEngineAutoConfiguration.java
So that Spring can choose between to two available beans
Refs https://github.com/Activiti/Activiti/issues/2206
=> Rename TaskExecutor to match with applicationTaskExecutor

.mergify.yml, activiti-api-impl/pom.xml, activiti-bpmn-converter/pom.xml, activiti-bpmn-layout/pom.xml, activiti-bpmn-model/pom.xml, activiti-core-dependencies-tests/pom.xml, activiti-core-dependencies/pom.xml, activiti-engine/pom.xml, activiti-image-generator/pom.xml, activiti-json-converter/pom.xml, activiti-process-validation/pom.xml, activiti-spring-app-process/pom.xml, activiti-spring-boot-starter/pom.xml, activiti-spring/pom.xml, pom.xml
This PR proposes to add dependency convergence tests for external activiti-api and activiti-core-common dependencies as part of #2198.
Also, added same parent version convergence test as part of #2200 
It also fixes Maven-deploy-plugin configuration to follow best practice for deploying multi-module project at the end. (See #2172)
=> feat: add activiti-core-dependencies-tests module 

activiti-spring-boot-starter/src/main/java/org/activiti/spring/boot/AbstractProcessEngineAutoConfiguration.java, activiti-spring-boot-starter/src/main/java/org/activiti/spring/boot/ProcessEngineAutoConfiguration.java, activiti-spring-boot-starter/src/main/resources/META-INF/spring.factories
as TaskExecutionAutoConfiguration is the one providing a bean of type `TaskExecutor`
Refs https://github.com/Activiti/Activiti/issues/2206
=> Load ProcessEngineAutoConfiguration after TaskExecutionAutoConfiguration

activiti-bpmn-converter/src/main/java/org/activiti/bpmn/converter/parser/MessageParser.java, activiti-bpmn-converter/src/test/java/org/activiti/editor/language/xml/MessageConverterTest.java, activiti-bpmn-converter/src/test/resources/message.bpmn
Proposed fix for Issue #2188.
The change is very simple - treat un-prefixed `itemRef`-s as being in the `targetNamespace` but it would be good if somebody could confirm if the behavior is actually correct.
Added a corresponding test.
=> Issue 2188

activiti-api-impl/activiti-api-process-runtime-impl/src/main/java/org/activiti/runtime/api/impl/ProcessRuntimeImpl.java, activiti-api-impl/activiti-api-process-runtime-impl/src/main/java/org/conf/activiti/runtime/api/ProcessRuntimeAutoConfiguration.java, activiti-api-impl/activiti-api-process-runtime-impl/src/test/java/org/activiti/runtime/api/impl/ProcessRuntimeImplTest.java, activiti-api-impl/activiti-api-task-runtime-impl/src/main/java/org/activiti/runtime/api/conf/TaskRuntimeAutoConfiguration.java, activiti-api-impl/activiti-api-task-runtime-impl/src/main/java/org/activiti/runtime/api/event/internal/TaskUpdatedListenerDelegate.java, activiti-api-impl/activiti-api-task-runtime-impl/src/main/java/org/activiti/runtime/api/impl/TaskRuntimeImpl.java, activiti-api-impl/activiti-api-task-runtime-impl/src/test/java/org/activiti/runtime/api/impl/TaskRuntimeImplTest.java, activiti-engine/src/main/java/org/activiti/engine/TaskService.java, activiti-engine/src/main/java/org/activiti/engine/impl/TaskServiceImpl.java, activiti-engine/src/main/java/org/activiti/engine/impl/cmd/SaveTaskCmd.java, activiti-engine/src/main/java/org/activiti/engine/impl/cmd/SetProcessInstanceNameCmd.java, activiti-engine/src/main/java/org/activiti/engine/impl/persistence/entity/TaskEntityManagerImpl.java, activiti-spring-conformance-tests/activiti-spring-conformance-set2/src/test/java/org/activiti/spring/conformance/set2/UserTaskCandidateGroupRuntimeTest.java, activiti-spring-conformance-tests/activiti-spring-conformance-set2/src/test/java/org/activiti/spring/conformance/set2/UserTaskCandidateUserRuntimeTest.java
This PR fixes #2252 event dispatching for task and process name update  commands to ensure that events are always generated and dispatched from existing CommandContext inside Activiti transaction, so that they can be aggregated and sent as event messages when Activiti transaction successfully completes.
=> Fix: dispatch task and process updated events from CommandContext

activiti-api-impl/activiti-api-process-runtime-impl/src/main/java/org/activiti/runtime/api/connector/IntegrationContextBuilder.java, activiti-spring-conformance-tests/activiti-spring-conformance-set1/src/test/java/org/activiti/spring/conformance/set1/ConformanceServiceTaskModifyVariableTest.java, activiti-spring-conformance-tests/activiti-spring-conformance-set1/src/test/java/org/activiti/spring/conformance/set1/ConformanceServiceTaskTest.java, activiti-spring-conformance-tests/activiti-spring-conformance-set1/src/test/java/org/activiti/spring/conformance/set1/Set1RuntimeTestConfiguration.java
This PR injects process instance execution context attributes into IntegrationContext holder class at runtime.
=> fix: (IntegrationContext) add process instance execution context attributes

activiti-api-impl/activiti-api-process-runtime-impl/src/main/java/org/activiti/runtime/api/connector/IntegrationContextBuilder.java, activiti-api-impl/activiti-api-process-runtime-impl/src/main/java/org/activiti/runtime/api/model/impl/APIProcessInstanceConverter.java, activiti-api-impl/activiti-api-process-runtime-impl/src/test/java/org/activiti/runtime/api/connector/IntegrationContextBuilderTest.java, activiti-api-impl/activiti-api-process-runtime-impl/src/test/java/org/activiti/runtime/api/model/impl/APIProcessInstanceConverterTest.java, activiti-engine/src/main/java/org/activiti/engine/impl/persistence/entity/ExecutionEntity.java, activiti-engine/src/main/java/org/activiti/engine/impl/persistence/entity/ExecutionEntityImpl.java, activiti-engine/src/main/java/org/activiti/engine/impl/persistence/entity/ExecutionEntityManagerImpl.java, activiti-engine/src/main/java/org/activiti/engine/runtime/Execution.java, activiti-engine/src/main/resources/org/activiti/db/mapping/entity/Execution.xml, activiti-engine/src/test/java/org/activiti/engine/test/api/runtime/ExecutionQueryTest.java, activiti-engine/src/test/java/org/activiti/engine/test/api/runtime/ProcessInstanceQueryTest.java
This PR adds support to expose `parentProcessInstanceId` attribute for Execution entity in the Activiti engine core . The rationale to do so is that internal entity model converters always need to run inside Activiti transaction in order to be able to resolve lazily associated `superExecution` entity to get parent process instance id. Resolving lazy associations this way for each execution record will create additional queries to the engine database from many places, i.e. when resolving execution context for aggregated events, model converters and runtime bundle query api that use model converters that need to run inside Activiti transaction in order to be able resolve `superExecution` entity via additional query.
The parent process instance id attribute seems to be a common property …
=> Resolve Execution entity parentProcessInstanceId attribute via Mybatis query mapping

activiti-api-impl/activiti-api-process-runtime-impl/src/main/java/org/activiti/runtime/api/connector/DefaultServiceTaskBehavior.java, pom.xml
fixes #2363 
this change doesn't brake any of the examples due we are always using connectors as predicates
=> Functional Connector use

activiti-spring-boot-starter/src/main/java/org/activiti/spring/boot/ActivitiProperties.java, activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/HistoryConfigurationTest.java, activiti-spring-boot-starter/src/test/resources/application-history.properties
* To create history table, set the following property.
`spring.activiti.dbHistoryUsed=true
`
* To enable history data, it is necessary to set the following properties.
`spring.activiti.historyLevel=audit`
=> Fix #2228(History tables missing)

activiti-api-impl/activiti-api-task-runtime-impl/src/main/java/org/activiti/runtime/api/event/impl/ToTaskCancelledConverter.java, activiti-api-impl/activiti-api-task-runtime-impl/src/test/java/org/activiti/runtime/api/event/impl/ToTaskCancelledConverterTest.java, activiti-engine/src/main/java/org/activiti/engine/impl/persistence/entity/TaskEntityManagerImpl.java, activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/tasks/TaskRuntimeEventListeners.java, activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/tasks/TaskRuntimeStandaloneTaskTest.java
Map task id to execution id in order to be able to retrieve the related task. Not ideal, but quick workaround.
=> Fix ToTaskCancelledConverter

activiti-spring-boot-starter/src/main/java/org/activiti/spring/boot/ProcessEngineAutoConfiguration.java
This PR just update the AutoConfiguration to use names instead of .class references which blows up when the classes referenced in the @AutoConfigureAfter are not present in the class path.
=> fixing auto configs to use names instead of .class references

activiti-api-impl/activiti-api-process-runtime-impl/src/main/java/org/activiti/runtime/api/connector/ConnectorActionDefinitionFinder.java, activiti-api-impl/activiti-api-process-runtime-impl/src/test/java/org/activiti/runtime/api/connector/ConnectorActionDefinitionFinderTest.java, activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/RuntimeTestConfiguration.java, activiti-spring-boot-starter/src/test/resources/connectors/connector-with-variable-mapping.json, activiti-spring-boot-starter/src/test/resources/connectors/process-image.json, activiti-spring-boot-starter/src/test/resources/connectors/tag-image.json, activiti-spring-boot-starter/src/test/resources/processes/categorize-image-connectors.bpmn20.xml, activiti-spring-boot-starter/src/test/resources/processes/connector-var-mapping.bpmn20.xml
It was previously using `connectorId.ActionId`.
This will have impact on variables mapping coming from process extensions file. Someone that was using `connectorId.ActionId` before should update the following:
1. BPMN xml file: update `implementation=` field inside service task to use `connectorName.actionName`
2. Rename connector bean name to `connectorName.actionName` (if it's a non-cloud connector)
3. Rename connector consumer destination to use `connectorName.actionName` (it it's a cloud connector)
Related to https://github.com/Activiti/Activiti/issues/2589
=> Use connectorName.actionName to match connector implementation

activiti-spring/src/main/java/org/activiti/spring/autodeployment/FailOnNoProcessAutoDeploymentStrategy.java, activiti-spring/src/main/java/org/activiti/spring/autodeployment/NeverFailAutoDeploymentStrategy.java
Related to https://github.com/Activiti/Activiti/issues/2747
=> Name of the resource with a problem will be shown in the log

activiti-engine/src/main/java/org/activiti/engine/impl/asyncexecutor/DefaultAsyncJobExecutor.java, activiti-spring-boot-starter/src/main/java/org/activiti/spring/boot/AsyncExecutorProperties.java, activiti-spring-boot-starter/src/main/java/org/activiti/spring/boot/ProcessEngineAutoConfiguration.java, activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/AsyncExecutorConfigurationTest.java, activiti-spring-boot-starter/src/test/resources/application-async-executor.properties
This PR adds support for configuring async executor via Spring application properties using `spring.activiti.async-executor.*` configuration values
Part of https://github.com/Activiti/Activiti/issues/2636
=> feat: externalize AsyncExecutor configuration properties 

activiti-api-impl/activiti-api-process-runtime-impl/src/main/java/org/activiti/runtime/api/impl/VariablesMappingProvider.java, activiti-api-impl/activiti-api-process-runtime-impl/src/test/java/org/activiti/runtime/api/impl/VariablesMappingProviderTest.java, activiti-api-impl/activiti-api-process-runtime-impl/src/test/resources/task-variable-mapping-extensions.json, activiti-spring-boot-starter/src/test/resources/processes/variable-mapping-extensions.json
In some cases a mapping can reference variables that are not set. In this case the entry of the mapping should be ignored instead of throwing NPE
=> Activiti[3288] - Fix mapping for null variables

activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/process/ProcessExtensionsTest.java, activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/tasks/TaskRuntimeVariableMappingIT.java, activiti-spring-boot-starter/src/test/resources/processes/task-variable-mapping-extensions.json, activiti-spring-process-extensions/src/main/java/org/activiti/spring/process/conf/ProcessExtensionsAutoConfiguration.java, activiti-spring-process-extensions/src/main/java/org/activiti/spring/process/variable/DateFormatterProvider.java, activiti-spring-process-extensions/src/main/java/org/activiti/spring/process/variable/types/DateVariableType.java, activiti-spring-process-extensions/src/test/java/org/activiti/spring/process/variable/DateFormatterProviderTest.java
Related to https://github.com/Activiti/Activiti/issues/2886
DateFormatterProvider is moved to activiti core
Default process variables having date type are supported
=> Move DateFormatterProvider to activiti core

activiti-bpmn-converter/src/main/java/org/activiti/bpmn/converter/BaseBpmnXMLConverter.java, activiti-bpmn-converter/src/test/java/org/activiti/editor/language/xml/MessageEventDefinitionConverterTest.java, activiti-bpmn-converter/src/test/resources/MessageEventDefinitionConverterTest.bpmn
This PR adds tests to assure correct BPMN Xml export/import for message event definitions with `correlationKey` and `messageExpression` attributes for the the following test coverage:
Part of https://github.com/Activiti/Activiti/issues/2637
=> fix: Support BPMN Message Events XML export/import for correlationKey and messageExpression attributes

activiti-engine/src/main/java/org/activiti/engine/delegate/event/impl/ActivitiEventBuilder.java, activiti-engine/src/main/java/org/activiti/engine/impl/bpmn/behavior/IntermediateThrowSignalEventActivityBehavior.java, activiti-engine/src/main/java/org/activiti/engine/impl/cmd/SignalEventReceivedCmd.java, activiti-engine/src/main/java/org/activiti/engine/impl/cmd/TriggerCmd.java, activiti-engine/src/main/java/org/activiti/engine/impl/event/SignalEventHandler.java, activiti-engine/src/main/java/org/activiti/engine/impl/util/ProcessInstanceHelper.java, activiti-spring-conformance-tests/activiti-spring-conformance-signals/src/test/java/org/activiti/spring/conformance/signals/SignalThrowCatchTest.java, activiti-spring-process-extensions/src/main/java/org/activiti/spring/process/ProcessVariablesInitiator.java
This PR fixes the problem with ACTIVITY_SIGNALED start event dispatching before PROCESS_CREATED event without execution context.
=> fix(signal): dispatch ACTIVITY_SIGNALED start event within execution context

activiti-engine/src/main/java/org/activiti/engine/impl/bpmn/behavior/AbstractThrowMessageEventActivityBehavior.java, activiti-engine/src/main/java/org/activiti/engine/impl/bpmn/behavior/BoundaryMessageEventActivityBehavior.java, activiti-engine/src/main/java/org/activiti/engine/impl/bpmn/behavior/IntermediateCatchMessageEventActivityBehavior.java, activiti-engine/src/main/java/org/activiti/engine/impl/bpmn/parser/factory/DefaultMessageExecutionContext.java, activiti-engine/src/main/java/org/activiti/engine/impl/bpmn/parser/factory/MessageExecutionContext.java, activiti-engine/src/test/java/org/activiti/engine/test/bpmn/event/message/MessageThrowCatchEventTest.java
The existing engine intermediate and boundary catch message event behaviors allow to create duplicate message event subscriptions with the same correlation key for different process instances. 
This PR fixes handling of catch message subscription to ensure that duplicate event message subscription with the same correlation key cannot be created by raising `ActivitiIllegalArgumentException` runtime exception during execution.
=> fix(ACTIVITI-3874): handle duplicate event subscriptions for boundary and intermediate message events

activiti-api-impl/activiti-api-process-runtime-impl/src/main/java/org/activiti/runtime/api/impl/RuntimeReceiveMessagePayloadEventListener.java, activiti-engine/src/main/java/org/activiti/engine/impl/bpmn/parser/factory/DefaultMessageExecutionContext.java, activiti-engine/src/test/java/org/activiti/engine/test/bpmn/event/message/MessageIntermediateEventTest.java, activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/process/ProcessRuntimeBPMNMessageIT.java, activiti-spring-boot-starter/src/test/resources/processes/ProcessRuntimeBPMNMessageIT.testBoundaryMessageExpression.bpmn20.xml, activiti-spring-boot-starter/src/test/resources/processes/ProcessRuntimeBPMNMessageIT.testCatchMessageExpression-extensions.json, activiti-spring-boot-starter/src/test/resources/processes/ProcessRuntimeBPMNMessageIT.testCatchMessageExpression.bpmn20.xml
```xml
<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:activiti="http://activiti.org/bpmn" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:omgdc="http://www.omg.org/spec/DD/20100524/DC" xmlns:omgdi="http://www.omg.org/spec/DD/20100524/DI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" id="sample-diagram" targetNamespace="http://bpmn.io/schema/bpmn" exporter="Activiti Modeler" exporterVersion="3.0.0-beta" xsi:schemaLocation="http://www.omg.org/spec/BPMN/20100524/MODEL BPMN20.xsd">
<process id="testCatchMessageExpression" name="intermediate-message-event" isExecutable="true">
<startEvent id="StartEvent_1">
<outgoing>SequenceFlow_1mbim8e</outgoing>
</startEvent> …
```
=> fix(ACTIVITI-3864): handle catch message expression and variable mappings

activiti-bpmn-converter/src/main/java/org/activiti/bpmn/converter/StartEventXMLConverter.java, activiti-bpmn-converter/src/test/java/org/activiti/editor/language/xml/StartEventNonInterruptingEventSubprocessConverterTest.java, activiti-bpmn-converter/src/test/resources/StartEventNonInterruptingEventSubprocessConverterTest.bpmn, activiti-engine/src/main/java/org/activiti/engine/impl/agenda/EndExecutionOperation.java, activiti-engine/src/test/java/org/activiti/engine/test/bpmn/event/message/MessageEventSubprocessTest.java, activiti-engine/src/test/resources/org/activiti/engine/test/bpmn/event/message/MessageEventSubprocessTest.testNonInterruptingUnderProcessDefinition.bpmn20.xml
This PR fixes runtime error when running tasks in the process with interrupting and non-interrupting Start Message Event is triggered inside an Event Subprocess. The existing `StartEventXMLConverter` is using non-standard `activiti:isInterrupting` attribute to specify start message event behavior in event subprocess:
https://github.com/Activiti/Activiti/blob/d5282ebbddff656e7448012570f4904746000275/activiti-bpmn-converter/src/main/java/org/activiti/bpmn/converter/StartEventXMLConverter.java#L52
The updated `StartEventXMLConverter` implementation removes parsing non-standard `activiti:isInterrupting` attribute and uses the standard `isInterrupting` attribute in order to adhere to BPMN specification  (page 244, table 10.87): 
```
isInterrupting: boolean = true | This attribute only applies …
```
=> fix(ACTIVITI-3875): added support for interrupting and non-interrupting start message event for event subprocess 

activiti-spring-boot-starter/src/main/java/org/activiti/spring/boot/ActivitiMethodSecurityAutoConfiguration.java
This PR fixes https://github.com/Activiti/Activiti/issues/2845 to apply `@ConditionalOnMissingBean` with `@EnableGlobalMethodSecurity` annotation to avoid triggering `ActivitiMethodSecurityAutoConfiguration` if there is already application specific `GlobalMethodSecurityConfiguration`present in the context.
=> fix(config): added conditional on missing `@EnableGlobalMethodSecurity` bean

activiti-spring-boot-starter/src/main/java/org/activiti/spring/boot/ProcessEngineAutoConfiguration.java, activiti-spring-process-extensions/src/main/java/org/activiti/spring/process/conf/ProcessExtensionsAutoConfiguration.java, activiti-spring-process-extensions/src/test/java/org/activiti/spring/process/conf/ProcessExtensionResourceFinderDescriptorAutoConfiguration.java
Due to a misconfiguration of resource loader pattern, examples are not able to load extensions files
Fix it by changing `classpath:` to `classpath*:`
=> AAE-764: Extensions files are  not loaded in examples

activiti-api-impl/activiti-api-process-runtime-impl/src/main/java/org/activiti/runtime/api/event/impl/ProcessCompletedImpl.java, activiti-api-impl/activiti-api-task-runtime-impl/src/main/java/org/activiti/runtime/api/event/impl/ToTaskCancelledConverter.java, activiti-api-impl/activiti-api-task-runtime-impl/src/test/java/org/activiti/runtime/api/event/impl/ToTaskCancelledConverterTest.java, activiti-engine/src/main/java/org/activiti/engine/delegate/event/impl/ActivitiEventBuilder.java, activiti-engine/src/main/java/org/activiti/engine/impl/bpmn/behavior/ParallelMultiInstanceBehavior.java, activiti-spring-boot-starter/pom.xml, activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/tasks/TaskBaseRuntime.java, activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/tasks/TaskRuntimeMultiInstanceIT.java, activiti-spring-boot-starter/src/test/resources/processes/MultiInstanceParallelUserTasksCompletionCondition.bpmn20.xml
**Component:-** 
Multi-Instance
Runtime Bundle is not sending the event once completion condition expression passed
**Current Behaviour:-**
When this expression evaluates to true, Still tasks are available in the pending list.
**Expected Behaviour:-**
When this expression evaluates to true, all remaining instances are destroyed and the multi-instance activity ends, continuing the process. 
fixes https://github.com/Activiti/Activiti/issues/2969
=> [AAE-683] [Activiti] Tasks are not destroyed once completion condition expression passed

activiti-spring-boot-starter/src/main/java/org/activiti/spring/AbstractActivitiSmartLifeCycle.java, activiti-spring-boot-starter/src/main/java/org/activiti/spring/ProcessDeployedEventProducer.java, activiti-spring-boot-starter/src/main/java/org/activiti/spring/StartMessageDeployedEventProducer.java, activiti-spring-boot-starter/src/test/java/org/activiti/spring/ProcessDeployedEventProducerTest.java
This PR fixes problem when the process deployed  and start message events are dispatched twice using Spring ApplicationReady event
Part of https://github.com/Activiti/Activiti/issues/1691
=> fix(AAE-201):  Fixed the problem when process deployed  and start message events are dispatched twice

activiti-engine/src/test/resources/META-INF/persistence.xml, activiti-engine/src/test/resources/activiti.cfg.xml, activiti-engine/src/test/resources/org/activiti/engine/test/bpmn/event/message/MessageThrowCatchEventTest.activiti.cfg.xml, activiti-engine/src/test/resources/org/activiti/engine/test/bpmn/event/message/MessageThrowEventTest.activiti.cfg.xml, activiti-engine/src/test/resources/org/activiti/standalone/cfg/identity/customIdentitySession-activiti.cfg.xml, activiti-engine/src/test/resources/org/activiti/standalone/cfg/variable/custom-serialize-variables-activiti.cfg.xml, activiti-engine/src/test/resources/org/activiti/standalone/idgenerator/uuidgenerator.test.activiti.cfg.xml, activiti-spring/src/test/resources/org/activiti/spring/test/components/SpringjobExecutorTest-context.xml
This flag is no longer supported in the latest version of h2:
- https://github.com/h2database/h2database/releases/tag/version-1.4.198
- https://github.com/h2database/h2database/releases/tag/version-1.4.200
This should fix https://github.com/Activiti/Activiti/pull/2990
Ref https://github.com/Activiti/Activiti/issues/2991
=> Remove MVCC flag from test db

activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/agenda/ContinueProcessOperation.java, activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/agenda/DestroyScopeOperation.java, activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/agenda/EndExecutionOperation.java, activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/agenda/TakeOutgoingSequenceFlowsOperation.java, activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/bpmn/behavior/BoundaryCancelEventActivityBehavior.java, activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/bpmn/behavior/BoundaryEventActivityBehavior.java, activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/bpmn/behavior/CancelEndEventActivityBehavior.java, activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/bpmn/behavior/EventSubProcessMessageStartEventActivityBehavior.java, activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/bpmn/behavior/InclusiveGatewayActivityBehavior.java, activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/bpmn/behavior/IntermediateCatchEventActivityBehavior.java, activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/bpmn/behavior/IntermediateCatchMessageEventActivityBehavior.java, activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/bpmn/behavior/IntermediateCatchSignalEventActivityBehavior.java, activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/bpmn/behavior/IntermediateCatchTimerEventActivityBehavior.java, activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/bpmn/behavior/ParallelGatewayActivityBehavior.java, activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/bpmn/behavior/ParallelMultiInstanceBehavior.java, activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/bpmn/behavior/SequentialMultiInstanceBehavior.java, activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/bpmn/behavior/TerminateEndEventActivityBehavior.java, activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/bpmn/helper/ErrorPropagation.java, activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/cmd/CompleteAdhocSubProcessCmd.java, activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/persistence/entity/ExecutionEntityManager.java, activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/persistence/entity/ExecutionEntityManagerImpl.java
Refactor the method ExecutionEntityManager.deleteExecutionAndRelatedData in order to remove the boolean parameter in favor of two separated methods (deleteExecutionAndRelatedData, cancelExecution).
This kind of parameters is considered as a bad practice (https://martinfowler.com/bliki/FlagArgument.html).
```
void deleteExecutionAndRelatedData(ExecutionEntity executionEntity, String deleteReason, boolean cancel);
```
fixes -> https://issues.alfresco.com/jira/browse/AAE-916
=> [AAE-916] Remove boolean parameter from ExecutionEntityManager.deleteExecutionAndRelatedData

.updatebot.yml, pom.xml
This PR fixes broken Updatebot propagation dependencies to `activiti-cloud-runtime-bundle-service`, `ctiviti-cloud-query-service`, and `activiti-cloud-modeling-service` repositories.
=> fix(Updatebot): Revert removed propagation to cloud repositories

Jenkinsfile
This PR removes redundant `updatebot update --merge` step from Jenkinsfile.
=> fix(Jenkinsfile): Removed "updatebot update --merge" step

activiti-core/activiti-bpmn-converter/src/main/java/org/activiti/bpmn/converter/child/multi/instance/MultiInstanceOutputDataItemParser.java, activiti-core/activiti-bpmn-converter/src/test/java/org/activiti/bpmn/converter/child/MultiInstanceParserTest.java, activiti-core/activiti-bpmn-converter/src/test/resources/multi-instance-loop-characteristics-output-data-item-as-value.xml
Keep as defined in the specification, the name should be provided inside `name` attribute only.,
This reverts commit ffd15829c3a46156eeebbb32cacb17e75ee7c29c.
=> Revert "Read OutputDataItem as elementText"

.updatebot.yml, Makefile, activiti-api/pom.xml, activiti-core-common/activiti-core-common-dependencies/pom.xml, activiti-core-common/pom.xml, activiti-core/activiti-core-dependencies/pom.xml, activiti-core/pom.xml
This PR reverts changes for activiti-build parent and activiti-core-dependencies propagation
Part of https://github.com/Activiti/Activiti/issues/3099
=> fix: Revert changes for activiti-build parent and activiti-core-dependencies propagation

activiti-core/activiti-engine/src/test/java/org/activiti/standalone/validation/DefaultProcessValidatorTest.java, activiti-core/activiti-engine/src/test/java/org/activiti/standalone/validation/MessageFlowValidationTest.java, activiti-core/activiti-engine/src/test/resources/org/activiti/engine/test/validation/flowWithoutConditionNoDefaultFlow.bpmn20.xml, activiti-core/activiti-engine/src/test/resources/org/activiti/engine/test/validation/invalidMessageProcess.bpmn20.xml, activiti-core/activiti-engine/src/test/resources/org/activiti/engine/test/validation/validMessageProcess.bpmn20.xml, activiti-core/activiti-process-validation/src/main/java/org/activiti/validation/validator/impl/DiagramInterchangeInfoValidator.java
https://github.com/Activiti/Activiti/issues/3119
All the time we validate a process that contains a Collaboration that shows the Message Flows. We receive a warning message from the Validator:
[main|org.activiti.engine.impl.bpmn.parser.BpmnParse] WARN  Invalid reference in diagram interchange definition: could not find messageflow2
In Collaboration Diagrams, a Message Flow can be extended to show the message that is passed from one Participant to another.
Message Flow is defined it is contained either within a Collaboration. We need to let the validator search for a bpmnReference of the bpmnElement also inside the MessageFlow elements
=> [AAE-1614] fix warning for message flow reference

activiti-core/activiti-api-impl/activiti-api-process-runtime-impl/src/main/java/org/activiti/runtime/api/conf/ConnectorsAutoConfiguration.java, activiti-core/activiti-api-impl/activiti-api-process-runtime-impl/src/main/java/org/activiti/runtime/api/impl/ExpressionEvaluator.java, activiti-core/activiti-api-impl/activiti-api-process-runtime-impl/src/main/java/org/activiti/runtime/api/impl/ExpressionResolver.java, activiti-core/activiti-api-impl/activiti-api-process-runtime-impl/src/main/java/org/activiti/runtime/api/impl/SimpleMapExpressionEvaluator.java, activiti-core/activiti-api-impl/activiti-api-process-runtime-impl/src/main/java/org/activiti/runtime/api/impl/VariableScopeExpressionEvaluator.java, activiti-core/activiti-api-impl/activiti-api-process-runtime-impl/src/main/java/org/activiti/runtime/api/impl/VariablesMappingProvider.java, activiti-core/activiti-api-impl/activiti-api-process-runtime-impl/src/test/java/org/activiti/runtime/api/impl/ExpressionResolverHelper.java, activiti-core/activiti-api-impl/activiti-api-process-runtime-impl/src/test/java/org/activiti/runtime/api/impl/ExpressionResolverTest.java, activiti-core/activiti-api-impl/activiti-api-process-runtime-impl/src/test/java/org/activiti/runtime/api/impl/ProcessVariablesPayloadValidatorTest.java, activiti-core/activiti-api-impl/activiti-api-process-runtime-impl/src/test/java/org/activiti/runtime/api/impl/SimpleMapExpressionEvaluatorTest.java, activiti-core/activiti-api-impl/activiti-api-process-runtime-impl/src/test/java/org/activiti/runtime/api/impl/VariableScopeExpressionEvaluatorTest.java, activiti-core/activiti-engine/src/main/java/org/activiti/engine/delegate/Expression.java, activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/el/FixedValue.java, activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/el/JuelExpression.java
Allow evaluating expressions even when internal Context is not set. This is useful in the case of cloud connectors.
=> AAE-1665 Inject ExpressionManager during expressions evaluation

.updatebot.yml
fix updatebot configuration to propagate to new activiti cloud monorepo
=> fix updatebot configuration to propagate to new activiti cloud monorepo

activiti-core/activiti-spring-conformance-tests/pom.xml, activiti-examples/pom.xml, pom.xml
Sources artifacts are configured to be generated at deploy phase, so jar should be signed only after that.
This is also skipping the deployment for examples and conformance tests that are not required to be deployed
Ref https://github.com/Activiti/Activiti/issues/3184
=> Move jar signature to deploy phase

pom.xml
Changing the default phases is causing issues while signing artifacts (sources jars and some pom files are not signed)
Ref https://github.com/Activiti/Activiti/issues/3184
=> Restore default phases for attach sources and sign jars (#3184)

pom.xml
When no phase is specified some of the artifacts are signed too late
Ref https://github.com/Activiti/Activiti/issues/3184
=> Explicitly sign artifacts in verify phase

Jenkinsfile, activiti-api/activiti-api-process-model/src/main/java/org/activiti/api/process/model/BPMNActivity.java, activiti-api/activiti-api-process-model/src/main/java/org/activiti/api/process/model/IntegrationContext.java, activiti-api/activiti-api-process-model/src/main/java/org/activiti/api/process/model/events/IntegrationEvent.java, activiti-core/activiti-api-impl/activiti-api-process-model-impl/src/main/java/org/activiti/api/runtime/model/impl/BPMNActivityImpl.java, activiti-core/activiti-api-impl/activiti-api-process-model-impl/src/main/java/org/activiti/api/runtime/model/impl/IntegrationContextImpl.java, activiti-core/activiti-api-impl/activiti-api-process-runtime-impl/src/main/java/org/activiti/runtime/api/connector/IntegrationContextBuilder.java, activiti-core/activiti-api-impl/activiti-api-process-runtime-impl/src/main/java/org/activiti/runtime/api/event/impl/BPMNErrorConverter.java, activiti-core/activiti-api-impl/activiti-api-process-runtime-impl/src/main/java/org/activiti/runtime/api/model/impl/ToActivityConverter.java
This PR adds support for INTEGRATION_ERROR_RECEIVED event type for IntegrationEvent interface and implementation.
It also adds support for exposing executionId attribute for BPMNActivity and ExecutionContext process runtime entity models apis. 
Fixes AAE-1291
Part of https://github.com/Activiti/Activiti/issues/2712
=> feat(AAE-1291): Added support for Integration error event type in Activiti Core Api

activiti-core/activiti-api-impl/activiti-api-process-model-impl/src/main/java/org/activiti/api/runtime/model/impl/ProcessVariablesMapDeserializer.java, activiti-core/activiti-api-impl/activiti-api-process-model-impl/src/main/java/org/activiti/api/runtime/model/impl/ProcessVariablesMapSerializer.java, activiti-core/activiti-api-impl/activiti-api-process-model-impl/src/main/java/org/activiti/api/runtime/model/impl/ProcessVariablesMapTypeRegistry.java, activiti-core/activiti-api-impl/activiti-api-process-model-impl/src/test/java/org/activiti/api/runtime/test/model/impl/IntegrationContextImplTest.java
This PR fixes variable type names for IntegrationContext variables passed between Rb and Connectors to use simple names instead of full Java class name for data types in the raw json to match types in the ProcessVariables entity stored inside Query and Audit databases, i.e.
The current format contains full Java class name:
```
"outBoundVariables": {
"processDefinitionId": {
"type": "java.lang.String",
"value": "HeadersConnectorProcess:1:dc32c0bc-9a56-11ea-afc3-92581787ab92"
},
"processDefinitionVersion": {
"type": "java.lang.Integer",
"value": "1"
},
"processDefinitionKey": {
"type": "java.lang.String",
"value": "HeadersConnectorProcess"
}
"amount": {
"type": "java.lang.BigDecimal",
"value": "10.00"
}
}
```
The updated format, will contain simple type names:
```
"outBoundVariables": { …
```
=> fix: add support for simple process variable types in IntegrationContext
