- modules/activiti-engine/src/main/java/org/activiti/engine/impl/bpmn/behavior/ExclusiveGatewayActivityBehavior.java
- modules/activiti-engine/src/main/java/org/activiti/engine/impl/bpmn/behavior/InclusiveGatewayActivityBehavior.java
- modules/activiti-engine/src/test/java/org/activiti/engine/test/bpmn/gateway/ExclusiveGatewayTest.java
- modules/activiti-engine/src/test/java/org/activiti/engine/test/bpmn/gateway/InclusiveGatewayTest.java
- modules/activiti-engine/src/test/resources/org/activiti/engine/test/bpmn/gateway/ExclusiveGatewayTest.testSkipExpression.bpmn20.xml
- modules/activiti-engine/src/test/resources/org/activiti/engine/test/bpmn/gateway/InclusiveGatewayTest.testSkipExpression.bpmn20.xml
Update InclusiveGatewayActivityBehavior.java and ExclusiveGatewayActivityBehavior.java to provide skipExpression support for outgoing sequence flows from a gateway.
> Add skipExpression support to inclusive and exclusive gateways.

- modules/activiti-rest/src/main/java/org/activiti/rest/service/api/history/HistoricTaskInstanceBaseResource.java
- modules/activiti-rest/src/main/java/org/activiti/rest/service/api/history/HistoricTaskInstanceCollectionResource.java
- modules/activiti-rest/src/main/java/org/activiti/rest/service/api/history/HistoricTaskInstanceQueryRequest.java
Ran test cases and did a simple integration test.
> Get historic task candidate group

- modules/activiti-engine/src/main/java/org/activiti/engine/delegate/DelegateExecution.java
- modules/activiti-engine/src/main/java/org/activiti/engine/impl/pvm/runtime/ExecutionImpl.java
> Map super execution id to DelegateExecution

- modules/activiti-engine/src/main/java/org/activiti/engine/impl/HistoricTaskInstanceQueryImpl.java
- modules/activiti-engine/src/main/java/org/activiti/engine/impl/TaskQueryImpl.java
- modules/activiti-engine/src/main/java/org/activiti/engine/task/TaskInfoQuery.java
- modules/activiti-engine/src/main/resources/org/activiti/db/mapping/entity/HistoricTaskInstance.xml
- modules/activiti-engine/src/main/resources/org/activiti/db/mapping/entity/Task.xml
- modules/activiti-engine/src/test/java/org/activiti/engine/test/api/task/TaskQueryTest.java
See https://jira.codehaus.org/browse/ACT-2196.
> Added a method (processInstanceIdIn) in TaskInfoQuery

- modules/activiti-engine/src/main/java/org/activiti/engine/impl/juel/TypeConverterImpl.java
- modules/activiti-engine/src/test/java/org/activiti/engine/test/bpmn/event/timer/IntermediateTimerEventTest.java
- modules/activiti-engine/src/test/resources/org/activiti/engine/test/bpmn/event/timer/IntermediateTimerEventTest.testTimerEventWithStartAndDuration.bpmn20.xml
Pull request for ACT-2179. Updated the TypeConverterImpl so that a Date coerced into String will be in ISO8601 format.
> ACT-2179 Date coerced to String should be in ISO8601 format

- modules/activiti-explorer/src/main/java/org/activiti/explorer/Constants.java
- modules/activiti-explorer/src/main/java/org/activiti/explorer/filter/ExplorerFilter.java
- modules/activiti-explorer/src/main/java/org/activiti/explorer/ui/login/DefaultLoginHandler.java
Fixes ACT-1970
Discussed here
http://forums.activiti.org/content/securing-activiti-modeler
> Only authenticated users can access /service

- modules/activiti-engine/src/main/java/org/activiti/engine/history/HistoricProcessInstanceQuery.java
- modules/activiti-engine/src/main/java/org/activiti/engine/impl/HistoricProcessInstanceQueryImpl.java
- modules/activiti-engine/src/main/resources/org/activiti/db/mapping/entity/HistoricProcessInstance.xml
- modules/activiti-engine/src/test/java/org/activiti/engine/test/history/HistoricProcessInstanceTest.java
See https://jira.codehaus.org/browse/ACT-2205.
> Added a method (processDefinitionKeyIn) in HistoricProcessInstanceQuery

- modules/activiti-engine/src/main/java/org/activiti/engine/impl/AbstractQuery.java
- modules/activiti-engine/src/test/java/org/activiti/standalone/cfg/AttachmentQuery.java
- modules/activiti-engine/src/test/java/org/activiti/standalone/cfg/AttachmentQueryProperty.java
- modules/activiti-engine/src/test/java/org/activiti/standalone/cfg/CustomMybatisXMLMapperTest.java
- modules/activiti-engine/src/test/java/org/activiti/standalone/cfg/CustomTask.java
- modules/activiti-engine/src/test/java/org/activiti/standalone/cfg/CustomTaskQuery.java
- modules/activiti-engine/src/test/resources/org/activiti/standalone/cfg/custom-mappers/AttachmentMapper.xml
- modules/activiti-engine/src/test/resources/org/activiti/standalone/cfg/custom-mappers/CustomTaskMapper.xml
- modules/activiti-engine/src/test/resources/org/activiti/standalone/cfg/custom-mybatis-xml-mappers-activiti.cfg.xml
- userguide/src/en/ch17-Advanced.adoc
added another example and test case for using custom XML mapped statements + re-factored old example and test case
added a constructor to AbsractQuery(ManagementService managementService) that custom queries that extended it can use
added information on using custom XML mapped statements in user guide
> using custom XML mapped statements

- modules/activiti-jmx/src/main/java/org/activiti/management/jmx/DefaultManagementMBeanAssembler.java
- modules/activiti-jmx/src/main/java/org/activiti/management/jmx/MBeanInfoAssembler.java
- modules/activiti-jmx/src/main/java/org/activiti/management/jmx/mbeans/JobExecutorMBean.java
Fix two typos in Loggers and one description in JMX module
> fixed logging and description typos in JMX module

- modules/activiti-explorer/src/main/java/org/activiti/editor/ui/ConvertProcessDefinitionPopupWindow.java
According to my issue:
http://jira.codehaus.org/browse/ACT-2219
I have found the way to fix it. Hope it helps.
> Fix the redirected URL when converting deploy process to editable model

- modules/activiti-rest/src/main/java/org/activiti/rest/service/api/RestUrls.java
- modules/activiti-rest/src/main/java/org/activiti/rest/service/api/identity/UserPictureResource.java
- modules/activiti-rest/src/main/java/org/activiti/rest/service/api/repository/ProcessDefinitionImageResource.java
- modules/activiti-rest/src/main/java/org/activiti/rest/service/api/runtime/process/ProcessInstanceDiagramResource.java
- modules/activiti-rest/src/main/java/org/activiti/rest/service/api/runtime/task/TaskAttachmentContentResource.java
- modules/activiti-rest/src/test/java/org/activiti/rest/service/api/identity/UserPictureResourceTest.java
- modules/activiti-rest/src/test/java/org/activiti/rest/service/api/repository/ProcessDefinitionImageResourceTest.java
- modules/activiti-rest/src/test/java/org/activiti/rest/service/api/runtime/ProcessInstanceDiagramResourceTest.java
Fixes wrong response content type especially when used in browser (or when Accept header exists in request)
Discussed here
http://forums.activiti.org/content/wrong-content-type-rest-api
> REST content type

- modules/activiti-engine/src/main/java/org/activiti/engine/impl/bpmn/behavior/TerminateEndEventActivityBehavior.java
- modules/activiti-engine/src/main/java/org/activiti/engine/impl/pvm/delegate/ActivityExecution.java
- modules/activiti-engine/src/main/java/org/activiti/engine/impl/pvm/runtime/ExecutionImpl.java
- modules/activiti-engine/src/test/java/org/activiti/engine/test/api/event/ProcessInstanceEventsTest.java
- modules/activiti-engine/src/test/resources/org/activiti/engine/test/bpmn/event/end/TerminateEndEventTest.testTerminateInParentProcess.bpmn
Adding additional events to activiti.
> TerminateEndEvent - extending activiti events. 

- modules/activiti-cxf/src/main/java/org/activiti/engine/impl/webservice/CxfWSDLImporter.java
- modules/activiti-cxf/src/test/java/org/activiti/engine/impl/webservice/WSDLImporterTest.java
- modules/activiti-cxf/src/test/resources/org/activiti/engine/impl/webservice/inherited-elements-in-types.wsdl
see https://activiti.atlassian.net/browse/ACT-4001
> ACT-4001: CxfWsdlImporter does not import correctly inherited types

- modules/activiti-bpmn-converter/src/main/java/org/activiti/bpmn/constants/BpmnXMLConstants.java
- modules/activiti-bpmn-converter/src/main/java/org/activiti/bpmn/converter/BpmnXMLConverter.java
- modules/activiti-bpmn-converter/src/main/java/org/activiti/bpmn/converter/UserTaskXMLConverter.java
- modules/activiti-bpmn-converter/src/main/java/org/activiti/bpmn/converter/parser/ResourceParser.java
- modules/activiti-bpmn-model/src/main/java/org/activiti/bpmn/model/BpmnModel.java
- modules/activiti-bpmn-model/src/main/java/org/activiti/bpmn/model/Resource.java
- modules/activiti-engine/src/test/java/org/activiti/engine/test/bpmn/usertask/TaskAssignmentCandidateTest.java
- modules/activiti-engine/src/test/resources/org/activiti/engine/test/bpmn/usertask/TaskAssignmentCandidateTest.testCandidateGroups.bpmn20.xml
This adds a BPMN feature not previously supported in Activiti, see test case for example.
> Added support for assignment to groups defined using resourceRef 

- userguide/src/en/ch07b-BPMN-Constructs.adoc
Add documentation for var.return to userguide
> Update guide return var

- modules/activiti-engine/src/main/java/org/activiti/engine/impl/cfg/ProcessEngineConfigurationImpl.java
- modules/activiti-engine/src/main/java/org/activiti/engine/impl/event/logger/EventLogger.java
- modules/activiti-engine/src/main/java/org/activiti/engine/impl/jobexecutor/TimerDeclarationImpl.java
- modules/activiti-engine/src/main/java/org/activiti/engine/impl/util/TimerUtil.java
- modules/activiti-engine/src/main/java/org/activiti/engine/impl/util/condition/ConditionUtil.java
- modules/activiti-engine/src/main/java/org/activiti/engine/impl/variable/JPAEntityMappings.java
Findbugs found occurrences where a null check was repeated within a few lines of each other
or the value was known to be non-null.
After making the changes I successfully ran a mvn clean test.
> Remove redundant null checks.

- modules/activiti-engine/src/main/java/org/activiti/engine/impl/bpmn/diagram/ProcessDiagramGenerator.java
This pull request changes the flow label positioning on the diagram.
The issue was originally found in the Alfresco project.
Please, refer to https://issues.alfresco.com/jira/browse/MNT-13139.
> Changed label positioning.

- modules/activiti-engine/src/main/java/org/activiti/engine/impl/bpmn/behavior/TerminateEndEventActivityBehavior.java
- modules/activiti-engine/src/main/java/org/activiti/engine/impl/bpmn/parser/factory/DefaultActivityBehaviorFactory.java
- modules/activiti-engine/src/test/java/org/activiti/engine/test/bpmn/event/end/TerminateEndEventTest.java
- modules/activiti-engine/src/test/resources/org/activiti/engine/test/bpmn/event/end/TerminateEndEventTest.parseExtensionElements.bpmn20.xml
added possibility to have EndEvent definition in TerminateEndEvent
> TerminateEndEvent extension elements

- modules/activiti-engine/src/main/java/org/activiti/engine/impl/persistence/entity/ByteArrayRef.java
- modules/activiti-engine/src/main/java/org/activiti/engine/impl/persistence/entity/UserEntity.java
- modules/activiti-engine/src/main/java/org/activiti/engine/impl/persistence/entity/UserEntityTest.java
- modules/activiti-engine/src/test/java/org/activiti/engine/test/api/identity/IdentityServiceTest.java
Fixes https://github.com/Activiti/Activiti/issues/497
> Fixing java.lang.NullPointerException when attempting to delete user picture

- modules/activiti-modeler/src/main/java/org/activiti/rest/editor/main/StencilsetRestResource.java
Fix read stencilset.json gibberish when in other languages. (UTF-8)
> Fix read stencilset.json gibberish when in other languages

- modules/activiti-engine/src/main/java/org/activiti/engine/delegate/event/ActivitiEventType.java
- modules/activiti-engine/src/main/java/org/activiti/engine/delegate/event/ActivitiProcessStartedEvent.java
- modules/activiti-engine/src/main/java/org/activiti/engine/delegate/event/impl/ActivitiEventBuilder.java
- modules/activiti-engine/src/main/java/org/activiti/engine/delegate/event/impl/ActivitiProcessStartedEventImpl.java
- modules/activiti-engine/src/main/java/org/activiti/engine/impl/pvm/runtime/AtomicOperationProcessStart.java
- modules/activiti-engine/src/test/java/org/activiti/engine/test/api/event/ProcessInstanceEventsTest.java
see https://activiti.atlassian.net/browse/ACT-3994
> ACT-3994: Add support of event PROCESS_STARTED fired on process instance startup

- modules/activiti-engine/src/main/java/org/activiti/engine/impl/bpmn/helper/ErrorPropagation.java
- modules/activiti-engine/src/test/java/org/activiti/engine/test/api/event/ProcessInstanceEventsTest.java
PROCESS_COMPLETED event is not generated for errorEndEvent
> PROCESS_COMPLETED event for errorEndEvent

- modules/activiti-engine/src/main/java/org/activiti/engine/impl/bpmn/diagram/ProcessDiagramGenerator.java
Reverts Activiti/Activiti#608
This pull request did not take into account other options of label positioning.
> Revert "Changed label positioning."

- modules/activiti-engine/src/main/java/org/activiti/engine/delegate/event/impl/ActivitiEventBuilder.java
- modules/activiti-engine/src/main/java/org/activiti/engine/impl/calendar/DueDateBusinessCalendar.java
- modules/activiti-engine/src/main/java/org/activiti/engine/impl/history/HistoryManager.java
- modules/activiti-engine/src/main/java/org/activiti/engine/impl/persistence/entity/JobEntity.java
- modules/activiti-engine/src/test/java/org/activiti/engine/test/bpmn/event/end/TerminateEndEventTest.java
- modules/activiti-engine/src/test/java/org/activiti/engine/test/db/MetaDataTest.java
Remove unused imports in engine project; the remaining changes are only spaces.
> Remove unused imports in engine project

- modules/activiti-bpmn-converter/src/main/java/org/activiti/bpmn/converter/child/BaseChildElementParser.java
- modules/activiti-engine/src/main/java/org/activiti/engine/impl/agenda/ExecuteInactiveBehaviorsOperation.java
- modules/activiti-engine/src/main/java/org/activiti/engine/impl/interceptor/CommandContext.java
Remote duplicate semi-colons; the other changes are just space differences.
> Remove duplicate semi-colon

- modules/activiti-engine/src/main/java/org/activiti/engine/impl/bpmn/behavior/MailActivityBehavior.java
Fix also required on 5.x branch
> Fix multitenant mail server configuration

- modules/activiti-engine/src/main/java/org/activiti/engine/impl/db/DbSqlSessionFactory.java
For Jira: https://activiti.atlassian.net/browse/ACT-4079
> Fix the NPE in isBulkInsertable() by changing .get() to .containsKey()

- modules/activiti-engine/src/main/java/org/activiti/engine/impl/DeploymentQueryImpl.java
- modules/activiti-engine/src/main/java/org/activiti/engine/impl/ProcessDefinitionQueryImpl.java
To read some properties that weren't accessible.
> Added accessor methods to ProcessDefinitionQueryImpl and DeploymentQueryImpl.

- modules/activiti-json-converter/src/main/java/org/activiti/editor/constants/StencilConstants.java
- modules/activiti-json-converter/src/main/java/org/activiti/editor/language/json/converter/SequenceFlowJsonConverter.java
> Dev vasile 686 - default flow must be preserved after export/import process 

- modules/activiti-engine/src/main/java/org/activiti/engine/impl/variable/JsonType.java
- modules/activiti-engine/src/test/java/org/activiti/engine/test/json/JsonTest.java
Fixes github issue 668 (https://github.com/Activiti/Activiti/issues/668)
> #668 - Fix 'Impossible to remove variable with 'json' type'

- tooling/archetypes/activiti-archetype-unittest/pom.xml
- userguide/src/en/ch19-tooling.adoc
- userguide/src/en/index.adoc
Documentation for create test case maven archetype and some minor change in namings
> Test case archetype document

- pom.xml
update master pom file to deploy maven archetype to the standard repository
> update master file to deploy maven archetype to standard repository

- modules/activiti-engine/src/main/java/org/activiti/engine/history/HistoricProcessInstanceQuery.java
- modules/activiti-engine/src/main/java/org/activiti/engine/impl/AbstractVariableQueryImpl.java
- modules/activiti-engine/src/main/java/org/activiti/engine/impl/HistoricProcessInstanceQueryImpl.java
- modules/activiti-engine/src/main/java/org/activiti/engine/impl/QueryOperator.java
- modules/activiti-engine/src/main/resources/org/activiti/db/mapping/entity/HistoricProcessInstance.xml
- modules/activiti-rest/src/main/java/org/activiti/rest/service/api/engine/variable/QueryVariable.java
- modules/activiti-rest/src/main/java/org/activiti/rest/service/api/history/HistoricProcessInstanceBaseResource.java
- modules/activiti-rest/src/test/java/org/activiti/rest/service/api/history/HistoricProcessInstanceQueryResourceTest.java
> Dev abalmus 14631 - REST Processes and Tasks API for parameters/variables allowed MATCHES operator, operator is not case-insensitive

- modules/activiti-bpmn-converter/src/test/java/org/activiti/editor/language/xml/FormPropertiesConverterTest.java
- modules/activiti-bpmn-converter/src/test/resources/formPropertiesProcess.bpmn
- modules/activiti-json-converter/src/test/java/org/activiti/editor/language/FormPropertiesConverterTest.java
- modules/activiti-json-converter/src/test/resources/test.formpropertiesmodel.json
> Dev vasile 701 (V5) - improve form properties converter test

- .gitignore
- modules/activiti-engine/src/main/java/org/activiti/engine/history/HistoricProcessInstance.java
- modules/activiti-engine/src/main/java/org/activiti/engine/history/HistoricProcessInstanceQuery.java
- modules/activiti-engine/src/main/java/org/activiti/engine/impl/ExecutionQueryImpl.java
- modules/activiti-engine/src/main/java/org/activiti/engine/impl/HistoricProcessInstanceQueryImpl.java
- modules/activiti-engine/src/main/java/org/activiti/engine/impl/HistoricTaskInstanceQueryImpl.java
- modules/activiti-engine/src/main/java/org/activiti/engine/impl/ProcessInstanceQueryImpl.java
- modules/activiti-engine/src/main/java/org/activiti/engine/impl/TaskQueryImpl.java
- modules/activiti-engine/src/main/java/org/activiti/engine/impl/bpmn/deployer/BpmnDeployer.java
- modules/activiti-engine/src/main/java/org/activiti/engine/impl/context/Context.java
- modules/activiti-engine/src/main/java/org/activiti/engine/impl/persistence/entity/ExecutionEntity.java
- modules/activiti-engine/src/main/java/org/activiti/engine/impl/persistence/entity/ExecutionEntityImpl.java
- modules/activiti-engine/src/main/java/org/activiti/engine/impl/persistence/entity/HistoricProcessInstanceEntity.java
- modules/activiti-engine/src/main/java/org/activiti/engine/impl/persistence/entity/HistoricProcessInstanceEntityImpl.java
- modules/activiti-engine/src/main/java/org/activiti/engine/runtime/Execution.java
- modules/activiti-engine/src/main/java/org/activiti/engine/runtime/ExecutionQuery.java
- modules/activiti-engine/src/main/java/org/activiti/engine/runtime/ProcessInstance.java
- modules/activiti-engine/src/main/java/org/activiti/engine/runtime/ProcessInstanceQuery.java
- modules/activiti-engine/src/main/java/org/activiti/engine/task/TaskInfoQuery.java
- modules/activiti-engine/src/test/java/org/activiti/engine/test/api/history/HistoricProcessInstanceQueryTest.java
- modules/activiti-engine/src/test/java/org/activiti/engine/test/api/runtime/ExecutionQueryTest.java
- modules/activiti-engine/src/test/java/org/activiti/engine/test/api/runtime/ProcessInstanceQueryTest.java
- modules/activiti-engine/src/test/java/org/activiti/engine/test/api/runtime/RuntimeServiceTest.java
- modules/activiti-engine/src/test/java/org/activiti/engine/test/api/task/TaskQueryTest.java
- modules/activiti-engine/src/test/resources/org/activiti/engine/test/api/history/HistoricProcessInstanceQueryTest.testLocalization.bpmn20.xml
- modules/activiti-engine/src/test/resources/org/activiti/engine/test/api/runtime/executionLocalization.bpmn20.xml
- modules/activiti-engine/src/test/resources/org/activiti/engine/test/api/runtime/oneTaskProcess.bpmn20.xml
- modules/activiti-engine/src/test/resources/org/activiti/engine/test/api/task/TaskQueryTest.testProcessDefinition.bpmn20.xml
I rebased these commits to avoid a merge conflict introduced with the BpmnDeployer refactoring that occurred recently.
> Localization support changes

- modules/activiti-engine/src/main/java/org/activiti/engine/impl/persistence/entity/HistoricVariableInstanceEntity.java
- modules/activiti-engine/src/test/java/org/activiti/engine/test/api/history/ProcessInstanceLogQueryAndByteArrayTypeVariableTest.java
Fix NullpointerException occured on referring Historic Variable(Serializable Type) #753
TestCase
https://drive.google.com/open?id=0ByO-BAU8ivtKcF80UUFUX0YtVU0
> Fix NPE occured on referring Historic Variable(Serializable Type)

- userguide/src/en/ch03-Configuration.adoc
> duplicate documents.

- modules/activiti-engine/src/main/java/org/activiti/engine/impl/db/DbSqlSession.java
- modules/activiti-engine/src/main/java/org/activiti/engine/impl/variable/DeserializedObject.java
- modules/activiti-engine/src/main/java/org/activiti/engine/impl/variable/SerializableType.java
reworked Fix for serializable object compare when upgrading JDK version
> MNT-15609 : Fix for serializable object compare when upgrading JDK version

- modules/activiti-spring-boot/spring-boot-starters/activiti-spring-boot-starter-basic/src/main/java/org/activiti/spring/boot/actuate/endpoint/ProcessEngineMvcEndpoint.java
If multiple process versions are available, return the diagram of the newest version.
> Fixes #827: support for multiple process versions added

- modules/activiti-engine/src/main/java/org/activiti/engine/history/HistoricProcessInstanceQuery.java
- modules/activiti-engine/src/main/java/org/activiti/engine/impl/HistoricProcessInstanceQueryImpl.java
- modules/activiti-engine/src/main/java/org/activiti/engine/impl/ProcessInstanceQueryImpl.java
- modules/activiti-engine/src/main/java/org/activiti/engine/runtime/ProcessInstanceQuery.java
- modules/activiti-engine/src/main/resources/org/activiti/db/mapping/entity/Execution.xml
- modules/activiti-engine/src/main/resources/org/activiti/db/mapping/entity/HistoricProcessInstance.xml
- modules/activiti-engine/src/test/java/org/activiti/engine/test/api/history/HistoricProcessInstanceQueryAndWithExceptionTest.java
- modules/activiti-engine/src/test/java/org/activiti/engine/test/api/runtime/ProcessInstanceQueryAndWithExceptionTest.java
- modules/activiti-engine/src/test/resources/org/activiti/engine/test/api/runtime/JobErrorCheck.bpmn20.xml
- modules/activiti-engine/src/test/resources/org/activiti/engine/test/api/runtime/JobErrorDoubleCheck.bpmn20.xml
Web added the search criteria(withException) to ProcessInstanceQuery.This criteria get process instances that job failed.
> Add the search criteria ProcessInstanceQuery#withException()

- modules/activiti-engine/src/main/java/org/activiti/engine/impl/asyncexecutor/AbstractAsyncJobExecutor.java
- modules/activiti-engine/src/main/java/org/activiti/engine/impl/asyncexecutor/AcquireAsyncJobsDueRunnable.java
- modules/activiti-engine/src/main/java/org/activiti/engine/impl/asyncexecutor/AcquireTimerJobsRunnable.java
- modules/activiti-engine/src/main/java/org/activiti/engine/impl/asyncexecutor/DefaultAsyncJobExecutor.java
- modules/activiti-engine/src/main/java/org/activiti/engine/impl/asyncexecutor/DefaultExecuteAsyncRunnableFactory.java
- modules/activiti-engine/src/main/java/org/activiti/engine/impl/asyncexecutor/ExecuteAsyncRunnable.java
The simple changes from https://forums.activiti.org/content/proposed-changes-job-handling-mechanism. I used multiple commits it is easier to see what I did exactly.
> Async changes first part

- modules/activiti-engine/src/main/java/org/activiti/engine/impl/EventSubscriptionQueryImpl.java
- modules/activiti-engine/src/test/java/org/activiti/engine/test/api/nonpublic/EventSubscriptionQueryTest.java
> Fix bug to make it possible to query event subscriptions by id

- modules/activiti-engine/src/test/java/org/activiti/examples/bpmn/tasklistener/TaskListenerTest.java
- modules/activiti-engine/src/test/resources/org/activiti/examples/bpmn/tasklistener/TaskListenerInSubProcessTest.bpmn20.xml
Regression in 6.0beta2 regarding Listeners
> ACT-4133(test): test for user task create listener in the subprocess

- modules/activiti-engine/src/main/java/org/activiti/engine/ProcessEngineConfiguration.java
- modules/activiti-engine/src/main/java/org/activiti/engine/impl/bpmn/deployer/BpmnDeployer.java
- modules/activiti-explorer/src/main/java/org/activiti/explorer/ui/process/ProcessDefinitionImageStreamResourceBuilder.java
- modules/activiti-explorer/src/main/java/org/activiti/explorer/ui/process/simple/editor/SimpleTableEditor.java
- modules/activiti-image-generator/src/main/java/org/activiti/image/ProcessDiagramGenerator.java
- modules/activiti-image-generator/src/main/java/org/activiti/image/impl/DefaultProcessDiagramCanvas.java
- modules/activiti-image-generator/src/main/java/org/activiti/image/impl/DefaultProcessDiagramGenerator.java
- modules/activiti-rest/src/main/java/org/activiti/rest/service/api/runtime/process/ProcessInstanceDiagramResource.java
Default annotationFontName "Arial" can't display Chinese or Japanese or
Korean, Activiti should be able to customize annotationFontName like
labelFontName.
> Supports customize annotationFontName as same as labelFontName

- modules/activiti-engine/src/main/java/org/activiti/engine/impl/cmd/GetDataObjectCmd.java
- modules/activiti-engine/src/main/java/org/activiti/engine/impl/cmd/GetDataObjectsCmd.java
- modules/activiti-engine/src/main/java/org/activiti/engine/impl/cmd/GetExecutionVariableCmd.java
- modules/activiti-engine/src/main/java/org/activiti/engine/impl/cmd/GetExecutionVariableInstanceCmd.java
- modules/activiti-engine/src/main/java/org/activiti/engine/impl/cmd/GetExecutionVariableInstancesCmd.java
- modules/activiti-engine/src/main/java/org/activiti/engine/impl/cmd/GetExecutionVariablesCmd.java
- modules/activiti-engine/src/main/java/org/activiti/engine/impl/event/logger/EventLogger.java
- modules/activiti-engine/src/main/java/org/activiti/engine/impl/util/TimerUtil.java
There are two basic cases:
(1) An explicit test for the the same value a few lines prior to the modified line
(2) An explicit test for the negation of the test that throws an exception.
> Remove redundant null checks

- modules/activiti-engine/src/main/java/org/activiti/engine/TaskService.java
- modules/activiti-engine/src/main/java/org/activiti/engine/impl/DataObjectImpl.java
- modules/activiti-engine/src/main/java/org/activiti/engine/impl/TaskServiceImpl.java
- modules/activiti-engine/src/main/java/org/activiti/engine/impl/bpmn/deployer/BpmnDeployer.java
- modules/activiti-engine/src/main/java/org/activiti/engine/impl/cmd/GetDataObjectCmd.java
- modules/activiti-engine/src/main/java/org/activiti/engine/impl/cmd/GetDataObjectsCmd.java
- modules/activiti-engine/src/main/java/org/activiti/engine/impl/cmd/GetTaskDataObjectCmd.java
- modules/activiti-engine/src/main/java/org/activiti/engine/impl/cmd/GetTaskDataObjectsCmd.java
- modules/activiti-engine/src/main/java/org/activiti/engine/impl/cmd/GetTaskVariableInstanceCmd.java
- modules/activiti-engine/src/main/java/org/activiti/engine/impl/cmd/GetTaskVariableInstancesCmd.java
- modules/activiti-engine/src/main/java/org/activiti/engine/runtime/DataObject.java
- modules/activiti-engine/src/test/java/org/activiti/examples/variables/VariablesTest.java
- modules/activiti-engine/src/test/resources/org/activiti/examples/variables/VariablesTest.testLocalizeDataObjects.bpmn20.xml
This support is needed to retrieve localization values for Variables via the TaskService.
> Add support for retrieving a VariableInstance and DataObject from the TaskService.

- modules/activiti-engine/src/main/java/org/activiti/engine/RepositoryService.java
> Fixed strong tag closing in javadoc documentation in RepositoryService.

- modules/activiti-engine/src/main/java/org/activiti/engine/impl/TaskServiceImpl.java
- modules/activiti-engine/src/main/java/org/activiti/engine/impl/bpmn/behavior/IntermediateThrowCompensationEventActivityBehavior.java
- modules/activiti-engine/src/main/java/org/activiti/engine/impl/bpmn/helper/ClassDelegateFactory.java
- modules/activiti-engine/src/main/java/org/activiti/engine/impl/bpmn/listener/ListenerNotificationHelper.java
- modules/activiti-engine/src/main/java/org/activiti/engine/impl/persistence/entity/HistoricProcessInstanceEntityImpl.java
- modules/activiti-engine/src/main/java/org/activiti/engine/impl/persistence/entity/SuspendedJobEntityManager.java
- modules/activiti-engine/src/main/java/org/activiti/engine/impl/persistence/entity/TaskEntityManagerImpl.java
- modules/activiti-engine/src/main/java/org/activiti/engine/impl/persistence/entity/data/impl/MybatisDeadLetterJobDataManager.java
- modules/activiti-engine/src/main/java/org/activiti/engine/runtime/ExecutionQuery.java
- modules/activiti-process-validation/src/main/java/org/activiti/validation/validator/impl/ExternalInvocationTaskValidator.java
My quarterly pass through the code looking for unused imports.
> Remove unused import statements

- modules/activiti-rest/src/main/java/org/activiti/rest/service/api/runtime/task/TaskVariableBaseResource.java
- modules/activiti-rest/src/test/java/org/activiti/rest/service/api/runtime/SerializableVariablesDiabledTest.java
added rest.variables.allow.serializable check on serialization of task variables
> task variable serialization property check

- modules/activiti-engine/src/main/resources/org/activiti/db/mapping/entity/HistoricProcessInstance.xml
- modules/activiti-engine/src/test/java/org/activiti/engine/test/api/history/HistoricProcessInstanceAndVariablesQueryTest.java
Changed mybatis mapper for HistoricProcessInstance.
Added some test cases.
> Optimization for HistoricProcessInstance queries for 'or queries' with multiple process variable values

- modules/activiti-engine/src/main/java/org/activiti/engine/impl/bpmn/behavior/MultiInstanceActivityBehavior.java
...retrieval of collection value with copying the multi-instance logic into the subclass.
This PR refactors the retrieval of the collection value in the MultiInstanceActivityBehavior class to a separate method. This effectively allows a subclass to build a java.util.Collection instance from a string variable containing JSON without copying some of the Activiti code into the subclass. The driving reason behind this PR is that our use Activiti does not allow variables of type java.util.Collection to be created.
> Refactor MultiInstanceActivityBehavior to allow a subclass override the

- modules/activiti-rest/src/main/java/org/activiti/rest/service/api/runtime/task/TaskBaseResource.java
- modules/activiti-rest/src/main/java/org/activiti/rest/service/api/runtime/task/TaskCollectionResource.java
- modules/activiti-rest/src/main/java/org/activiti/rest/service/api/runtime/task/TaskQueryRequest.java
- modules/activiti-rest/src/test/java/org/activiti/rest/service/api/runtime/TaskCollectionResourceTest.java
- modules/activiti-rest/src/test/java/org/activiti/rest/service/api/runtime/TaskQueryResourceTest.java
- userguide/src/en/ch14-REST.adoc
This adds filter by category for Tasks to Rest API. JIRA issue ACT-4210.
> [Activiti REST : ACT-4210] - query tasks by category attribute.

- modules/activiti-engine/src/main/java/org/activiti/engine/impl/bpmn/behavior/InclusiveGatewayActivityBehavior.java
- modules/activiti-engine/src/test/java/org/activiti/engine/test/bpmn/gateway/InclusiveGatewayDefaultFlowTest.java
- modules/activiti-engine/src/test/resources/org/activiti/engine/test/bpmn/inclusive/InclusiveGatewayTest.defaultFlowTest.bpmn20.xml
We fixed the problem that default flow's execution with inclusive Gateway isn't active.
> Fix default flow inactive problem with inclusive Gateway.

- modules/activiti-rest/src/main/java/org/activiti/rest/service/api/RestResponseFactory.java
- modules/activiti-rest/src/main/java/org/activiti/rest/service/api/runtime/process/ProcessInstanceResponse.java
applied changes from PR #1056 in V6
> Changes from PR #1056 applied in V6

- modules/activiti-engine/src/main/java/org/activiti/engine/impl/HistoricActivityInstanceQueryImpl.java
- modules/activiti-engine/src/test/java/org/activiti/engine/test/history/HistoricActivityInstanceTest.java
- modules/activiti-engine/src/test/resources/org/activiti/engine/test/history/HistoricActivityInstanceTest.testHistoricActivityInstanceUnfinished.bpmn20.xml
More details here:
https://activiti.atlassian.net/browse/ACT-4234
> ACT-4234 HistoricActivityInstanceQuery search unfinished activities - always zero results

- modules/activiti-osgi/src/main/java/org/activiti/osgi/Extender.java
Update OSGi Extender to support comments in service provider configuration files
> ACT-4231 Parse comments in service provider configs

- modules/activiti-engine/src/main/java/org/activiti/engine/impl/HistoricActivityInstanceQueryImpl.java
- modules/activiti-engine/src/test/java/org/activiti/engine/test/history/HistoricActivityInstanceTest.java
- modules/activiti-engine/src/test/resources/org/activiti/engine/test/history/HistoricActivityInstanceTest.testHistoricActivityInstanceUnfinished.bpmn20.xml
More details here:
https://activiti.atlassian.net/browse/ACT-4234
> ACT-4234 HistoricActivityInstanceQuery search unfinished activities - always zero results (v6)

- modules/activiti-engine/src/main/java/org/activiti/engine/impl/persistence/entity/VariableScopeImpl.java
- modules/activiti-engine/src/test/java/org/activiti/engine/test/api/task/TaskServiceTest.java
More Details here:
https://activiti.atlassian.net/browse/ACT-4144
> ACT-4144 - fixed search variables by activityInstanceID in HistoricDetailQuery (V6)

- modules/activiti-secure-javascript/src/main/java/org/activiti/scripting/secure/ClassWhitelister.java
- modules/activiti-secure-javascript/src/main/java/org/activiti/scripting/secure/SecureJavascriptConfigurator.java
- modules/activiti-secure-javascript/src/main/java/org/activiti/scripting/secure/behavior/SecureJavascriptTaskActivityBehavior.java
- modules/activiti-secure-javascript/src/main/java/org/activiti/scripting/secure/impl/DefaultClassWhitelister.java
- modules/activiti-secure-javascript/src/main/java/org/activiti/scripting/secure/impl/SecureJavascriptUtil.java
- modules/activiti-secure-javascript/src/main/java/org/activiti/scripting/secure/impl/SecureScriptClassShutter.java
- modules/activiti-secure-javascript/src/main/java/org/activiti/scripting/secure/impl/SecureScriptScope.java
- modules/activiti-secure-javascript/src/test/java/org/activiti/test/scripting/secure/MyBean.java
- modules/activiti-secure-javascript/src/test/java/org/activiti/test/scripting/secure/SecureScriptingBaseTest.java
- modules/activiti-secure-javascript/src/test/java/org/activiti/test/scripting/secure/SecureScriptingTest.java
- modules/activiti-secure-javascript/src/test/resources/test-secure-script-bean.bpmn20.xml
- Exposes beans in secure scripts
- Introduces ClassWhitelister interface enable whitelisting customization
> [ACT-4252] Expose beans in secure scripting

- modules/activiti-form-model/src/main/java/org/activiti/form/model/FormField.java
Fixing #1092 add sizeY field to FormField in order to match activiti-app form editor behavior.
> Fix #1092 -Update FormField

- modules/activiti-engine/src/main/java/org/activiti/engine/impl/HistoricTaskInstanceQueryImpl.java
- modules/activiti-engine/src/main/java/org/activiti/engine/impl/TaskQueryImpl.java
- modules/activiti-engine/src/main/java/org/activiti/engine/task/TaskInfoQuery.java
- modules/activiti-engine/src/main/resources/org/activiti/db/mapping/entity/HistoricTaskInstance.xml
- modules/activiti-engine/src/main/resources/org/activiti/db/mapping/entity/Task.xml
- modules/activiti-engine/src/test/java/org/activiti/engine/test/api/task/TaskQueryTest.java
Provides initial support for involving groups to tasks
> Support for involving groups to tasks

- modules/activiti-engine/src/main/java/org/activiti/engine/impl/persistence/entity/VariableScopeImpl.java
- modules/activiti5-engine/src/main/java/org/activiti5/engine/impl/persistence/entity/VariableScopeImpl.java
Fixing a possible Null Pointer Exception.
> possible null point exception in activiti6 engine

- modules/activiti-secure-javascript/src/main/java/org/activiti/scripting/secure/behavior/SecureJavascriptTaskActivityBehavior.java
- modules/activiti-secure-javascript/src/test/java/org/activiti/test/scripting/secure/SecureScriptingTest.java
- modules/activiti-secure-javascript/src/test/resources/test-secure-script-execution.bpmn20.xml
fix [ACT-4261](https://activiti.atlassian.net/browse/ACT-4261)
> Using secure scripting process execution gets stuck

- modules/activiti-secure-javascript/src/main/java/org/activiti/scripting/secure/behavior/SecureJavascriptTaskActivityBehavior.java
- modules/activiti-secure-javascript/src/test/java/org/activiti/test/scripting/secure/SecureScriptingBaseTest.java
- modules/activiti-secure-javascript/src/test/java/org/activiti/test/scripting/secure/SecureScriptingTest.java
- modules/activiti-secure-javascript/src/test/resources/test-dynamic-secure-script.bpmn20.xml
Added support for dynamic script behaviour when using secure scripts
> dynamic secure scripts support

- modules/activiti-engine/src/main/java/org/activiti/engine/impl/persistence/entity/ExecutionEntityManagerImpl.java
Process definition name and version were set in createProcessInstanceExecution
> ProcessDefinition name and version were set

- modules/activiti-bpmn-layout/src/main/java/org/activiti/bpmn/BpmnAutoLayout.java
- modules/activiti-ui/activiti-app-logic/src/main/java/org/activiti/app/service/runtime/PermissionService.java
Unnecessary conversion to long for comparing strings in PermissionService.java
Better for-each to translate nested subProcess in BpmnAutoLayout.java
> Comparison type

- modules/activiti-json-converter/src/main/java/org/activiti/editor/language/json/converter/BaseBpmnJsonConverter.java
- modules/activiti-json-converter/src/test/java/org/activiti/editor/language/StartEventConverterTest.java
- modules/activiti-json-converter/src/test/resources/test.starteventmodel.json
Execution listener was missed when a bpmn file was imported from an earlier version of activiti. This branch is to fix that issue.
> Fixed missing execution listener

- modules/activiti-bpmn-converter/src/main/java/org/activiti/bpmn/converter/alfresco/AlfrescoStartEventXMLConverter.java
- modules/activiti-bpmn-converter/src/main/java/org/activiti/bpmn/converter/alfresco/AlfrescoUserTaskXMLConverter.java
- modules/activiti-bpmn-model/src/main/java/org/activiti/bpmn/model/DataObject.java
- modules/activiti-engine/src/main/java/org/activiti/engine/impl/bpmn/behavior/EventBasedGatewayActivityBehavior.java
- modules/activiti-engine/src/main/java/org/activiti/engine/impl/bpmn/behavior/IntermediateCatchTimerEventActivityBehavior.java
- modules/activiti-engine/src/main/java/org/activiti/engine/impl/persistence/entity/HistoricVariableInstanceEntityImpl.java
- modules/activiti-engine/src/main/java/org/activiti/engine/impl/persistence/entity/UserEntityImpl.java
- modules/activiti5-engine/src/main/java/org/activiti5/engine/impl/persistence/entity/DeploymentEntityManager.java
- modules/activiti5-engine/src/main/java/org/activiti5/engine/impl/persistence/entity/ExecutionEntity.java
Some methods present in a class have been repeated in the child class with no variation. Changes were made in 9 such files after verifying the child and parent classes.
> Removing identical methods that are already present in superclass

- modules/activiti-engine/src/main/java/org/activiti/engine/impl/test/TestHelper.java
- modules/activiti-engine/src/main/java/org/activiti/engine/test/Deployment.java
Enabling TenantId (multiple Id ) to be used for Deployment
> Enabling deployment using tenantId

- modules/activiti-spring-boot/spring-boot-samples/spring-boot-sample-jpa/src/main/resources/processes/doge.bpmn20.xml
End event in subProcess was missing.
> Added missing end event in subprocess to fix invalid process xml

- modules/activiti-engine/src/test/java/org/activiti/engine/test/bpmn/subprocess/adhoc/AdhocSubProcessTest.java
- modules/activiti-engine/src/test/java/org/activiti/engine/test/history/HistoricProcessInstanceTest.java
- modules/activiti-engine/src/test/java/org/activiti/standalone/escapeclause/HistoricTaskQueryEscapeClauseTest.java
- modules/activiti-engine/src/test/java/org/activiti/standalone/escapeclause/TaskQueryEscapeClauseTest.java
- modules/activiti-engine/src/test/java/org/activiti/standalone/history/FullHistoryTest.java
Fixed the issues related to the dependency on order of date and time in the test cases.
> Fixed issues in test cases

- modules/activiti-ui/activiti-app-conf/src/main/java/org/activiti/app/security/UserDetailsService.java
> fixed the issue related to user authentication

- modules/activiti-engine/src/main/java/org/activiti/engine/impl/agenda/EndExecutionOperation.java
- modules/activiti-engine/src/main/java/org/activiti/engine/impl/bpmn/behavior/BoundaryEventActivityBehavior.java
- modules/activiti-engine/src/main/java/org/activiti/engine/impl/bpmn/behavior/ParallelMultiInstanceBehavior.java
- modules/activiti-engine/src/main/java/org/activiti/engine/impl/bpmn/behavior/TerminateEndEventActivityBehavior.java
- modules/activiti-engine/src/main/java/org/activiti/engine/impl/bpmn/helper/ErrorPropagation.java
- modules/activiti-engine/src/main/java/org/activiti/engine/impl/jobexecutor/TriggerTimerEventJobHandler.java
- modules/activiti-engine/src/main/java/org/activiti/engine/impl/persistence/entity/ExecutionEntityManager.java
- modules/activiti-engine/src/main/java/org/activiti/engine/impl/persistence/entity/ExecutionEntityManagerImpl.java
- modules/activiti-engine/src/main/java/org/activiti/engine/impl/persistence/entity/TaskEntity.java
- modules/activiti-engine/src/main/java/org/activiti/engine/impl/persistence/entity/TaskEntityImpl.java
- modules/activiti-engine/src/main/java/org/activiti/engine/impl/persistence/entity/TaskEntityManagerImpl.java
- modules/activiti-engine/src/test/java/org/activiti/engine/test/api/event/CancelCallActivityByMessageTest.java
- modules/activiti-engine/src/test/resources/org/activiti/engine/test/api/event/CancelCallActivityByMessageTest.testActivityMessageBoundaryEventsExternalSubProcess.bpmn20.xml
- modules/activiti-engine/src/test/resources/org/activiti/engine/test/api/event/CancelCallActivityByMessageTest.testActivityMessageBoundaryEventsOnCallActivity.bpmn20.xml
Fixed the issue and added new test case.
> Fixed the issue related to boundary message event on callactivity

- modules/activiti-engine/src/main/java/org/activiti/engine/ActivitiEngineAgenda.java
- modules/activiti-engine/src/main/java/org/activiti/engine/Agenda.java
- modules/activiti-engine/src/main/java/org/activiti/engine/impl/agenda/DefaultActivitiEngineAgenda.java
- modules/activiti-engine/src/main/java/org/activiti/engine/impl/interceptor/CommandInvoker.java
- modules/activiti-engine/src/test/java/org/activiti/examples/runtime/WatchDogAgendaFactory.java
- modules/activiti-rest/src/test/java/org/activiti/rest/api/jpa/BaseJPARestTestCase.java
- modules/activiti-rest/src/test/java/org/activiti/rest/service/BaseSpringRestTestCase.java
- Fixed the tricky test with join GW.
- changed the TestCases to abstract.
> Fixed the failing tests

- modules/activiti-json-converter/src/main/java/org/activiti/editor/language/json/converter/UserTaskJsonConverter.java
this fixes the issue with import of bpmn models and userids
> Bpmn models import issue 

- modules/activiti-engine/src/test/java/org/activiti/engine/test/api/history/HistoricTaskAndVariablesQueryTest.java
- modules/activiti-engine/src/test/java/org/activiti/engine/test/api/runtime/TaskInvolvementTest.java
- modules/activiti-engine/src/test/java/org/activiti/engine/test/api/task/TaskServiceTest.java
Check history level when running tests
> Fix failing tests

- modules/activiti-engine/src/test/java/org/activiti/engine/test/api/runtime/ProcessInstanceSuspensionTest.java
- modules/activiti-engine/src/test/java/org/activiti/engine/test/history/HistoricVariableInstanceTest.java
> Fix cfghistoryaudit

- modules/activiti-secure-service-tasks/src/main/java/org/activiti/serviceTasks/secure/SecureServiceTaskConfigurator.java
add support for whitelisted classes for SecureServiceTasksConfigurator
> add support for whitelisted classes for SecureServiceTasksConfigurator

- modules/activiti-engine/src/main/java/org/activiti/engine/impl/db/DbSchemaExport.java
- modules/activiti-engine/src/main/java/org/activiti/engine/impl/db/DbSqlSession.java
- modules/activiti-engine/src/main/java/org/activiti/engine/impl/test/TestHelper.java
- modules/activiti-engine/src/main/java/org/activiti/engine/impl/util/IoUtil.java
These changes are to ensure that connections are closed. They are in response to the most recent available sonar report and in response to ACTIVITI-29
> changes recommended by sonar report

- modules/activiti-engine/src/main/java/org/activiti/engine/impl/persistence/entity/TableDataManager.java
> added missing backslash to escape _ character

- modules/activiti-engine/src/main/java/org/activiti/engine/impl/persistence/entity/DeploymentEntityManager.java
- modules/activiti-engine/src/main/java/org/activiti/engine/impl/persistence/entity/ExecutionEntity.java
- modules/activiti-engine/src/main/java/org/activiti/engine/impl/persistence/entity/ExecutionEntityManager.java
- modules/activiti-engine/src/main/java/org/activiti/engine/impl/pvm/runtime/AbstractEventAtomicOperation.java
- modules/activiti-engine/src/main/java/org/activiti/engine/impl/pvm/runtime/ExecutionImpl.java
- modules/activiti-engine/src/main/java/org/activiti/engine/impl/pvm/runtime/InterpretableExecution.java
- modules/activiti-engine/src/test/java/org/activiti/examples/bpmn/executionlistener/ExecutionListenerTest.java
- modules/activiti-engine/src/test/java/org/activiti/examples/bpmn/executionlistener/FailingRecorderExecutionListener.java
- modules/activiti-engine/src/test/resources/org/activiti/examples/bpmn/executionlistener/ExecutionListenersStartEndEvent.bpmn20.xml
- modules/activiti-engine/src/test/resources/org/activiti/examples/bpmn/executionlistener/ExecutionListenersStartEndEventDeleteDeployment.bpmn20.xml
unable to delete the deplyment when there is a execution listener in error.
> #ACT-4289:

- modules/activiti-ui/activiti-app/src/main/webapp/scripts/landing-app.js
> Add additional protection to redirect on login

- modules/activiti-secure-service-tasks/src/test/java/org/activiti/test/serviceTask/secure/SecureServiceTaskBaseTest.java
- modules/activiti-secure-service-tasks/src/test/java/org/activiti/test/serviceTask/secure/SecureShellTaskTest.java
- modules/activiti-secure-service-tasks/src/test/resources/ShellTaskTest.testShellWindows.bpmn20.xml
this fixes the test case failure in activiti-secure-service-task module for windows os.
> ACT-4296 fix

- modules/activiti-form-engine/src/main/java/org/activiti/form/engine/impl/cmd/GetRuntimeFormDefinitionCmd.java
- modules/activiti-ui/activiti-app/src/main/webapp/scripts/common/directives.js
- modules/activiti-ui/activiti-app/src/main/webapp/workflow/scripts/controllers/render-form.js
- modules/activiti-ui/activiti-app/src/main/webapp/workflow/views/templates/form-element-template.html
This will fix the form data retention issue i.e issue no  ACT-4297
> Fix for ACT-4297

- modules/activiti-secure-service-tasks/src/test/java/org/activiti/test/serviceTask/secure/SecureShellTaskTest.java
- modules/activiti-secure-service-tasks/src/test/resources/ShellTaskTest.testShellWindows.bpmn20.xml
> shell Task Process Instance name Issue

- modules/activiti-engine/src/main/java/org/activiti/engine/impl/bpmn/helper/ErrorPropagation.java
- modules/activiti-engine/src/test/java/org/activiti/engine/test/bpmn/event/error/BoundaryErrorEventTest.java
- modules/activiti-engine/src/test/resources/org/activiti/engine/test/bpmn/event/error/BoundaryErrorEventTest.catchErrorEvents.bpmn20.xml
- modules/activiti-engine/src/test/resources/org/activiti/engine/test/bpmn/event/error/BoundaryErrorEventTest.testCatchErrorEventsOnCallActiviti.bpmn20.xml
- modules/activiti-engine/src/test/resources/org/activiti/engine/test/bpmn/event/error/BoundaryErrorEventTest.testCatchErrorEventsOnMultipleCallActiviti.bpmn20.xml
- modules/activiti-engine/src/test/resources/org/activiti/engine/test/bpmn/event/error/BoundaryErrorEventTest.testCatchErrorEventsOnMultipleCallActivitiS.bpmn20.xml
- modules/activiti-engine/src/test/resources/org/activiti/engine/test/bpmn/event/error/BoundaryErrorEventTest.testThrowErrorEventsWithError.bpmn20.xml
- modules/activiti-engine/src/test/resources/org/activiti/engine/test/bpmn/event/error/BoundaryErrorEventTest.testThrowErrorEventsWithOutError.bpmn20.xml
- modules/activiti-engine/src/test/resources/org/activiti/engine/test/bpmn/event/error/BoundaryErrorEventTest.throwErrorEvent.bpmn20.xml
- modules/activiti-engine/src/test/resources/org/activiti/engine/test/bpmn/event/error/BoundaryErrorEventTest.throwOtherErrorEvent.bpmn20.xml
This fixes the multi instance processes error catch event issue
> Fix for ACT-4300

- modules/activiti-bpmn-converter/src/test/java/org/activiti/editor/language/xml/MessageConverterTest.java
- modules/activiti-engine/src/main/java/org/activiti/engine/impl/bpmn/deployer/EventSubscriptionManager.java
- modules/activiti-engine/src/main/java/org/activiti/engine/impl/cmd/StartProcessInstanceByMessageCmd.java
- modules/activiti-engine/src/main/java/org/activiti/engine/impl/util/ProcessInstanceHelper.java
It fixes the failure of message start event. [Fixes this bug in Jira](https://activiti.atlassian.net/browse/ACT-4278)
> Fix for failure of process instance creation by message start event

- modules/activiti-rest/src/main/java/org/activiti/rest/service/api/runtime/task/TaskBaseResource.java
- modules/activiti-rest/src/main/java/org/activiti/rest/service/api/runtime/task/TaskCollectionResource.java
Fix for the Bug i.e, tasks are not filtering instead returning all tasks as response when given "withoutDueDate=true" filter in REST API.
> WithoutDueDate filter fix

- .travis.yml
- activiti-bpmn-converter/pom.xml
- activiti-bpmn-layout/pom.xml
- activiti-bpmn-model/pom.xml
- activiti-json-converter/pom.xml
- activiti-process-validation/pom.xml
- activiti-spring-boot/pom.xml
- activiti-spring-boot/spring-boot-starters/activiti-spring-boot-starter-basic/pom.xml
- activiti-spring/pom.xml
- pom.xml
Maven pom cleanup:
- Removing the parent pom
- Adding / upgrading project metadata
- Upgrading Maven plugins
- Removing useless `distro` profile
Automating releases:
- include distribution URLs (snapshot and release)
- configuration of the maven-release-plugin
> Maven cleanup + automation of release tasks

- activiti-bpmn-converter/pom.xml
- activiti-bpmn-layout/pom.xml
- activiti-bpmn-model/pom.xml
- activiti-engine/pom.xml
- activiti-json-converter/pom.xml
- activiti-process-validation/pom.xml
- activiti-services/activiti-services-core-model/pom.xml
- activiti-services/activiti-services-core/pom.xml
- activiti-services/activiti-services-events/pom.xml
- activiti-services/activiti-services-identity-keycloak/pom.xml
- activiti-services/activiti-services-rest/pom.xml
- activiti-services/pom.xml
- activiti-spring-boot/pom.xml
- activiti-spring-boot/spring-boot-samples/pom.xml
- activiti-spring-boot/spring-boot-samples/spring-boot-sample-hal-rest-api/pom.xml
- activiti-spring-boot/spring-boot-starters/activiti-spring-boot-starter-basic/pom.xml
- activiti-spring-boot/spring-boot-starters/activiti-spring-boot-starter/pom.xml
- activiti-spring-boot/spring-boot-starters/pom.xml
- activiti-spring/pom.xml
- pom.xml
I'm updating the pom versions to 7-201707-EA-SNAPSHOT and fixing a wrong artefact Id
> Salaboy 1282 update poms version

- modules/activiti-webapp-explorer2/src/main/webapp/VAADIN/widgetsets/org.activiti.explorer.CustomWidgetset/css/styles.css
- modules/activiti-webapp-explorer2/src/main/webapp/VAADIN/widgetsets/org.activiti.explorer.CustomWidgetset/dcharts/styles.css
When running the VA scan it captured as a vulnerability as "List of all email addresses found on this host."
- vaadin@dussan.org
> remove vaadin@dussan.org as it capthured in  VA reports

- activiti-services/activiti-services-rest/src/main/java/org/activiti/services/rest/controllers/HomeController.java
- activiti-services/activiti-services-rest/src/main/java/org/activiti/services/rest/controllers/ProcessDefinitionController.java
- activiti-services/activiti-services-rest/src/main/java/org/activiti/services/rest/controllers/ProcessDefinitionMetaController.java
- activiti-services/activiti-services-rest/src/main/java/org/activiti/services/rest/controllers/ProcessInstanceController.java
- activiti-services/activiti-services-rest/src/main/java/org/activiti/services/rest/controllers/ProcessInstanceTasksController.java
- activiti-services/activiti-services-rest/src/main/java/org/activiti/services/rest/controllers/ProcessInstanceVariableController.java
- activiti-services/activiti-services-rest/src/main/java/org/activiti/services/rest/controllers/TaskController.java
- activiti-spring-boot/spring-boot-starters/activiti-spring-boot-starter/src/test/java/org/activiti/cmdendpoint/CommandEndpointTest.java
- activiti-spring-boot/spring-boot-starters/activiti-spring-boot-starter/src/test/java/org/activiti/definition/ProcessDefinitionIT.java
- activiti-spring-boot/spring-boot-starters/activiti-spring-boot-starter/src/test/java/org/activiti/runtime/ProcessInstanceRestTemplate.java
- activiti-spring-boot/spring-boot-starters/activiti-spring-boot-starter/src/test/java/org/activiti/runtime/TasksIT.java
Just adding simple versioning to HAL API endpoints (v1)
> Salaboy 1284 api versioning

- activiti-services/activiti-services-gateway/.gitignore
- activiti-services/activiti-services-gateway/pom.xml
- activiti-services/activiti-services-gateway/src/main/java/org/activiti/services/gateway/GatewayApplication.java
- activiti-services/activiti-services-gateway/src/main/resources/application.properties
- activiti-services/pom.xml
Just adding the Gateway, I will add the registry in a different PR
> adding gateway service

- activiti-image-generator/pom.xml
- activiti-image-generator/src/main/java/org/activiti/image/impl/DefaultProcessDiagramGenerator.java
- activiti-services/activiti-services-core-model/pom.xml
- activiti-services/activiti-services-core/src/main/java/org/activiti/services/core/ProcessEngineWrapper.java
- activiti-services/activiti-services-rest/pom.xml
- activiti-services/activiti-services-rest/src/main/java/org/activiti/services/rest/controllers/ProcessDefinitionController.java
- activiti-services/activiti-services-rest/src/main/java/org/activiti/services/rest/controllers/ProcessInstanceController.java
- activiti-spring-boot/spring-boot-starters/activiti-spring-boot-starter/src/test/java/org/activiti/definition/ProcessDefinitionIT.java
- activiti-spring-boot/spring-boot-starters/activiti-spring-boot-starter/src/test/java/org/activiti/keycloak/KeycloakEnabledBaseTestIT.java
- activiti-spring-boot/spring-boot-starters/activiti-spring-boot-starter/src/test/java/org/activiti/runtime/ProcessInstanceIT.java
- activiti-spring-boot/spring-boot-starters/activiti-spring-boot-starter/src/test/java/org/activiti/test/util/TestResourceUtil.java
Refer to https://github.com/Activiti/Activiti/issues/1320
> SVG endpoints for Process Definitions and Process Instances #1320

- activiti-services/activiti-services-audit/activiti-services-audit-jpa/pom.xml
- activiti-services/activiti-services-audit/activiti-services-audit-jpa/src/main/resources/application.properties
- activiti-services/activiti-services-audit/activiti-services-audit-jpa/src/test/resources/application-producer-test.properties
- activiti-spring-boot/spring-boot-starters/activiti-spring-boot-starter/src/test/resources/application.properties
- docker/README.md
- docker/docker-compose.yml
Am creating a related PR in the sample repo so that the sample can instead be started from there. Audit service should be included in the core services.
> move sample to its own repo

- activiti-services/activiti-services-audit/activiti-services-audit-jpa/pom.xml
- activiti-services/activiti-services-audit/activiti-services-audit-jpa/src/main/java/org/activiti/JpaAuditApplication.java
- activiti-services/activiti-services-audit/activiti-services-audit-jpa/src/main/resources/application.properties
- activiti-services/activiti-services-registry/src/main/resources/application.properties
- activiti-spring-boot/spring-boot-starters/activiti-spring-boot-starter/pom.xml
@erdemedeiros @ryandawsonuk please review and merge
> enable discovery

- activiti-services/activiti-services-audit/activiti-services-audit-jpa/src/main/java/org/activiti/JpaAuditApplication.java
- activiti-services/activiti-services-core/src/main/java/org/activiti/services/core/commands/CommandEndpoint.java
- activiti-services/activiti-services-events/pom.xml
- activiti-services/activiti-services-events/src/main/java/org/activiti/services/events/converter/EventConverterContext.java
- activiti-services/activiti-services-events/src/main/java/org/activiti/services/events/converter/ProcessCompletedEventConverter.java
- activiti-services/activiti-services-events/src/main/java/org/activiti/services/events/converter/TaskAssignedEventConverter.java
- activiti-services/activiti-services-events/src/main/java/org/activiti/services/events/converter/TaskCompletedEventConverter.java
- activiti-services/activiti-services-events/src/main/java/org/activiti/services/events/converter/TaskCreatedEventConverter.java
- activiti-services/activiti-services-events/src/main/java/org/activiti/services/events/converter/VariableDeletedEventConveter.java
- activiti-services/activiti-services-events/src/main/java/org/activiti/services/events/converter/VariableUpdatedEventConverter.java
- activiti-services/activiti-services-events/src/test/resources/logback-test.xml
- activiti-spring-boot/spring-boot-starters/activiti-spring-boot-starter/pom.xml
- activiti-spring-boot/spring-boot-starters/activiti-spring-boot-starter/src/test/java/org/activiti/starter/tests/cmdendpoint/WaitUtil.java
- activiti-spring-boot/spring-boot-starters/activiti-spring-boot-starter/src/test/resources/logback-test.xml
Look at my comment associated with this issue.
> removing souts and adding logging

- pom.xml
> Fixes Eclipse STS m2e plugin execution not covered by lifecycle mapping errors (#1357)

- activiti-services/activiti-services-audit/activiti-services-audit-jpa/pom.xml
- activiti-services/activiti-services-gateway/pom.xml
- activiti-services/activiti-services-registry/pom.xml
Reduces size of images we generate from ~700mb to ~170mb.
> smaller docker images

- activiti-spring-boot/spring-boot-starters/activiti-spring-boot-starter/src/main/java/org/activiti/configuration/ActivitiRuntimeBundle.java
@ryandawsonuk can you check and merge this one?
> adding ActivitiRuntimeBundle annotation

- activiti-services/activiti-services-audit/activiti-services-audit-jpa/src/main/java/org/activiti/services/audit/ProcessEngineEventsController.java
- activiti-services/activiti-services-audit/activiti-services-audit-jpa/src/test/java/org/activiti/services/audit/EventsRestTemplate.java
The Query service should do the same. @erdemedeiros @ryandawsonuk please review and merge
> Audit Service aligned

- activiti-services/activiti-services-core-model/src/main/java/org/activiti/services/core/model/TaskVariables.java
- activiti-services/activiti-services-core-model/src/main/java/org/activiti/services/core/model/commands/SetTaskVariablesCmd.java
- activiti-services/activiti-services-core/src/main/java/org/activiti/services/core/ProcessEngineWrapper.java
- activiti-services/activiti-services-rest/src/main/java/org/activiti/services/rest/controllers/TaskController.java
- activiti-services/activiti-services-rest/src/main/java/org/activiti/services/rest/controllers/TaskVariableController.java
- activiti-services/activiti-services-rest/src/main/java/org/activiti/services/rest/resources/assembler/TaskVariableResourceAssembler.java
- activiti-spring-boot/spring-boot-starters/activiti-spring-boot-starter/src/test/java/org/activiti/starter/tests/helper/TaskRestTemplate.java
- activiti-spring-boot/spring-boot-starters/activiti-spring-boot-starter/src/test/java/org/activiti/starter/tests/runtime/TaskVariablesIT.java
https://github.com/Activiti/Activiti/issues/1302
* Binary variables(Multipart request) are not supported yet.
> TaskVariable endpoint is missing, find out if it can be provided. #1302

- .gitignore
Refer to https://github.com/Activiti/Activiti/issues/1363
> Add the setting of .gitignore for Eclipse

- modules/activiti-engine/src/main/java/org/activiti/engine/history/HistoricProcessInstanceQuery.java
- modules/activiti-engine/src/main/java/org/activiti/engine/impl/ExecutionQueryImpl.java
- modules/activiti-engine/src/main/java/org/activiti/engine/impl/HistoricProcessInstanceQueryImpl.java
- modules/activiti-engine/src/main/java/org/activiti/engine/impl/ProcessInstanceQueryImpl.java
- modules/activiti-engine/src/main/java/org/activiti/engine/runtime/ProcessInstanceQuery.java
- modules/activiti-engine/src/main/resources/org/activiti/db/mapping/entity/Execution.xml
- modules/activiti-engine/src/main/resources/org/activiti/db/mapping/entity/HistoricProcessInstance.xml
- modules/activiti-engine/src/test/java/org/activiti/engine/test/api/history/HistoricProcessInstanceQueryGroupInvolvementTest.java
- modules/activiti-engine/src/test/java/org/activiti/engine/test/api/runtime/InstanceInvolvementTest.java
- modules/activiti-engine/src/test/resources/org/activiti/engine/test/api/history/HistoricProcessInstanceQueryGroupInvolvementTest.bpmn20.xml
- modules/activiti-engine/src/test/resources/org/activiti/engine/test/api/runtime/groupInvolvementProcess.bpmn20.xml
ACTIVITI-1291 added involvedGroupsIn() query capability for ProcessQuery (both HistoricProcessInstanceQuery & ProcessInstanceQuery)
> ACTIVITI-1291 added involvedGroupsIn() query capability for ProcessQuery (both HistoricProcessInstanceQuery & ProcessInstanceQuery)

- activiti-services/activiti-services-api/pom.xml
- activiti-services/activiti-services-core-model/pom.xml
- activiti-services/activiti-services-core/pom.xml
- activiti-services/activiti-services-core/src/main/java/org/activiti/services/core/AuthenticationWrapper.java
- activiti-services/activiti-services-core/src/main/java/org/activiti/services/core/pageable/PageableTaskService.java
- activiti-services/activiti-services-events/pom.xml
- activiti-services/activiti-services-rest-impl/src/main/java/org/activiti/services/rest/controllers/TaskControllerImpl.java
@erdemedeiros can you please review?
> removing engine dep from services-api

- activiti-services/activiti-services-audit/activiti-services-audit-jpa/pom.xml
- activiti-services/activiti-services-audit/activiti-services-audit-jpa/src/main/java/org/activiti/services/audit/EventsRepository.java
- activiti-services/activiti-services-audit/activiti-services-audit-jpa/src/main/java/org/activiti/services/audit/ProcessEngineEventsController.java
- activiti-services/activiti-services-query/activiti-services-query-model/pom.xml
> Add basic filtering for audit events

- activiti-services/activiti-services-audit/activiti-services-audit-jpa/pom.xml
- activiti-services/activiti-services-audit/activiti-services-audit-jpa/src/main/java/org/activiti/services/audit/channel/AuditConsumerChannelHandler.java
- activiti-services/activiti-services-audit/activiti-services-audit-jpa/src/main/java/org/activiti/services/audit/channel/AuditConsumerChannels.java
- activiti-services/activiti-services-audit/activiti-services-audit-jpa/src/test/java/org/activiti/services/audit/channel/AuditConsumerChannelHandlerTest.java
Closes #1433 
Moved from SpringBoot application to services
> Move Audit events handling to a dedicated component

- activiti-services/activiti-services-audit/activiti-services-audit-jpa/src/main/java/org/activiti/services/audit/events/BaseActivityEventEntity.java
Fix #1446
Root cause: Missing annotation @Entity on BaseActivityEventEntity
> Fix missing fields on activity events

- modules/activiti-engine/src/main/java/org/activiti/engine/impl/interceptor/CommandContextInterceptor.java
- modules/activiti-engine/src/test/java/org/activiti/engine/test/transactions/TransactionRollbackTest.java
- modules/activiti-engine/src/test/resources/org/activiti/engine/test/transactions/TransactionRollbackTest.testRollbackAfterError.bpmn20.xml
Refer to https://github.com/Activiti/Activiti/pull/1526
> Backport #1526 to 5.x

- modules/activiti-engine/src/main/java/org/activiti/engine/impl/interceptor/CommandContextInterceptor.java
- modules/activiti-engine/src/test/java/org/activiti/engine/test/transactions/TransactionRollbackTest.java
- modules/activiti-engine/src/test/resources/org/activiti/engine/test/transactions/TransactionRollbackTest.testRollbackAfterError.bpmn20.xml
>  Backport #1526 to 6.x

- modules/activiti-explorer/src/main/java/org/activiti/editor/ui/EditorProcessDefinitionDetailPanel.java
- modules/activiti-webapp-explorer2/src/main/resources/activiti-custom-context.xml
- modules/activiti-webapp-rest2/src/main/resources/activiti-custom-context.xml
> fix Chinese Disorderly Code when import/edit/deploy model on branch 5.x

- modules/activiti-webapp-rest2/src/main/resources/activiti-custom-context.xml
i checked the code, it seems only happen when export model to image. deploy has fixed.
see also #1131 and #818
> fix cdc on branch 6.x

- modules/activiti-ui/activiti-app-conf/src/main/java/org/activiti/app/servlet/ApiDispatcherServletConfiguration.java
- modules/activiti-ui/activiti-app-conf/src/main/java/org/activiti/app/servlet/AppDispatcherServletConfiguration.java
fixes broken multipart file uploads, see issue
https://github.com/Activiti/Activiti/issues/1553
> provide MulipartResolver bean for REST API

- modules/activiti-bpmn-converter/src/main/java/org/activiti/bpmn/constants/BpmnXMLConstants.java
- modules/activiti-bpmn-converter/src/main/java/org/activiti/bpmn/converter/CallActivityXMLConverter.java
- modules/activiti-bpmn-model/src/main/java/org/activiti/bpmn/model/CallActivity.java
- modules/activiti-engine/src/main/java/org/activiti/engine/impl/bpmn/behavior/CallActivityBehavior.java
- modules/activiti-engine/src/main/java/org/activiti/engine/impl/bpmn/parser/factory/DefaultActivityBehaviorFactory.java
- modules/activiti-engine/src/main/java/org/activiti/engine/impl/pvm/PvmProcessInstance.java
- modules/activiti-engine/src/main/java/org/activiti/engine/impl/pvm/runtime/ExecutionImpl.java
- modules/activiti-engine/src/test/java/org/activiti/engine/test/bpmn/subprocess/CallActivityTest.java
- modules/activiti-engine/src/test/resources/org/activiti/examples/bpmn/callactivity/childProcess.bpmn20.xml
- modules/activiti-engine/src/test/resources/org/activiti/examples/bpmn/callactivity/mainProcess.bpmn20.xml
- modules/activiti-engine/src/test/resources/org/activiti/examples/bpmn/callactivity/mainProcessBusinessKey.bpmn20.xml
- modules/activiti-engine/src/test/resources/org/activiti/examples/bpmn/callactivity/mainProcessInheritBusinessKey.bpmn20.xml
I backported the following commits into 5.x branch.
https://github.com/Activiti/Activiti/pull/975
https://github.com/Activiti/Activiti/commit/2a5875151863fd25ccffc1990412279982249ede#diff-03629ad959b2997050be5e3403a7785f
> Backport call activity business key to 5.x

- pom.xml
> [#1621] updated Jackson to 2.8.10

- pom.xml
> CVE-2017-9801 commons-mail vulnerability fix

- activiti-image-generator/pom.xml
- activiti-image-generator/src/test/java/org/activiti/engine/test/image/ProcessDiagramGeneratorTest.java
- activiti-spring/src/test/java/org/activiti/spring/test/autodeployment/SpringAutoDeployTest.java
fix reported vulnerability on commons-email and batik
> Feature/mteodori 1601 vulnerability check (#1614)

- activiti-bpmn-converter/src/test/java/org/activiti/bpmn/converter/ServiceTaskXMLConverterTest.java
- activiti-engine/src/main/java/org/activiti/engine/UserGroupLookupProxy.java
- activiti-engine/src/main/java/org/activiti/engine/UserRoleLookupProxy.java
- activiti-engine/src/main/java/org/activiti/engine/impl/NativeTaskQueryImpl.java
- activiti-engine/src/main/java/org/activiti/engine/impl/cmd/integration/DeleteIntegrationContextCmd.java
- activiti-engine/src/main/java/org/activiti/engine/impl/cmd/integration/RetrieveIntegrationContextsCmd.java
- activiti-engine/src/main/java/org/activiti/engine/impl/persistence/entity/data/integration/IntegrationContextDataManager.java
- activiti-engine/src/main/java/org/activiti/engine/impl/persistence/entity/data/integration/MybatisIntegrationContextDataManager.java
- activiti-engine/src/main/java/org/activiti/engine/impl/persistence/entity/integration/IntegrationContextEntity.java
- activiti-engine/src/main/java/org/activiti/engine/impl/persistence/entity/integration/IntegrationContextEntityImpl.java
- activiti-engine/src/main/java/org/activiti/engine/impl/persistence/entity/integration/IntegrationContextManager.java
- activiti-engine/src/main/java/org/activiti/engine/impl/persistence/entity/integration/IntegrationContextManagerImpl.java
- activiti-engine/src/main/java/org/activiti/engine/integration/IntegrationContextService.java
- activiti-engine/src/main/java/org/activiti/engine/integration/IntegrationContextServiceImpl.java
- activiti-engine/src/main/resources/org/activiti/db/mapping/entity/IntegrationContext.xml
- activiti-engine/src/test/java/org/activiti/engine/impl/bpmn/parser/handler/ServiceTaskParseHandlerTest.java
- activiti-engine/src/test/java/org/activiti/engine/impl/cmd/integration/DeleteIntegrationContextCmdTest.java
- activiti-engine/src/test/java/org/activiti/engine/impl/cmd/integration/RetrieveIntegrationContextCmdTest.java
- activiti-engine/src/test/java/org/activiti/engine/impl/persistence/entity/data/MybatisIntegrationContextDataManagerTest.java
- activiti-engine/src/test/java/org/activiti/engine/impl/persistence/entity/integration/IntegrationContextManagerImplTest.java
- activiti-engine/src/test/java/org/activiti/engine/integration/IntegrationContextServiceImplTest.java
- activiti-image-generator/src/main/java/org/activiti/image/ProcessDiagramGenerator.java
- activiti-image-generator/src/main/java/org/activiti/image/exception/ActivitiImageException.java
- activiti-image-generator/src/main/java/org/activiti/image/impl/DefaultProcessDiagramCanvas.java
- activiti-image-generator/src/main/java/org/activiti/image/impl/DefaultProcessDiagramGenerator.java
- activiti-process-validation/src/test/java/org/activiti/validation/validator/impl/ServiceTaskValidatorTest.java
- since a new year started the copyright year was updated to 2018
refs #1686
> Update copyright header

- activiti-bpmn-model/src/main/java/org/activiti/bpmn/model/FlowElementsContainer.java
- activiti-bpmn-model/src/main/java/org/activiti/bpmn/model/Process.java
- activiti-bpmn-model/src/main/java/org/activiti/bpmn/model/SubProcess.java
- activiti-json-converter/src/test/java/org/activiti/editor/language/AbstractConverterTest.java
- activiti-json-converter/src/test/java/org/activiti/editor/language/SubProcessTest.java
- activiti-json-converter/src/test/resources/test.subprocess.xml
fixes #1518 (target: `develop`)
> Fix(develop)/flow element map

- modules/activiti-rest/src/main/java/org/activiti/rest/service/api/repository/DeploymentCollectionResource.java
- modules/activiti-rest/src/test/java/org/activiti/rest/service/api/repository/DeploymentResourceTest.java
Please refer to https://community.alfresco.com/message/827728-re-rest-deployment-adding-a-category
> Adding category parameter to deployment rest

- modules/activiti-engine/pom.xml
- modules/activiti-engine/src/main/java/org/activiti/engine/impl/HistoricTaskInstanceQueryImpl.java
- modules/activiti-engine/src/main/java/org/activiti/engine/impl/history/DefaultHistoryManager.java
- modules/activiti-engine/src/main/java/org/activiti/engine/impl/persistence/entity/HistoricTaskInstanceEntity.java
- modules/activiti-engine/src/main/java/org/activiti/engine/impl/persistence/entity/HistoricVariableInstanceEntity.java
- modules/activiti-engine/src/main/resources/org/activiti/db/mapping/entity/HistoricVariableInstance.xml
- modules/activiti-engine/src/test/java/org/activiti/engine/test/api/task/TaskVariablesTest.java
- modules/activiti-engine/src/test/java/org/activiti/engine/test/history/HistoricTaskInstanceUpdateTest.java
- modules/activiti-engine/src/test/resources/org/activiti/engine/test/api/task/TaskVariablesTest.testTaskLocalVar.bpmn20.xml
- modules/activiti-engine/src/test/resources/org/activiti/engine/test/history/HistoricTaskInstanceUpdateTest.testHistoricTaskInstanceExecutionIdUpdateOnConcurrentExecution.bpmn20.xml
- pom.xml
Update the persisted historic task instances that are open
> Update the persisted historic task instances that are open

- modules/activiti-engine/src/main/java/org/activiti/engine/impl/history/DefaultHistoryManager.java
- modules/activiti-engine/src/test/java/org/activiti/engine/test/api/task/TaskVariablesTest.java
- modules/activiti-engine/src/test/resources/org/activiti/engine/test/api/task/TaskVariablesTest.testTaskLocalVar.bpmn20.xml
Following discussion in PR #1612
> fix task local variables execution id replacement

- activiti-bpmn-converter/src/main/resources/org/activiti/impl/bpmn/parser/activiti-bpmn-extensions-5.18.xsd
> [develop] add missing businessCalendarName to 5.18 schema

- activiti-bpmn-layout/pom.xml
- activiti-bpmn-layout/src/main/java/org/activiti/bpmn/BpmnAutoLayout.java
depends on https://github.com/Activiti/activiti-build/pull/24
> updated jgraphx to fix CVE-2017-18197

- activiti-engine/src/main/java/org/activiti/engine/impl/bpmn/behavior/ServiceTaskDelegateExpressionActivityBehavior.java
- activiti-engine/src/main/java/org/activiti/engine/impl/bpmn/parser/factory/ActivityBehaviorFactory.java
- activiti-engine/src/main/java/org/activiti/engine/impl/bpmn/parser/factory/DefaultActivityBehaviorFactory.java
- activiti-engine/src/main/java/org/activiti/engine/impl/bpmn/parser/handler/ServiceTaskParseHandler.java
- activiti-engine/src/main/java/org/activiti/engine/test/TestActivityBehaviorFactory.java
- activiti-engine/src/test/java/org/activiti/standalone/validation/DefaultProcessValidatorTest.java
- activiti-process-validation/src/main/java/org/activiti/validation/validator/impl/ServiceTaskValidator.java
- activiti-process-validation/src/test/java/org/activiti/validation/validator/impl/ServiceTaskValidatorTest.java
Need to create a PR for RB that set MQServiceTaskBehavior as the default behavior service tasks
> Rename MQServiceTaskBehavior bean

- .gitignore
- .updatebot.yml
- Jenkinsfile
- activiti-api-impl/activiti-api-model-shared-impl/pom.xml
- activiti-api-impl/activiti-api-process-model-impl/pom.xml
- activiti-api-impl/activiti-api-process-runtime-impl/pom.xml
- activiti-api-impl/activiti-api-runtime-shared-impl/pom.xml
- activiti-api-impl/activiti-api-task-model-impl/pom.xml
- activiti-api-impl/activiti-api-task-runtime-impl/pom.xml
- activiti-api-impl/pom.xml
- activiti-bpmn-layout/pom.xml
- activiti-core-dependencies/pom.xml
- activiti-spring-boot-starter/pom.xml
- pom.xml
This PR contains changes to implement #1994 first iteration
> Final Pom Alignment for CI/CD

- pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed version changes from the source code in repository: `Activiti/activiti-build` ref: `master`
> update Activiti/activiti-build to master

- .travis.yml
https://github.com/Activiti/Activiti/issues/2007
> ensure ITs run in travis and not skipped by flag

- pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed version changes from the source code in repository: `Activiti/activiti-api` ref: `develop`
> update Activiti/activiti-api to develop

- pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.api:activiti-api-dependencies` to: `7.0.20`
> update org.activiti.api:activiti-api-dependencies to 7.0.20

- pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.api:activiti-api-dependencies` to: `7.0.22`
> update org.activiti.api:activiti-api-dependencies to 7.0.24

- pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.build:activiti-parent` to: `7.0.32`
> update org.activiti.build:activiti-parent to 7.0.33

- pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.api:activiti-api-dependencies` to: `7.0.25`
> update org.activiti.api:activiti-api-dependencies to 7.0.27

- pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.build:activiti-parent` to: `7.0.34`
> update org.activiti.build:activiti-parent to 7.0.36

- pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.api:activiti-api-dependencies` to: `7.0.28`
> update org.activiti.api:activiti-api-dependencies to 7.0.28

- pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.build:activiti-parent` to: `7.0.37`
> update org.activiti.build:activiti-parent to 7.0.38

- pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.api:activiti-api-dependencies` to: `7.0.29`
> update org.activiti.api:activiti-api-dependencies to 7.0.31

- pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.api:activiti-api-dependencies` to: `7.0.32`
> update org.activiti.api:activiti-api-dependencies to 7.0.32

- pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.core.common:activiti-core-common-dependencies` to: `7.0.0`
> update org.activiti.core.common:activiti-core-common-dependencies to 7.0.0

- pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.api:activiti-api-dependencies` to: `7.0.34`
> update org.activiti.api:activiti-api-dependencies to 7.0.34

- pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.core.common:activiti-core-common-dependencies` to: `7.0.2`
> update org.activiti.core.common:activiti-core-common-dependencies to 7.0.2

- pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.core.common:activiti-core-common-dependencies` to: `7.0.3`
> update org.activiti.core.common:activiti-core-common-dependencies to 7.0.3

- activiti-engine/src/main/java/org/activiti/engine/impl/cmd/GetExecutionVariableInstanceCmd.java
- activiti-engine/src/main/java/org/activiti/engine/impl/cmd/GetExecutionVariableInstancesCmd.java
- activiti-engine/src/main/java/org/activiti/engine/impl/cmd/GetTaskVariableInstanceCmd.java
- activiti-engine/src/main/java/org/activiti/engine/impl/cmd/GetTaskVariableInstancesCmd.java
- activiti-engine/src/test/java/org/activiti/engine/test/api/runtime/RuntimeVariablesTest.java
Fixed the following issue.
https://github.com/Activiti/Activiti/issues/2010
> Fix issue 2010

- activiti-api-impl/activiti-api-task-runtime-impl/src/main/java/org/activiti/runtime/api/conf/TaskRuntimeAutoConfiguration.java
- activiti-api-impl/activiti-api-task-runtime-impl/src/main/java/org/activiti/runtime/api/event/impl/TaskUpdatedEventImpl.java
- activiti-api-impl/activiti-api-task-runtime-impl/src/main/java/org/activiti/runtime/api/event/impl/ToAPITaskUpdatedEventConverter.java
- activiti-api-impl/activiti-api-task-runtime-impl/src/main/java/org/activiti/runtime/api/event/internal/TaskUpdatedListenerDelegate.java
- activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/RuntimeTestConfiguration.java
- activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/tasks/TaskRuntimeUpdateTaskTest.java
-added listener delegate for TaskUpdate event
-created a test for this listener
refs [1991](https://github.com/Activiti/Activiti/issues/1991)
> ACTIVITI-1991 Task is not updated in Query

- activiti-spring-boot-starter/src/main/java/org/activiti/spring/boot/ActivitiProperties.java
- activiti-spring-boot-starter/src/main/java/org/activiti/spring/boot/ProcessDefinitionResourceFinder.java
- activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/ProcessDefinitionResourceFinderIT.java
- activiti-spring-boot-starter/src/test/resources/long/path/for/processes/categorize-human-long-path.bpmn20.xml
Can deploy at the same time processes located under
- /processes
- /any/path/to/processes
> Allow process deployment from different folder levels

- activiti-image-generator/src/main/java/org/activiti/image/impl/DefaultProcessDiagramCanvas.java
- activiti-image-generator/src/main/java/org/activiti/image/impl/DefaultProcessDiagramGenerator.java
> Add Transaction SubProcess Symbol

- activiti-api-impl/activiti-api-task-runtime-impl/src/main/java/org/activiti/runtime/api/event/impl/ToTaskCompletedConverter.java
- activiti-api-impl/activiti-api-task-runtime-impl/src/main/java/org/activiti/runtime/api/model/impl/APITaskConverter.java
- activiti-api-impl/activiti-api-task-runtime-impl/src/test/java/org/activiti/runtime/api/event/impl/ToTaskCompletedConverterTest.java
Instead of trying to infer the status, just set it to completed
> Fix task status for task completed event

- pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.core.common:activiti-core-common-dependencies` to: `7.0.5`
> update org.activiti.core.common:activiti-core-common-dependencies to 7.0.7

- activiti-api-impl/activiti-api-process-runtime-impl/src/main/java/org/activiti/runtime/api/model/impl/APIProcessDefinitionConverter.java
- activiti-api-impl/activiti-api-process-runtime-impl/src/main/java/org/conf/activiti/runtime/api/ProcessRuntimeAutoConfiguration.java
- activiti-api-impl/activiti-api-process-runtime-impl/src/test/java/org/activiti/runtime/api/model/impl/APIProcessDefinitionConverterTest.java
- activiti-api-impl/activiti-api-process-runtime-impl/src/test/java/org/activiti/runtime/api/model/impl/MockProcessDefinitionBuilder.java
- activiti-api-impl/activiti-api-task-runtime-impl/src/main/java/org/activiti/runtime/api/model/impl/APITaskConverter.java
- activiti-api-impl/activiti-api-task-runtime-impl/src/test/java/org/activiti/runtime/api/model/impl/APITaskConverterTest.java
- activiti-api-impl/activiti-api-task-runtime-impl/src/test/java/org/activiti/runtime/api/model/impl/MockTaskBuilder.java
- activiti-bpmn-model/src/main/java/org/activiti/bpmn/model/BpmnModel.java
#2082 
Depends on PR https://github.com/Activiti/activiti-api/pull/32
> Add form key to process definition and task models

- pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.api:activiti-api-dependencies` to: `7.0.36`
> update org.activiti.api:activiti-api-dependencies to 7.0.37

- pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.api:activiti-api-dependencies` to: `7.0.38`
> update org.activiti.api:activiti-api-dependencies to 7.0.38

- pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.core.common:activiti-core-common-dependencies` to: `7.0.8`
> update org.activiti.core.common:activiti-core-common-dependencies to 7.0.8

- activiti-engine/src/main/resources/org/activiti/db/mapping/entity/Task.xml
- activiti-engine/src/test/java/org/activiti/engine/test/api/task/TaskQueryTest.java
- activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/RuntimeTestConfiguration.java
- activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/tasks/TaskRuntimeClaimTaskFromProcessTest.java
- activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/tasks/TaskRuntimeTaskAssigneeTest.java
- activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/tasks/TaskVariablesLocalCopiesTest.java
- activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/test/util/ProcessCleanUpUtil.java
- activiti-spring-boot-starter/src/test/resources/processes/two-usertask-parallel.bpmn20.xml
fixes https://github.com/Activiti/Activiti/issues/2057
was tricky to recreate as needed to get the groups to null and not just empty and to use an or condition but now capturing with tests
> reproduce the db error and capture with test

- pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.api:activiti-api-dependencies` to: `7.0.39`
> update org.activiti.api:activiti-api-dependencies to 7.0.39

- activiti-api-impl/activiti-api-task-runtime-impl/src/main/java/org/activiti/runtime/api/impl/TaskRuntimeImpl.java
- activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/ProcessDefinitionFormKeyIT.java
- activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/tasks/TaskRuntimeFormKeyTest.java
- activiti-spring-boot-starter/src/test/resources/processes/SingleTaskProcess.bpmn20.xml
Related to #2082
Depends on https://github.com/Activiti/activiti-api/pull/34
> Allow updating task formKey

- activiti-spring-boot-starter/src/main/java/org/activiti/spring/boot/ActivitiProperties.java
Use ResourcePatternResolver.CLASSPATH_ALL_URL_PREFIX: this fix the issue about processes not getting deployed during tests when they are located under src/main/resources/processes
Refs https://github.com/Activiti/Activiti/issues/2140
> Update default processes location prefix

- pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.core.common:activiti-core-common-dependencies` to: `7.0.10`
> update org.activiti.core.common:activiti-core-common-dependencies to 7.0.13

- pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.api:activiti-api-dependencies` to: `7.0.40`
> update org.activiti.api:activiti-api-dependencies to 7.0.46

- pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.core.common:activiti-core-common-dependencies` to: `7.0.14`
> update org.activiti.core.common:activiti-core-common-dependencies to 7.0.15

- .updatebot.yml
> fix: (updatebot) use single pull request into activiti-dependencies

- pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.core.common:activiti-core-common-dependencies` to: `7.0.16`
> update org.activiti.core.common:activiti-core-common-dependencies to 7.0.17

- activiti-api-impl/activiti-api-task-runtime-impl/src/test/java/org/activiti/runtime/api/model/impl/APITaskConverterTest.java
- activiti-engine/pom.xml
- activiti-spring/pom.xml
- pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.build:activiti-parent` to: `7.0.41`
> update org.activiti.build:activiti-parent to 7.0.41

- pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.core.common:activiti-core-common-dependencies` to: `7.0.19`
> update org.activiti.core.common:activiti-core-common-dependencies to 7.0.19

- activiti-api-impl/activiti-api-process-runtime-impl/src/main/java/org/activiti/runtime/api/event/impl/ToSequenceFlowTakenConverter.java
Missing id for BPMN element fixed
> Missing id for BPMN element fixed

- activiti-api-impl/activiti-api-process-runtime-impl/src/main/java/org/activiti/runtime/api/event/impl/ToSequenceFlowTakenConverter.java
> Missing id for BPMNElement #2175

- activiti-api-impl/activiti-api-process-runtime-impl/src/main/java/org/activiti/runtime/api/event/impl/ProcessUpdatedEventImpl.java
- activiti-api-impl/activiti-api-process-runtime-impl/src/main/java/org/activiti/runtime/api/event/impl/ToProcessUpdatedConverter.java
- activiti-api-impl/activiti-api-process-runtime-impl/src/main/java/org/activiti/runtime/api/event/internal/ProcessUpdatedListenerDelegate.java
- activiti-api-impl/activiti-api-process-runtime-impl/src/main/java/org/conf/activiti/runtime/api/ProcessRuntimeAutoConfiguration.java
Update process instance properties via API #2147
First changes to avoid errors coming from https://github.com/Activiti/activiti-api/pull/54
> Update process instance properties via API #2147

- activiti-api-impl/activiti-api-process-runtime-impl/src/main/java/org/activiti/runtime/api/event/impl/ToSequenceFlowTakenConverter.java
- pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.core.common:activiti-core-common-dependencies` to: `7.0.20`
> update org.activiti.core.common:activiti-core-common-dependencies to 7.0.21

- pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.build:activiti-parent` to: `7.0.42`
> fix(versions): update Activiti/Activiti versions

- activiti-api-impl/activiti-api-process-runtime-impl/src/main/java/org/activiti/runtime/api/impl/ProcessAdminRuntimeImpl.java
- activiti-api-impl/activiti-api-process-runtime-impl/src/main/java/org/activiti/runtime/api/impl/ProcessRuntimeImpl.java
- activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/process/ProcessRuntimeTest.java
- pom.xml
Depends on Activiti/activiti-api#57
https://github.com/Activiti/activiti-api/pull/57
> Implementation of processInstance update, tests added

- activiti-api-impl/activiti-api-task-runtime-impl/src/main/java/org/activiti/runtime/api/impl/TaskRuntimeImpl.java
- activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/tasks/TaskRuntimeClaimReleaseTest.java
- activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/tasks/TaskRuntimeDeleteTaskTest.java
- activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/tasks/TaskRuntimeStandaloneTaskTest.java
- activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/tasks/TaskRuntimeTaskAssigneeTest.java
- activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/tasks/TaskRuntimeUnAuthorizedTest.java
- pom.xml
Adding small changes to support candidateUsers and Groups
> initial refactoring for candidateUsers and Groups

- activiti-engine/src/test/java/org/activiti/engine/test/bpmn/async/AsyncTaskTest.java
> Try fixing intermittent failing async tests

- activiti-api-impl/activiti-api-process-runtime-impl/src/main/java/org/conf/activiti/runtime/api/ProcessRuntimeAutoConfiguration.java
- activiti-api-impl/activiti-api-runtime-shared-impl/src/main/java/org/activiti/runtime/api/conf/CommonRuntimeAutoConfiguration.java
- activiti-api-impl/activiti-api-task-runtime-impl/src/main/java/org/activiti/runtime/api/conf/TaskRuntimeAutoConfiguration.java
> @Configuration classes using base Common config

- activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/RuntimeTestConfiguration.java
- activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/tasks/TaskRuntimeCandidatesTest.java
Related to Activiti/Activiti#2330
> Test updated to check userCandidate add/remove commands and events

- activiti-spring-conformance-tests/activiti-spring-conformance-set5/pom.xml
- activiti-spring-conformance-tests/activiti-spring-conformance-set5/src/test/java/org/activiti/spring/conformance/set5/Application.java
- activiti-spring-conformance-tests/activiti-spring-conformance-set5/src/test/java/org/activiti/spring/conformance/set5/BasicCallActivityAndServiceTaskTest.java
- activiti-spring-conformance-tests/activiti-spring-conformance-set5/src/test/java/org/activiti/spring/conformance/set5/BasicCallActivityTest.java
- activiti-spring-conformance-tests/activiti-spring-conformance-set5/src/test/java/org/activiti/spring/conformance/set5/ConformanceBasicProcessRuntimeTest.java
- activiti-spring-conformance-tests/activiti-spring-conformance-set5/src/test/java/org/activiti/spring/conformance/set5/Set5RuntimeTestConfiguration.java
- activiti-spring-conformance-tests/activiti-spring-conformance-set5/src/test/resources/processes/basic-call-activity-service-task.bpmn20.xml
- activiti-spring-conformance-tests/activiti-spring-conformance-set5/src/test/resources/processes/basic-call-activity.bpmn20.xml
- activiti-spring-conformance-tests/activiti-spring-conformance-set5/src/test/resources/processes/sub-process-a.bpmn20.xml
- activiti-spring-conformance-tests/activiti-spring-conformance-set5/src/test/resources/processes/sub-process-b.bpmn20.xml
- activiti-spring-conformance-tests/pom.xml
> conformance set5

- activiti-api-impl/activiti-api-task-runtime-impl/src/main/java/org/activiti/runtime/api/impl/TaskRuntimeImpl.java
- activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/tasks/TaskRuntimeCandidatesTest.java
- activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/tasks/TaskRuntimeFormKeyTest.java
- pom.xml
Related to Activiti/Activiti#2355
Depends on https://github.com/Activiti/activiti-api/pull/68
> UpdateTaskPayload: taskName changed to name

- .travis.yml
- Jenkinsfile
- activiti-engine/pom.xml
- activiti-spring/pom.xml
- pom.xml
Part of Activiti/Activiti#2076
> Open JDK 11 Support

- activiti-engine/src/main/java/org/activiti/engine/impl/el/JsonNodeELResolver.java
- activiti-engine/src/main/java/org/activiti/engine/impl/el/VariableScopeElResolver.java
- activiti-engine/src/test/java/org/activiti/engine/test/json/SerializePOJOJsonTest.java
- activiti-engine/src/test/resources/org/activiti/engine/test/json/SerializePOJOJsonTest.testCollectionInJsonVarInExpression.bpmn20.xml
- activiti-engine/src/test/resources/org/activiti/engine/test/json/SerializePOJOJsonTest.testCollectionJsonVarInExpression.bpmn20.xml
- activiti-engine/src/test/resources/org/activiti/engine/test/json/SerializePOJOJsonTest.testJsonVarInExpression.bpmn20.xml
- activiti-engine/src/test/resources/org/activiti/engine/test/json/SerializePOJOJsonTest.testPOJOCollectionInJsonVarInExpression.bpmn20.xml
- activiti-engine/src/test/resources/org/activiti/standalone/cfg/variable/custom-serialize-variables-activiti.cfg.xml
* `${userMap.customField}`
* `${userMap.mapInMap.customField}`
* `${CustomPOJO.customField}`
* `${userCollection}`
* `${userMap.userCollection}`
* `${userMap.userCollection.get(0).value}`
* `${CustomPOJO.customMethod()}`
> Handling expressions for json variables

- activiti-api-impl/activiti-api-task-runtime-impl/src/main/java/org/activiti/runtime/api/conf/TaskRuntimeAutoConfiguration.java
- activiti-api-impl/activiti-api-task-runtime-impl/src/main/java/org/activiti/runtime/api/impl/TaskAdminRuntimeImpl.java
- activiti-api-impl/activiti-api-task-runtime-impl/src/main/java/org/activiti/runtime/api/impl/TaskRuntimeHelper.java
- activiti-api-impl/activiti-api-task-runtime-impl/src/main/java/org/activiti/runtime/api/impl/TaskRuntimeImpl.java
- activiti-api-impl/activiti-api-task-runtime-impl/src/main/java/org/activiti/runtime/api/impl/TaskUpdater.java
- activiti-api-impl/activiti-api-task-runtime-impl/src/test/java/org/activiti/runtime/api/impl/TaskRuntimeHelperTest.java
- activiti-api-impl/activiti-api-task-runtime-impl/src/test/java/org/activiti/runtime/api/impl/TaskRuntimeImplTest.java
- activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/tasks/TaskRuntimeUpdateTaskTest.java
Related to https://github.com/Activiti/Activiti/issues/2372
Depends on https://github.com/Activiti/activiti-api/pull/75
> Update task is implemented for TaskAdminRuntimeImpl

- activiti-api-impl/activiti-api-process-runtime-impl/src/main/java/org/activiti/runtime/api/impl/ProcessAdminRuntimeImpl.java
- activiti-api-impl/activiti-api-process-runtime-impl/src/main/java/org/activiti/runtime/api/impl/ProcessRuntimeImpl.java
- activiti-api-impl/activiti-api-process-runtime-impl/src/test/java/org/activiti/runtime/api/impl/ProcessRuntimeImplTest.java
- activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/process/ProcessRuntimeTest.java
- activiti-spring-conformance-tests/activiti-spring-conformance-set0/src/test/java/org/activiti/spring/conformance/set0/ConformanceBasicGenericTaskTest.java
- activiti-spring-conformance-tests/activiti-spring-conformance-set0/src/test/java/org/activiti/spring/conformance/set0/ConformanceBasicProcessInformationTest.java
- activiti-spring-conformance-tests/activiti-spring-conformance-set0/src/test/java/org/activiti/spring/conformance/set0/ProcessInstanceOperationsTest.java
- activiti-spring-conformance-tests/activiti-spring-conformance-set1/src/test/java/org/activiti/spring/conformance/set1/ConformanceServiceTaskModifyVariableTest.java
- activiti-spring-conformance-tests/activiti-spring-conformance-set1/src/test/java/org/activiti/spring/conformance/set1/ConformanceServiceTaskTest.java
- activiti-spring-conformance-tests/activiti-spring-conformance-set2/src/test/java/org/activiti/spring/conformance/set2/UserTaskAssigneeDeleteRuntimeTest.java
- activiti-spring-conformance-tests/activiti-spring-conformance-set2/src/test/java/org/activiti/spring/conformance/set2/UserTaskAssigneeRuntimeTest.java
- activiti-spring-conformance-tests/activiti-spring-conformance-set2/src/test/java/org/activiti/spring/conformance/set2/UserTaskCandidateDeleteRuntimeTest.java
- activiti-spring-conformance-tests/activiti-spring-conformance-set2/src/test/java/org/activiti/spring/conformance/set2/UserTaskCandidateGroupRuntimeTest.java
- activiti-spring-conformance-tests/activiti-spring-conformance-set2/src/test/java/org/activiti/spring/conformance/set2/UserTaskCandidateUserRuntimeTest.java
- activiti-spring-conformance-tests/activiti-spring-conformance-set2/src/test/java/org/activiti/spring/conformance/set2/UserTaskNoCandidateRuntimeTest.java
- activiti-spring-conformance-tests/activiti-spring-conformance-set3/src/test/java/org/activiti/spring/conformance/set3/UserTaskCandidateGroupAndAssigneeTest.java
- activiti-spring-conformance-tests/activiti-spring-conformance-set3/src/test/java/org/activiti/spring/conformance/set3/UserTaskCandidateGroupsTest.java
- activiti-spring-conformance-tests/activiti-spring-conformance-set3/src/test/java/org/activiti/spring/conformance/set3/UserTaskCandidateVisibilityTest.java
- activiti-spring-conformance-tests/activiti-spring-conformance-set4/src/test/java/org/activiti/spring/conformance/set4/BasicExclusiveGatewayErrorTest.java
- activiti-spring-conformance-tests/activiti-spring-conformance-set4/src/test/java/org/activiti/spring/conformance/set4/BasicExclusiveGatewayTest.java
- activiti-spring-conformance-tests/activiti-spring-conformance-set4/src/test/java/org/activiti/spring/conformance/set4/BasicParallelGatewayGroupAssignmentsTest.java
- activiti-spring-conformance-tests/activiti-spring-conformance-set4/src/test/java/org/activiti/spring/conformance/set4/BasicParallelGatewayTest.java
- activiti-spring-conformance-tests/activiti-spring-conformance-set5/src/test/java/org/activiti/spring/conformance/set5/BasicCallActivityAndServiceTaskTest.java
- activiti-spring-conformance-tests/activiti-spring-conformance-set5/src/test/java/org/activiti/spring/conformance/set5/BasicCallActivityTest.java
- pom.xml
Related to https://github.com/Activiti/Activiti/issues/2393
Depends on https://github.com/Activiti/activiti-api/pull/78
> Refactoring for UpdateProcessPayload and StartProcessPayload

- activiti-api-impl/activiti-api-task-runtime-impl/src/main/java/org/activiti/runtime/api/impl/TaskRuntimeImpl.java
- activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/tasks/TaskRuntimeStandaloneTaskTest.java
Related to https://github.com/Activiti/Activiti/issues/1953
> Task name required when creating a task

- activiti-engine/pom.xml
- activiti-spring-conformance-tests/activiti-spring-conformance-variables/pom.xml
- activiti-spring-conformance-tests/activiti-spring-conformance-variables/src/test/java/org/activiti/spring/conformance/variables/Application.java
- activiti-spring-conformance-tests/activiti-spring-conformance-variables/src/test/java/org/activiti/spring/conformance/variables/ProcessVariablesTest.java
- activiti-spring-conformance-tests/activiti-spring-conformance-variables/src/test/java/org/activiti/spring/conformance/variables/TaskVariablesTest.java
- activiti-spring-conformance-tests/activiti-spring-conformance-variables/src/test/java/org/activiti/spring/conformance/variables/VariablesRuntimeTestConfiguration.java
- activiti-spring-conformance-tests/activiti-spring-conformance-variables/src/test/resources/processes/user-task-assignee-followed-group1.bpmn20.xml
- activiti-spring-conformance-tests/activiti-spring-conformance-variables/src/test/resources/processes/user-task-candidate-group.bpmn20.xml
- activiti-spring-conformance-tests/activiti-spring-conformance-variables/src/test/resources/processes/user-task-group1-followed-group2.bpmn20.xml
- activiti-spring-conformance-tests/pom.xml
Addressing this issue:  https://github.com/Activiti/Activiti/issues/2338
> Variables conformance tests

- activiti-api-impl/activiti-api-process-runtime-impl/src/main/java/org/activiti/runtime/api/connector/IntegrationContextBuilder.java
- activiti-api-impl/activiti-api-process-runtime-impl/src/test/java/org/activiti/runtime/api/connector/IntegrationContextBuilderTest.java
- activiti-spring-conformance-tests/activiti-spring-conformance-set1/src/test/java/org/activiti/spring/conformance/set1/ConformanceServiceTaskTest.java
- pom.xml
Related to https://github.com/Activiti/Activiti/issues/2381
Depends on https://github.com/Activiti/activiti-api/pull/79
> Fields added to IntegrationContext

- activiti-spring-boot-starter/src/main/java/org/activiti/spring/ProcessDeployedEventProducer.java
- activiti-spring-boot-starter/src/main/java/org/activiti/spring/boot/ProcessEngineAutoConfiguration.java
- activiti-spring-boot-starter/src/test/java/org/activiti/spring/ProcessDeployedEventProducerTest.java
- activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/process/DeployedProcessesListener.java
- activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/process/ProcessDeployedEventIT.java
Related to https://github.com/Activiti/Activiti/issues/2389
> Publish process model as part of ProcessDeployedEvent

- activiti-api-impl/activiti-api-task-runtime-impl/src/main/java/org/activiti/runtime/api/conf/TaskRuntimeAutoConfiguration.java
- activiti-api-impl/activiti-api-task-runtime-impl/src/main/java/org/activiti/runtime/api/impl/TaskAdminRuntimeImpl.java
- activiti-api-impl/activiti-api-task-runtime-impl/src/main/java/org/activiti/runtime/api/impl/TaskRuntimeHelper.java
- activiti-api-impl/activiti-api-task-runtime-impl/src/main/java/org/activiti/runtime/api/impl/TaskRuntimeImpl.java
- activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/tasks/TaskVariablesLocalCopiesTest.java
- activiti-spring-conformance-tests/activiti-spring-conformance-variables/src/test/java/org/activiti/spring/conformance/variables/TaskVariablesTest.java
- pom.xml
Related to https://github.com/Activiti/Activiti/issues/2515
Depends on https://github.com/Activiti/activiti-api/pull/100
> Method to get task variables by admin is implemented

- pom.xml
[UpdateBot](https://github.com/jenkins-x/updatebot) pushed maven dependency: `org.activiti.build:activiti-parent` to: `7.1.14`
> fix(versions): update Activiti/Activiti versions into develop

- activiti-api-impl/activiti-api-task-runtime-impl/src/main/java/org/activiti/runtime/api/event/impl/TaskCreatedEventImpl.java
- activiti-api-impl/activiti-api-task-runtime-impl/src/main/java/org/activiti/runtime/api/event/impl/ToAPITaskCreatedEventConverter.java
- activiti-api-impl/activiti-api-task-runtime-impl/src/main/java/org/activiti/runtime/api/model/impl/APITaskConverter.java
Reverts Activiti/Activiti#2678
> Revert "ProcessDefinitionVersion support for TaskCreatedEvent"

- activiti-bpmn-converter/src/main/java/org/activiti/bpmn/converter/ServiceTaskXMLConverter.java
- activiti-bpmn-converter/src/test/java/org/activiti/bpmn/converter/ServiceTaskXMLConverterTest.java
2680 add default behavior for writing the "implementation" attribute of the "serviceTask" xml element
https://github.com/Activiti/Activiti/issues/2680
> 2680 add default behavior for writing the "implementation" attribute of the "serviceTask" xml element

- activiti-bpmn-converter/src/main/java/org/activiti/bpmn/converter/ServiceTaskXMLConverter.java
- activiti-bpmn-converter/src/test/java/org/activiti/bpmn/converter/ServiceTaskXMLConverterTest.java
2680 set 'implementation' attibute namewithout qualifier on service task xml element
> 2680 set 'implementation' attibute namewithout qualifier on service task xml element

- activiti-api-impl/activiti-api-process-runtime-impl/src/main/java/org/activiti/runtime/api/connector/InboundVariableValueProvider.java
- activiti-api-impl/activiti-api-process-runtime-impl/src/main/java/org/activiti/runtime/api/connector/InboundVariablesProvider.java
- activiti-api-impl/activiti-api-process-runtime-impl/src/test/java/org/activiti/runtime/api/connector/InboundVariableValueProviderTest.java
- activiti-api-impl/activiti-api-process-runtime-impl/src/test/java/org/activiti/runtime/api/connector/InboundVariablesProviderTest.java
- activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/RuntimeTestConfiguration.java
- activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/process/ConnectorsConfiguration.java
- activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/process/ProcessRuntimeConnectorIT.java
- activiti-spring-boot-starter/src/test/resources/processes/process-with-extensions-but-no-connector-def-extensions.json
- activiti-spring-boot-starter/src/test/resources/processes/process-with-extensions-but-no-connector-def.bpmn20.xml
- activiti-spring-boot-starter/src/test/resources/processes/variable-mapping-extensions.json
- activiti-spring-process-extensions/src/main/java/org/activiti/spring/process/model/Mapping.java
> #2694 static values inputs for connectors

- activiti-api-impl/activiti-api-task-runtime-impl/src/main/java/org/activiti/runtime/api/conf/TaskRuntimeAutoConfiguration.java
- activiti-api-impl/activiti-api-task-runtime-impl/src/main/java/org/activiti/runtime/api/impl/TaskAdminRuntimeImpl.java
- activiti-api-impl/activiti-api-task-runtime-impl/src/main/java/org/activiti/runtime/api/impl/TaskRuntimeImpl.java
- activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/tasks/TaskRuntimeDeleteTaskTest.java
- activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/tasks/TaskRuntimeStandaloneTaskTest.java
- activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/tasks/TaskRuntimeTaskAssigneeTest.java
Addressing this issue:
https://github.com/Activiti/Activiti/issues/2462
> Change status for deleted tasks

- activiti-api-impl/activiti-api-process-runtime-impl/src/main/java/org/activiti/runtime/api/connector/IntegrationContextBuilder.java
- activiti-api-impl/activiti-api-process-runtime-impl/src/test/java/org/activiti/runtime/api/connector/IntegrationContextBuilderTest.java
Part of https://github.com/Activiti/Activiti/issues/2736
> fix: set process definition version and key for integration request

- activiti-api-impl/activiti-api-task-runtime-impl/src/main/java/org/activiti/runtime/api/impl/TaskRuntimeImpl.java
- activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/tasks/TaskRuntimeCompleteTaskTest.java
Related to https://github.com/Activiti/Activiti/issues/2756
> Refactoring task complete in order to get more info

- activiti-api-impl/activiti-api-process-runtime-impl/src/main/java/org/activiti/runtime/api/connector/InboundVariableValueProvider.java
- activiti-api-impl/activiti-api-process-runtime-impl/src/main/java/org/activiti/runtime/api/connector/OutboundVariablesProvider.java
- activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/RuntimeTestConfiguration.java
- activiti-spring-boot-starter/src/test/resources/processes/variable-mapping-extensions.json
- activiti-spring-process-extensions/src/main/java/org/activiti/spring/process/model/Extension.java
- activiti-spring-process-extensions/src/main/java/org/activiti/spring/process/model/ProcessVariablesMapping.java
- activiti-spring-process-extensions/src/test/resources/processes/variable-mapping-extensions.json
Related to https://github.com/Activiti/Activiti/issues/2529
> Deal with names vs UUIDs in connectors and variable mappings

- activiti-spring-conformance-tests/activiti-spring-conformance-set0/src/test/java/org/activiti/spring/conformance/set0/ConformanceBasicProcessRuntimeTest.java
- activiti-spring-conformance-tests/activiti-spring-conformance-set3/pom.xml
- activiti-spring-conformance-tests/activiti-spring-conformance-set3/src/test/java/org/activiti/spring/conformance/set3/ConformanceBasicProcessRuntimeTest.java
- activiti-spring-conformance-tests/activiti-spring-conformance-set3/src/test/java/org/activiti/spring/conformance/set3/UserTaskCandidateGroupAndAssigneeTest.java
- activiti-spring-conformance-tests/pom.xml
- Related to https://github.com/Activiti/Activiti/issues/2734
- Depends on https://github.com/Activiti/activiti-core-common/pull/91
> Use assertions library for conformance tests

- activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/tasks/TaskRuntimeStandaloneTaskTest.java
https://issues.alfresco.com/jira/browse/ACTIVITI-2849
> ACTIVITI-2849 modified 2 tests for standalone task

- activiti-spring-boot-starter/src/main/java/org/activiti/spring/boot/ProcessEngineAutoConfiguration.java
- Allow override this bean in runtime bundle
> Use named bean for behaviorFactoryConfigurer

- activiti-engine/src/main/java/org/activiti/engine/impl/bpmn/behavior/CallActivityBehavior.java
- activiti-engine/src/test/java/org/activiti/engine/test/api/event/VariableEventsTest.java
- activiti-engine/src/test/java/org/activiti/engine/test/bpmn/callactivity/CallActivityAdvancedTest.java
- activiti-engine/src/test/java/org/activiti/engine/test/bpmn/event/error/mapError/BoundaryErrorMapTest.java
- activiti-engine/src/test/java/org/activiti/engine/test/bpmn/multiinstance/MultiInstanceTest.java
- activiti-engine/src/test/resources/org/activiti/engine/test/api/tenant/TenancyTest.testCallActivityWithTenant-process02.bpmn20.xml
remove support for  extensionElements like
<callActivity id="callactivity1" name="Call activity" calledElement="process2">
<extensionElements>
<activiti:in source="sendFor" target="sendFor" />
</extensionElements>
</callActivity>
> extension remove from call activity

- activiti-api-impl/activiti-api-process-runtime-impl/src/main/java/org/activiti/runtime/api/impl/VariablesMappingProvider.java
- activiti-api-impl/activiti-api-process-runtime-impl/src/test/java/org/activiti/runtime/api/impl/VariablesMappingProviderTest.java
- activiti-api-impl/activiti-api-process-runtime-impl/src/test/resources/task-variable-empty-mapping-with-constants-extensions.json
Decoupling logic for constants and variable mapping
> ACTIVITI-3408 VariableMappingProvider refactoring

- activiti-api-impl/activiti-api-process-runtime-impl/src/main/java/org/activiti/runtime/api/conf/ProcessRuntimeAutoConfiguration.java
- activiti-api-impl/activiti-api-process-runtime-impl/src/main/java/org/activiti/runtime/api/event/impl/BPMNMessageConverter.java
- activiti-api-impl/activiti-api-process-runtime-impl/src/main/java/org/activiti/runtime/api/event/impl/ToMessageReceivedConverter.java
- activiti-api-impl/activiti-api-process-runtime-impl/src/main/java/org/activiti/runtime/api/event/impl/ToMessageSentConverter.java
- activiti-api-impl/activiti-api-process-runtime-impl/src/main/java/org/activiti/runtime/api/event/impl/ToMessageWaitingConverter.java
- activiti-api-impl/activiti-api-process-runtime-impl/src/main/java/org/activiti/runtime/api/event/internal/MessageReceivedListenerDelegate.java
- activiti-api-impl/activiti-api-process-runtime-impl/src/main/java/org/activiti/runtime/api/event/internal/MessageSentListenerDelegate.java
- activiti-api-impl/activiti-api-process-runtime-impl/src/main/java/org/activiti/runtime/api/event/internal/MessageWaitingListenerDelegate.java
- activiti-api-impl/activiti-api-process-runtime-impl/src/test/java/org/activiti/runtime/api/event/impl/BPMNMessageConverterTest.java
- activiti-api-impl/activiti-api-process-runtime-impl/src/test/java/org/activiti/runtime/api/event/impl/ToMessageReceivedConverterTest.java
- activiti-api-impl/activiti-api-process-runtime-impl/src/test/java/org/activiti/runtime/api/event/impl/ToMessageSentConverterTest.java
- activiti-api-impl/activiti-api-process-runtime-impl/src/test/java/org/activiti/runtime/api/event/impl/ToMessageWaitingConverterTest.java
- activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/MessageTestConfiguration.java
- activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/process/ProcessRuntimeBPMNMessageIT.java
Related to https://github.com/Activiti/Activiti/issues/2637
> Support for BPMN message events

- activiti-api-impl/activiti-api-process-runtime-impl/src/main/java/org/activiti/runtime/api/conf/ProcessRuntimeAutoConfiguration.java
- activiti-api-impl/activiti-api-process-runtime-impl/src/main/java/org/activiti/runtime/api/event/impl/BPMNErrorConverter.java
- activiti-api-impl/activiti-api-process-runtime-impl/src/main/java/org/activiti/runtime/api/event/impl/ToErrorReceivedConverter.java
- activiti-api-impl/activiti-api-process-runtime-impl/src/main/java/org/activiti/runtime/api/event/internal/ErrorReceivedListenerDelegate.java
- activiti-api-impl/activiti-api-process-runtime-impl/src/test/java/org/activiti/runtime/api/event/impl/BPMNErrorConverterTest.java
- activiti-api-impl/activiti-api-process-runtime-impl/src/test/java/org/activiti/runtime/api/event/impl/ToErrorReceivedConverterTest.java
- activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/process/ProcessRuntimeBPMNErrorReceivedIT.java
- activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/process/listener/DummyBPMNErrorReceivedListener.java
- activiti-spring-boot-starter/src/test/resources/processes/simpleSubProcessErrorEvent.bpmn20.xml
- activiti-spring-boot-starter/src/test/resources/processes/testErrorBoundaryEventCallActivity.bpmn20.xml
- activiti-spring-boot-starter/src/test/resources/processes/testErrorBoundaryEventSubProcess.bpmn20.xml
- activiti-spring-boot-starter/src/test/resources/processes/testErrorStartEventSubProcess.bpmn20.xml
Related to https://github.com/Activiti/Activiti/issues/2743
> ACTIVITI-2743 Implementation of Error Events

- activiti-bpmn-converter/src/main/java/org/activiti/bpmn/converter/StartEventXMLConverter.java
ACTIVITI-3917 remove activiti: qualifier to the isInterrupting attribute for startEvent element
> ACTIVITI-3917 remove activiti: qualifier to the isInterrupting attribute for startEvent element

- activiti-bpmn-converter/src/main/java/org/activiti/bpmn/converter/CallActivityXMLConverter.java
> remove adding default inheritVariables tag

- .gitignore
- activiti-api-impl/activiti-api-task-runtime-impl/src/main/java/org/activiti/runtime/api/conf/TaskRuntimeAutoConfiguration.java
- activiti-api-impl/activiti-api-task-runtime-impl/src/main/java/org/activiti/runtime/api/impl/TaskRuntimeHelper.java
- activiti-api-impl/activiti-api-task-runtime-impl/src/main/java/org/activiti/runtime/api/impl/TaskRuntimeImpl.java
- activiti-api-impl/activiti-api-task-runtime-impl/src/test/java/org/activiti/runtime/api/impl/TaskRuntimeHelperTest.java
- pom.xml
This PR refactors TaskRuntime implementation to use extended SecurityManager groups Apis from https://github.com/Activiti/activiti-api/pull/124
Depends on https://github.com/Activiti/activiti-core-common/pull/123
Part of https://github.com/Activiti/Activiti/issues/2765
> fix(AAE-201): Refactored TaskRuntime implementation to use extended SecurityManager groups Apis

- activiti-bpmn-converter/src/main/java/org/activiti/bpmn/converter/EndEventXMLConverter.java
- activiti-bpmn-converter/src/test/java/org/activiti/editor/language/xml/EndEventConverterTest.java
- activiti-bpmn-converter/src/test/resources/end-error-event.bpmn20.xml
Fix EndEventXMLConverter (order of elements)
> AAE-685 fix EndEventXMLConverter

- activiti-api-impl/activiti-api-process-runtime-impl/src/test/java/org/activiti/runtime/api/impl/ProcessVariablesPayloadValidatorTest.java
- activiti-api-impl/activiti-api-task-runtime-impl/src/test/java/org/activiti/runtime/api/impl/TaskVariablesPayloadValidatorTest.java
Refactoring of tests for process / task variable validators (moved from runtime bundle)
Tests related to changes here:
https://github.com/Activiti/Activiti/pull/2947
> AAE-105 refactoring of test for process / task validators

- activiti-bpmn-model/src/main/java/org/activiti/bpmn/model/AcceptUpdates.java
- activiti-bpmn-model/src/main/java/org/activiti/bpmn/model/CallActivity.java
- activiti-bpmn-model/src/main/java/org/activiti/bpmn/model/FlowElement.java
- activiti-bpmn-model/src/main/java/org/activiti/bpmn/model/FlowNode.java
- activiti-bpmn-model/src/main/java/org/activiti/bpmn/model/ReferenceOverrider.java
- activiti-bpmn-model/src/main/java/org/activiti/bpmn/model/StartEvent.java
- activiti-bpmn-model/src/main/java/org/activiti/bpmn/model/UserTask.java
Part of addressing this issue: https://issues.alfresco.com/jira/browse/AAE-705
> AAE-705: Added interface to override id references

- activiti-bpmn-converter/src/main/java/org/activiti/bpmn/converter/CatchEventXMLConverter.java
- activiti-bpmn-converter/src/main/java/org/activiti/bpmn/converter/ThrowEventXMLConverter.java
- activiti-bpmn-converter/src/test/java/org/activiti/editor/language/xml/IntermediateThrowCatchSignalEventConverterTest.java
- activiti-bpmn-converter/src/test/resources/intermediate-throw-catch-signal-event.bpmn20.xml
Add to the sections for definition of IntermediateThrowEvent, IntermediateCatchEvent incoming and outgoing elements
> AAE-729 fix CatchEventXMLConverter, ThrowEventXMLConverter, test

- activiti-engine/src/main/java/org/activiti/engine/impl/cmd/DeployCmd.java
https://issues.alfresco.com/jira/browse/ACTIVITI-4012
> fix for null pointer in example-runtime-bundle

- activiti-spring-boot-starter/src/main/java/org/activiti/spring/boot/ProcessEngineAutoConfiguration.java
default value to process definition dir
> AAE-833 extension prefix default to process definition dir

- activiti-engine/src/main/java/org/activiti/engine/impl/bpmn/behavior/EventSubProcessMessageStartEventActivityBehavior.java
- activiti-engine/src/test/java/org/activiti/engine/test/api/event/ActivityEventsTest.java
- activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/process/ProcessRuntimeBPMNMessageIT.java
- activiti-spring-boot-starter/src/test/resources/processes/ProcessRuntimeBPMNMessageIT.interrupting-eventSubprocess.bpmn20.xml
- activiti-spring-boot-starter/src/test/resources/processes/ProcessRuntimeBPMNMessageIT.nonInterrupting-eventSubprocess.bpmn20.xml
fixes https://github.com/Activiti/Activiti/issues/2980
> [AAE-94] Tasks cancelled by Start Message Event are not updated in query service

- pom.xml
Replaces https://github.com/Activiti/Activiti/pull/2990 that got closed accidentally
> Propagate versions

- activiti-spring/src/main/java/org/activiti/spring/SpringProcessEngineConfiguration.java
- activiti-spring/src/test/java/org/activiti/spring/test/email/JndiEmailTest.java
- activiti-spring/src/test/java/org/activiti/spring/test/executionListener/ExecutionListenerOnTransactionTest.java
- activiti-spring/src/test/java/org/activiti/spring/test/expression/SpringLimitedExpressionsTest.java
- activiti-spring/src/test/java/org/activiti/spring/test/expression/callactivity/CallActivityBasedOnSpringBeansExpressionTest.java
- activiti-spring/src/test/java/org/activiti/spring/test/fieldinjection/ListenerFieldInjectionTest.java
- activiti-spring/src/test/java/org/activiti/spring/test/servicetask/BoundaryErrorEventSpringTest.java
- activiti-spring/src/test/java/org/activiti/spring/test/servicetask/ServiceTaskSpringDelegationTest.java
- activiti-spring/src/test/java/org/activiti/spring/test/taskListener/TaskListenerSpringTest.java
- activiti-spring/src/test/java/org/activiti/spring/test/taskassignment/CustomTaskAssignmentTest.java
- activiti-spring/src/test/java/org/activiti/spring/test/transaction/SpringTransactionIntegrationTest.java
> [AAE-934] remove resource check before setting strategy

- activiti-api-impl/activiti-api-process-runtime-impl/src/main/java/org/activiti/runtime/api/impl/ProcessVariablesPayloadValidator.java
- activiti-api-impl/activiti-api-process-runtime-impl/src/test/java/org/activiti/runtime/api/impl/ProcessVariablesPayloadValidatorTest.java
- activiti-spring-process-extensions/src/main/java/org/activiti/spring/process/conf/ProcessExtensionsAutoConfiguration.java
> [AAE-851] Add Datetime to list of selectable variable types

- activiti-api-impl/activiti-api-task-runtime-impl/src/main/java/org/activiti/runtime/api/model/impl/APITaskConverter.java
- activiti-api-impl/activiti-api-task-runtime-impl/src/test/java/org/activiti/runtime/api/model/impl/APITaskConverterTest.java
- activiti-api-impl/activiti-api-task-runtime-impl/src/test/java/org/activiti/runtime/api/model/impl/MockTaskBuilder.java
- activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/tasks/TaskRuntimeClaimReleaseTest.java
- activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/tasks/TaskRuntimeClaimTaskFromProcessTest.java
- activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/tasks/TaskRuntimeFormKeyTest.java
- activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/tasks/TaskRuntimeMultiInstanceIT.java
Related to https://github.com/Activiti/Activiti/issues/2766
Depends on https://github.com/Activiti/activiti-api/pull/126
> AAE-771 Support taskDefinitionKey in the Task model 

- activiti-api/activiti-api-process-model-impl/src/main/java/org/activiti/api/runtime/model/impl/IntegrationContextImpl.java
- activiti-api/activiti-api-process-model/src/main/java/org/activiti/api/process/model/IntegrationContext.java
- activiti-core/activiti-api-impl/activiti-api-process-runtime-impl/src/main/java/org/activiti/runtime/api/connector/IntegrationContextBuilder.java
Part of this issue: https://issues.alfresco.com/jira/browse/AAE-82
> Add appVersion to IntegrationContext

- activiti-core/activiti-api-impl/activiti-api-process-runtime-impl/src/main/java/org/activiti/runtime/api/impl/ProcessRuntimeImpl.java
- activiti-core/activiti-api-impl/activiti-api-process-runtime-impl/src/test/java/org/activiti/runtime/api/impl/ProcessRuntimeImplTest.java
- activiti-core/activiti-spring-conformance-tests/activiti-spring-conformance-set0/src/test/resources/default-app.json
- activiti-core/activiti-spring-conformance-tests/activiti-spring-conformance-set1/src/test/resources/default-app.json
- activiti-core/activiti-spring-conformance-tests/activiti-spring-conformance-set2/src/test/resources/default-app.json
- activiti-core/activiti-spring-conformance-tests/activiti-spring-conformance-set3/src/test/resources/default-app.json
- activiti-core/activiti-spring-conformance-tests/activiti-spring-conformance-set4/src/test/resources/default-app.json
- activiti-core/activiti-spring-conformance-tests/activiti-spring-conformance-set5/src/test/resources/default-app.json
- activiti-core/activiti-spring-conformance-tests/activiti-spring-conformance-signals/src/test/resources/default-app.json
- activiti-core/activiti-spring-conformance-tests/activiti-spring-conformance-variables/src/test/resources/default-app.json
- activiti-examples/activiti-api-basic-connector-example/src/test/resources/default-app.json
- activiti-examples/activiti-api-basic-process-example/src/test/resources/default-app.json
Addressing this issue: https://issues.alfresco.com/jira/browse/AAE-1243
> AAE-1243 Add version check before starting a process

- activiti-api/activiti-api-process-model/src/main/java/org/activiti/api/process/model/ProcessInstance.java
- activiti-core/activiti-api-impl/activiti-api-process-runtime-impl/src/main/java/org/activiti/runtime/api/impl/ProcessAdminRuntimeImpl.java
- activiti-core/activiti-api-impl/activiti-api-process-runtime-impl/src/main/java/org/activiti/runtime/api/impl/ProcessRuntimeImpl.java
- activiti-core/activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/process/ProcessRuntimeIT.java
- activiti-core/activiti-spring-conformance-tests/activiti-spring-conformance-set0/src/test/java/org/activiti/spring/conformance/set0/ProcessInstanceOperationsTest.java
https://issues.alfresco.com/jira/browse/AAE-1256
> [AAE-1256] Modify process status from DELETED to CANCELLED

- activiti-core/activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/tasks/TaskRuntimeMultiInstanceIT.java
Move assertions related to the timer execution inside await block, as they are asynchronous. This should fix the test TaskRuntimeMultiInstanceIT.processWithParallelMultiInstancesOnUserTask_Boundary_Event that's falling randomly.
> AAE-718 fix random test failure on multi-instances

- activiti-dependency-check/dependency-check-suppression.xml
- pom.xml
> Update to Spring Boot 2.1.12.RELEASE

- activiti-core/activiti-engine/src/main/resources/org/activiti/db/mapping/entity/ProcessDefinition.xml
in case of oracle bulk configuration is used have to add additional mapping 
https://issues.alfresco.com/jira/browse/AAE-1511
> bulk mapping updated, fix for https://issues.alfresco.com/jira/browse/AAE-1511

- .updatebot.yml
add activiti-cloud-build to updatebot
> add activiti-cloud-build to updatebot

- activiti-api/activiti-api-runtime-shared/src/main/java/org/activiti/api/runtime/shared/UnprocessableEntityException.java
- activiti-api/activiti-api-runtime-shared/src/main/java/org/activiti/api/runtime/shared/UnprocessableEntryException.java
- activiti-core/activiti-api-impl/activiti-api-process-runtime-impl/src/main/java/org/activiti/runtime/api/impl/ProcessRuntimeImpl.java
- activiti-core/activiti-api-impl/activiti-api-process-runtime-impl/src/test/java/org/activiti/runtime/api/impl/ProcessRuntimeImplTest.java
> fix: throw unprocessable entry exception when process doesn't belongs to latest deployment

- activiti-api/activiti-api-task-model/src/main/java/org/activiti/api/task/model/Task.java
- activiti-core/activiti-api-impl/activiti-api-task-model-impl/src/main/java/org/activiti/api/task/model/impl/TaskImpl.java
- activiti-core/activiti-api-impl/activiti-api-task-runtime-impl/src/test/java/org/activiti/runtime/api/impl/TaskRuntimeImplTest.java
- activiti-core/activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/tasks/TaskRuntimeCandidatesTest.java
Only the implementation need to handle the candidate fields
> AAE-944 remove information from the interface

- activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/persistence/entity/ExecutionEntityManagerImpl.java
> bugfix: populate appVersion for child executions

- activiti-core/activiti-engine/src/test/java/org/activiti/engine/impl/persistence/entity/ExecutionEntityManagerImplTest.java
Tests for create process instance, sub process, child process.
Closes AAE-1603, AAE-1600
> test: create with correct state and version executions

- activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/el/ExpressionManager.java
- activiti-core/activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/RuntimeTestConfiguration.java
- activiti-core/activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/process/ProcessRuntimeVariableMappingTest.java
- activiti-core/activiti-spring-boot-starter/src/test/resources/processes/output-mapping-expression-value-extensions.json
In addition to MapResolver, other base resolver should be included as well, i.e. ListELResolver, JsonNodeELResolver
> AAE-1665 Add missing ElResolvers to output mapping expressions

- activiti-core/activiti-bpmn-converter/src/main/java/org/activiti/bpmn/converter/BaseBpmnXMLConverter.java
- activiti-core/activiti-bpmn-converter/src/main/java/org/activiti/bpmn/converter/CatchEventXMLConverter.java
- activiti-core/activiti-bpmn-converter/src/main/java/org/activiti/bpmn/converter/EndEventXMLConverter.java
- activiti-core/activiti-bpmn-converter/src/main/java/org/activiti/bpmn/converter/ExclusiveGatewayXMLConverter.java
- activiti-core/activiti-bpmn-converter/src/main/java/org/activiti/bpmn/converter/InclusiveGatewayXMLConverter.java
- activiti-core/activiti-bpmn-converter/src/main/java/org/activiti/bpmn/converter/ManualTaskXMLConverter.java
- activiti-core/activiti-bpmn-converter/src/main/java/org/activiti/bpmn/converter/ParallelGatewayXMLConverter.java
- activiti-core/activiti-bpmn-converter/src/main/java/org/activiti/bpmn/converter/StartEventXMLConverter.java
- activiti-core/activiti-bpmn-converter/src/main/java/org/activiti/bpmn/converter/TaskXMLConverter.java
- activiti-core/activiti-bpmn-converter/src/main/java/org/activiti/bpmn/converter/ThrowEventXMLConverter.java
- activiti-core/activiti-bpmn-converter/src/main/java/org/activiti/bpmn/converter/UserTaskXMLConverter.java
- activiti-core/activiti-bpmn-converter/src/test/java/org/activiti/editor/language/xml/MultiInstanceUserTaskConverterTest.java
- activiti-core/activiti-bpmn-converter/src/test/resources/multiInstanceUserTaskModel.bpmn
Related to 
https://github.com/Activiti/Activiti/issues/3160
> #3160 change order of generated xml elements

- activiti-core/activiti-engine/pom.xml
- activiti-core/activiti-spring/pom.xml
- activiti-core/pom.xml
> jaxb moved to compile (#2413)

- activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/bpmn/deployer/BpmnDeployer.java
- activiti-core/activiti-engine/src/test/java/org/activiti/engine/impl/bpmn/deployer/BpmnDeployerTest.java
Set application version when deployment exists already
> Set application version when deployment exists already

- activiti-core/activiti-spring-process-extensions/src/main/java/org/activiti/spring/process/conf/ProcessExtensionsAutoConfiguration.java
Add new data type "folder" to auto configuration.
Depends on https://github.com/Activiti/activiti-cloud/pull/42
> [AAE-2262] Add folder type

- activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/cmd/CreateProcessInstanceCmd.java
- activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/cmd/StartProcessInstanceCmd.java
- activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/util/ProcessDefinitionRetriever.java
Centralised the logic for the process definition retrieving.
> [DW-1668] - centralised the logic for retrieving the Process definition

- .lgtm.yml
- .travis.yml
- pom.xml
> drop java 8 support

- activiti-api/activiti-api-task-model/pom.xml
- activiti-api/activiti-api-task-model/src/main/java/org/activiti/api/task/model/builders/TaskPayloadBuilder.java
- activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/el/ExpressionManager.java
- activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/el/VariableScopeElResolver.java
- activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/el/variable/AuthenticatedUserELResolver.java
- activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/el/variable/ExecutionElResolver.java
- activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/el/variable/ProcessInitiatorELResolver.java
- activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/el/variable/TaskElResolver.java
- activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/el/variable/VariableElResolver.java
- activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/el/variable/VariableScopeItemELResolver.java
- activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/variable/JsonType.java
- activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/variable/LongJsonType.java
- activiti-core/activiti-engine/src/test/java/org/activiti/engine/impl/el/VariableScopeElResolverTest.java
- activiti-core/activiti-engine/src/test/java/org/activiti/engine/impl/el/variable/AuthenticatedUserELResolverTest.java
- activiti-core/activiti-engine/src/test/java/org/activiti/engine/impl/el/variable/ExecutionElResolverTest.java
- activiti-core/activiti-engine/src/test/java/org/activiti/engine/impl/el/variable/ProcessInitiatorELResolverTest.java
- activiti-core/activiti-engine/src/test/java/org/activiti/engine/impl/el/variable/TaskElResolverTest.java
- activiti-core/activiti-engine/src/test/java/org/activiti/engine/impl/el/variable/VariableElResolverTest.java
- activiti-core/activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/tasks/TaskRuntimeIT.java
- activiti-core/activiti-spring-boot-starter/src/test/resources/processes/TaskToInitiatorProcess.bpmn20.xml
- activiti-core/activiti-spring/src/main/java/org/activiti/spring/SpringExpressionManager.java
Fixes https://github.com/Activiti/Activiti/issues/3243
> Add expression resolver to handle process initiator

- activiti-core/activiti-spring-process-extensions/src/main/java/org/activiti/spring/process/conf/ProcessExtensionsAutoConfiguration.java
Add new array data type to auto configuration
> [AAE-2335] Create array process variable type

- activiti-core/activiti-api-impl/activiti-api-process-runtime-impl/src/main/java/org/activiti/runtime/api/conf/ProcessRuntimeAutoConfiguration.java
- activiti-core/activiti-api-impl/activiti-api-process-runtime-impl/src/main/java/org/activiti/runtime/api/event/impl/ToProcessCancelledConverter.java
- activiti-core/activiti-api-impl/activiti-api-process-runtime-impl/src/main/java/org/activiti/runtime/api/event/internal/ProcessCancelledListenerDelegate.java
- activiti-core/activiti-engine/src/main/java/org/activiti/engine/delegate/event/ActivitiProcessCancelledEvent.java
- activiti-core/activiti-engine/src/main/java/org/activiti/engine/delegate/event/impl/ActivitiEventBuilder.java
- activiti-core/activiti-engine/src/main/java/org/activiti/engine/delegate/event/impl/ActivitiProcessCancelledEventImpl.java
- activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/bpmn/behavior/TerminateEndEventActivityBehavior.java
- activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/persistence/entity/ExecutionEntityManagerImpl.java
- activiti-core/activiti-engine/src/test/java/org/activiti/engine/test/api/event/ExecutionEventsTest.java
- activiti-core/activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/process/ProcessRuntimeEventsIT.java
- activiti-core/activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/process/ProcessRuntimeIT.java
- activiti-core/activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/process/ProcessRuntimeTerminatedEndEventIT.java
- modify former ActivitiProcessCancelledEventImpl to include the process instance that is being cancelled
Fixes https://github.com/Activiti/Activiti/issues/3250
> Populate ProcessCancelledEvent with available information

- pom.xml
> use awaitility version as in Spring Boot 2.2

- pom.xml
> Update Spring Boot to 2.1.13.RELEASE

- modules/activiti-ui/activiti-app/src/main/webapp/META-INF/context.xml
> 'debug' attribute is no longer supported.

- activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/persistence/entity/ExecutionEntityImpl.java
> #3302 Fixd

- activiti-core/activiti-engine/src/main/java/org/activiti/engine/impl/persistence/entity/ExecutionEntityImpl.java
Reverts Activiti/Activiti#3303
> Revert "#3302 Fixd"
